-- Ejecutar en Supabase -> SQL Editor -> New query -> Run.
-- Requiere 01_esquema.sql.
--
-- Personajes de High School DxD: OPI: 22. Cada fila lleva todo: datos, icono, biografia y
-- materiales de ascension.
--
-- Los datos son una copia de la base de datos tal y como estaba el 2026-09-15.
-- Inserta lo que falte y actualiza lo que ya exista, sin borrar nada: los
-- favoritos, tier lists y guias de los usuarios que apuntan a estas filas se
-- conservan. Ojo: si has cambiado algo desde la app despues de esa fecha,
-- ejecutarlo lo devuelve a como estaba en la copia.

insert into public.characters (
  id, game_id, name, image_url, rarity, element, level_cap, description, role, path, signature, is_upcoming, biography, biography_source, biography_en, biography_source_en, biography_es, biography_source_es, biography_es_translated, ascension
)
values
  ('dxd-akeno', 'high-school-dxd-opi', 'Akeno Himejima', null, null, null, null, 'Reina del grupo Gremory', null, null, null, false, 'Akeno is a beautiful young woman with a voluptuous figure, very long black hair and violet eyes. Her hair is usually tied in a very long ponytail, reaching all the way down to the floor with two strands sticking out from the top and sloping backward, with an orange ribbon keeping it in place.

Like most of the girls at Kuoh Academy, she wears the customary Kuoh Academy girls'' school uniform, along with black calf-length socks.

As revealed in the visual book with her data , her body measurements are [B102-W60-H89 cm] [B40-W24-H35 in]. Her body weight is [54 kg] [119 lbs] while her height is 168 cm (5 feet 6 inches).

In the anime, during battles, she often transforms her clothes into a traditional attire, consisting of a white with red accents, a red , and a pair of with white .

After Akeno has revealed her Fallen Angel side in front of Issei, she has one Devil wing and one Fallen Angel wing.', 'https://highschooldxd.fandom.com/wiki/Akeno%20Himejima', 'Akeno is a beautiful young woman with a voluptuous figure, very long black hair and violet eyes. Her hair is usually tied in a very long ponytail, reaching all the way down to the floor with two strands sticking out from the top and sloping backward, with an orange ribbon keeping it in place.

Like most of the girls at Kuoh Academy, she wears the customary Kuoh Academy girls'' school uniform, along with black calf-length socks.

As revealed in the visual book with her data , her body measurements are [B102-W60-H89 cm] [B40-W24-H35 in]. Her body weight is [54 kg] [119 lbs] while her height is 168 cm (5 feet 6 inches).

In the anime, during battles, she often transforms her clothes into a traditional attire, consisting of a white with red accents, a red , and a pair of with white .

After Akeno has revealed her Fallen Angel side in front of Issei, she has one Devil wing and one Fallen Angel wing.', 'https://highschooldxd.fandom.com/wiki/Akeno%20Himejima', 'Akeno es una voluptuosa joven de la misma edad que Rias con un largo cabello negro y ojos violetas. Su cabello esta usualmente atado en una larga cola de caballo que le llega hasta las piernas con dos antenas que sobresalen de la parte superior que se inclinan hacia atrás, con un listón naranja que mantiene todo en su lugar. Como la mayoría de las chicas en la Academia Kuoh, ella lleva el uniforme escolar femenino de la academia Kuoh, junto con calcetines negros hasta la rodilla.

Cuando se reveló como un Ángel Caído delante de Issei en el Volumen 4, le creció un ala de Demonio y una de Ángel Caído.', 'https://highschooldxd.fandom.com/es/wiki/Akeno%20Himejima', false, null),
  ('dxd-asia', 'high-school-dxd-opi', 'Asia Argento', null, null, null, null, 'Alfil del grupo Gremory · Twilight Healing', null, null, null, false, 'thumb|left|130px
Asia is a beautiful young girl with long blonde hair and green eyes. Her body measurements are [B83→85-W55-H81→83 cm]; her height is [155 cm] [5 feet 1 inch] and her body weight is [44→45 kg] [97→98 lbs]. Her hair flows all the way down to her back, with split bangs over her forehead and a single strand sticking out from the top and sloping backward.

Her former main attire consisted of a dark teal nun outfit with light blue accents, a white veil over her head with light blue accents, a brown satchel slung on her right hip (where she holds her Bible), and brown boots with black straps in an X-shaped pattern.', 'https://highschooldxd.fandom.com/wiki/Asia%20Argento', 'Asia is a beautiful young girl with long blonde hair and green eyes. Her body measurements are [B83→85-W55-H81→83 cm]; her height is [155 cm] [5 feet 1 inch] and her body weight is [44→45 kg] [97→98 lbs]. Her hair flows all the way down to her back, with split bangs over her forehead and a single strand sticking out from the top and sloping backward.

Her former main attire consisted of a dark teal nun outfit with light blue accents, a white veil over her head with light blue accents, a brown satchel slung on her right hip (where she holds her Bible), and brown boots with black straps in an X-shaped pattern.', 'https://highschooldxd.fandom.com/wiki/Asia%20Argento', 'Asia es una chica de alrededor de 15-16 años de edad con un largo cabello rubio y ojos verdes. Su cabello largo llega hasta la espalda, con un flequillo dividido sobre la frente y un solo filamento que sobresale de la parte superior estilo ahoge, inclinándose hacia atrás. De todas las chicas del Club de Investigación de lo Oculto en términos de tamaño de los senos, los suyos parecen ser uno de los más "modestos". Sus medidas son Busto 83cm - Cintura 55cm - Cadera 81cm

Su traje principal consiste en un traje de monja azul oscuro con detalles en azul claro, un velo blanco sobre su cabeza con detalles en azul claro, un sachel marrón colgado a la derecha de la cadera (donde ella tiene su Biblia), y botas marrones con correas negras en un patrón de X.', 'https://highschooldxd.fandom.com/es/wiki/Asia%20Argento', false, null),
  ('dxd-azazel', 'high-school-dxd-opi', 'Azazel', null, null, null, null, 'Gobernador de los Ángeles Caídos', null, null, null, false, 'Azazel is a tall man appearing to be in his twenties with an average build, black hair, golden bangs, and black goatee. He also possesses twelve jet-black feathered wings that grow out from his back. It is described by Vali to be a never ending black.

During the Summit, Azazel wore a V-neck maroon long-coat with a wide, open high-collar that opens up at the hem. The long-coat also featured two black belts around the waist and four black bands on each arm, two of the bands at the wrist and the other two near the elbow. He wore grey slacks and brown shoes.

After the events in Volume 4, he loses his left arm, but replaces it with a prosthetic arm made from his Sacred Gear research.

When he served as a Chemistry teacher at Kuoh Academy, Azazel wore a knee-length dark blue blazer with a lighter blue dress shirt, a black waist coat, and a red tie. He wore faded-purple slacks and black dress shoes.', 'https://highschooldxd.fandom.com/wiki/Azazel', 'Azazel is a tall man appearing to be in his twenties with an average build, black hair, golden bangs, and black goatee. He also possesses twelve jet-black feathered wings that grow out from his back. It is described by Vali to be a never ending black.

During the Summit, Azazel wore a V-neck maroon long-coat with a wide, open high-collar that opens up at the hem. The long-coat also featured two black belts around the waist and four black bands on each arm, two of the bands at the wrist and the other two near the elbow. He wore grey slacks and brown shoes.

After the events in Volume 4, he loses his left arm, but replaces it with a prosthetic arm made from his Sacred Gear research.

When he served as a Chemistry teacher at Kuoh Academy, Azazel wore a knee-length dark blue blazer with a lighter blue dress shirt, a black waist coat, and a red tie. He wore faded-purple slacks and black dress shoes.', 'https://highschooldxd.fandom.com/wiki/Azazel', 'Azazel es un hombre de una estatura alta de ojos color violeta su cabello es de color negro salvo en la parte de adelante que lleva el color amarillo. También lleva un traje Kimono de color cafe claro y su cuidada barba.

En el volumen 4 el pierde el brazo debido al el enfrentamiento con katarea leviatan, es reemplazado por un brazo mecanico.

Azazel como Ex-jefe de los ángeles caídos posee 6 pares de alas.', 'https://highschooldxd.fandom.com/es/wiki/Azazel', false, null),
  ('dxd-gasper', 'high-school-dxd-opi', 'Gasper Vladi', null, null, null, null, 'Alfil del grupo Gremory · vampiro', null, null, null, false, 'Gasper is an effeminate-looking male with platinum blond hair and pinkish-violet eyes. His hair is styled in short bob cut with several small fringes over his forehead, and he has pointed ears. Kiba describes him as looking like a beautiful girl.

Unlike the rest of the boys of Kuoh Academy who wear the boys'' uniform, Gasper wears the Kuoh Academy girls'' school uniform with thigh-high socks, creating a Zettai Ryōiki (絶対領域, Absolute Territory).

Originally a coward and a shut-in with a very shy personality, Gasper likes to wear female clothing, claiming that girls'' clothes are cute. He also has a penchant for boxes, carrying one with him all the time. When Issei tried to give Gasper confidence, the former gave Gasper a paper bag to put over the latter''s face. However, Issei comments that whenever Gasper puts the paper bag on, the latter looks like a molester.

As the series progresses, with Issei and the Gremory group''s encouragement, Gasper begins to gain confidence and bravery.', 'https://highschooldxd.fandom.com/wiki/Gasper%20Vladi', 'Gasper is an effeminate-looking male with platinum blond hair and pinkish-violet eyes. His hair is styled in short bob cut with several small fringes over his forehead, and he has pointed ears. Kiba describes him as looking like a beautiful girl.

Unlike the rest of the boys of Kuoh Academy who wear the boys'' uniform, Gasper wears the Kuoh Academy girls'' school uniform with thigh-high socks, creating a Zettai Ryōiki (絶対領域, Absolute Territory).

Originally a coward and a shut-in with a very shy personality, Gasper likes to wear female clothing, claiming that girls'' clothes are cute. He also has a penchant for boxes, carrying one with him all the time. When Issei tried to give Gasper confidence, the former gave Gasper a paper bag to put over the latter''s face. However, Issei comments that whenever Gasper puts the paper bag on, the latter looks like a molester.

As the series progresses, with Issei and the Gremory group''s encouragement, Gasper begins to gain confidence and bravery.', 'https://highschooldxd.fandom.com/wiki/Gasper%20Vladi', 'Gasper es un chico de aspecto andrógino que tiene alrededor de la misma edad de Koneko con el cabello rubio platino y ojos de color rojo. A diferencia del resto de los chicos de la Academia Kuoh que usan el uniforme varonil, Gasper usa el uniforme de las chicas de la Academia Kuoh con largas calcetas negras que le llegan al muslo.

Originalmente es un cobarde y un introvertido, a Gasper le gusta usar ropa femenina, alegando que la ropa de las chicas es muy linda (para gran enfado de Issei). También tiene una inclinación por las cajas, llevando una con él todo el tiempo. A medida que avanza serie, Gasper comienza a ser más confiado y se vuelve más valiente.', 'https://highschooldxd.fandom.com/es/wiki/Gasper%20Vladi', false, null),
  ('dxd-grayfia', 'high-school-dxd-opi', 'Grayfia Lucifuge', null, null, null, null, 'Reina de Sirzechs · sirvienta del clan Gremory', null, null, null, false, 'Grayfia is a beautiful young woman with a voluptuous body, appearing to be in her early twenties with back-length silver hair that features a long braid on each side with small blue bows at the ends, while the rest is let down which ends in twin braids and red eyes (silver in the anime).

While on her days off as a maid, Grayfia''s normal outfit has few noticeable differences is that she looks younger, her eyes are red and she has a faded-pink scrunchy on her, as opposed to the blue maid outfit. Her outfit is a black shirt with golden-caramel accents at the edges of the shirt and spread horizontally near the bottom, with two light golden trims going down the shirt; and the shirt splits slightly above her stomach, exposing her midriff. Around her neck and shoulders is a long, cyan scarf made from light material that reaches her hips.', 'https://highschooldxd.fandom.com/wiki/Grayfia%20Lucifuge', 'Grayfia is a beautiful young woman with a voluptuous body, appearing to be in her early twenties with back-length silver hair that features a long braid on each side with small blue bows at the ends, while the rest is let down which ends in twin braids and red eyes (silver in the anime).

While on her days off as a maid, Grayfia''s normal outfit has few noticeable differences is that she looks younger, her eyes are red and she has a faded-pink scrunchy on her, as opposed to the blue maid outfit. Her outfit is a black shirt with golden-caramel accents at the edges of the shirt and spread horizontally near the bottom, with two light golden trims going down the shirt; and the shirt splits slightly above her stomach, exposing her midriff. Around her neck and shoulders is a long, cyan scarf made from light material that reaches her hips.', 'https://highschooldxd.fandom.com/wiki/Grayfia%20Lucifuge', 'Ella es una mujer hermosa tiene el cabello color plata y ojos celestes, y segun todas las chicas del Club de Investigaciones de lo Oculto es la Gran Onee-Sama, Issei afirma que supera a Rias en su figura y atributos.

Es una mujer tranquila y reservada, ademas de muy estricta. Siempre toma encerio su trabajo mientras trabaja como sirvienta de la casa Gremory.

Cuando esta en sus días Libres se convierte en La Esposa de Sirzech Lucifer, madre de Millicas Gremory y la Onne-sama de Rias Gremory, ella tambien toma su papel como esposa de Sirzechs Lucifer muy enserio y aparece como una Dama de Clase alta, Es muy amable pero estricta.', 'https://highschooldxd.fandom.com/es/wiki/Grayfia%20Lucifuge', false, null),
  ('dxd-irina', 'high-school-dxd-opi', 'Irina Shidou', null, null, null, null, 'Ángel y amiga de la infancia de Issei', null, null, null, false, 'Irina is a beautiful young woman with violet eyes. She has long chestnut hair that is usually tied into twintails, each held with a blue scrunchy, but on some occasions, she lets her hair down. Her body measurements are B87-W59-H89 cm [B34-W23-H35 in]; height is 164 cm (5 feet 4 inches) and body weight is 56 kg.

She wears the standard Church battle attire, same as Xenovia''s with some slight differences. After transferring to Kuoh Academy and moving into the Hyoudou Residence, she starts wearing the Kuoh Academy girls'' school uniform, with black short shorts under her skirt and the addition of white sneakers with blue accents.

Following her Angelization by Michael, she wears a red "A" printed on her right hand, symbolizing her position as Michael''s Ace. Irina also gained white Angel wings and a halo, as of Volume 17, she has a total of 4 wings.

Irina is a cheerful, goofy, upbeat, and enthusiastic person.', 'https://highschooldxd.fandom.com/wiki/Irina%20Shidou', 'Irina is a beautiful young woman with violet eyes. She has long chestnut hair that is usually tied into twintails, each held with a blue scrunchy, but on some occasions, she lets her hair down. Her body measurements are B87-W59-H89 cm [B34-W23-H35 in]; height is 164 cm (5 feet 4 inches) and body weight is 56 kg.

She wears the standard Church battle attire, same as Xenovia''s with some slight differences. After transferring to Kuoh Academy and moving into the Hyoudou Residence, she starts wearing the Kuoh Academy girls'' school uniform, with black short shorts under her skirt and the addition of white sneakers with blue accents.

Following her Angelization by Michael, she wears a red "A" printed on her right hand, symbolizing her position as Michael''s Ace. Irina also gained white Angel wings and a halo, as of Volume 17, she has a total of 4 wings.

Irina is a cheerful, goofy, upbeat, and enthusiastic person.', 'https://highschooldxd.fandom.com/wiki/Irina%20Shidou', 'Irina es una joven de alrededor de la edad de Issei con un largo cabello castaño claro y ojos de color violeta. Su cabello esta usualmente agarrado en dos coletas, cada una con una liga azul, pero en algunas ocasiones de deja el cabello suelto.

Ella usaba el traje de batalla estándar de la iglesia durante su volumen introductorio. Después al ser transferida a la Academia Kuoh y mudarse a la residencia Hyōdō, comienza a utilizar el uniforme femenino escolar de la academia Kuoh, con la adición de zapatillas blancas con detalles en azul y un leotardo negro debajo de la falda. Después de su Angelización por Michael, usa una A roja impresa en la mano derecha, que simboliza su posición como As de Michael.

Irina es una persona alegre, despreocupada, optimista, amigable, algo infantil y entusiasta.', 'https://highschooldxd.fandom.com/es/wiki/Irina%20Shidou', false, null),
  ('dxd-issei', 'high-school-dxd-opi', 'Issei Hyodo', null, null, null, null, 'Peón de Rias · portador del Boosted Gear', null, null, null, false, 'thumb|left|130px|Issei''s profile picture. 
Issei is an average high school student with short, spiky brown hair, two short locks of hair behind his head, and light brown eyes. He gained a more muscular and toned build following his training with Tannin.

While he has worn various outfits throughout the series, his most commonly worn outfit is the Kuoh Academy boys'' school uniform, which consists of a blazer (more commonly black, although in other media is shown with a tinge of purple or grey, with white accents) over a white, long-sleeved dress shirt with black highlights with a black ribbon on the collar, matching black pants, and brown dress shoes.', 'https://highschooldxd.fandom.com/wiki/Issei%20Hyoudou', 'Issei is an average high school student with short, spiky brown hair, two short locks of hair behind his head, and light brown eyes. He gained a more muscular and toned build following his training with Tannin.

While he has worn various outfits throughout the series, his most commonly worn outfit is the Kuoh Academy boys'' school uniform, which consists of a blazer (more commonly black, although in other media is shown with a tinge of purple or grey, with white accents) over a white, long-sleeved dress shirt with black highlights with a black ribbon on the collar, matching black pants, and brown dress shoes. 

However, Issei''s uniform differs in the fact that he wears a red T-shirt underneath his open dress shirt and blazer and wears blue (recently red) and white sneakers in place of dress shoes.

Before fighting Riser in a rematch, Issei''s left arm was transformed into a Dragon''s arm, which needed a ritual performed regularly by Rias and Akeno to appear human.', 'https://highschooldxd.fandom.com/wiki/Issei%20Hyoudou', 'Issei es un hombre joven en sus años de adolescencia con un cuerpo promedio, de pelo corto castaño con varios flequillos que cubren parcialmente sus cejas y dos extensiones de cabello que cuelgan paralelamente a su nuca y ojos marrones. Después de su entrenamiento con Tannin, él obtuvo una complexión más musculosa y tonificada.

Mientras que él ha usado varios trajes en toda la serie, su traje más comúnmente usado es el uniforme de la Academia Kouh, que consiste en una Chaqueta (más comúnmente negro, aunque en otros medios se muestra con un tinte de color púrpura o gris, con detalles en blanco) sobre una camisa de manga larga blanca reflejos negros con un lazo negro en el cuello, pantalones negros a juego y zapatos de vestir cafés. Sin embargo, Issei usa diferente el uniforme en el hecho de que lleva una playera roja debajo de su camisa y chaqueta, y lleva zapatillas de deporte blancas y azules en lugar de zapatos de vestir.', 'https://highschooldxd.fandom.com/es/wiki/Issei', false, null),
  ('dxd-koneko', 'high-school-dxd-opi', 'Koneko Toujou', null, null, null, null, 'Torre del grupo Gremory · nekomata', null, null, null, false, 'thumb|left|140px
Koneko is a petite girl with white hair and gold eyes. Her body measurements are [B67-W57-H73 cm] [B26-W22-H29 in]. Her weight is [31 kg] [68 lbs]. The front of her hair has two long bangs going past her shoulders and several loose bangs hanging over her forehead, while the back has a short bob cut. She also wears a black cat-shaped hair clip on both sides of her hair, one of which contained the data on artificially making new Super Devils. 

She usually wears the Kuoh Academy girls'' school uniform, without the shoulder cape. Koneko''s height is 138 cm (4 feet 6 inches), making her one of the shortest female characters of the series.

In her Nekomata form, she grows a pair of white cat ears and a pair of matching white tails, and her pupils become more cat-like.', 'https://highschooldxd.fandom.com/wiki/Koneko%20Toujou', 'Koneko is a petite girl with white hair and gold eyes. Her body measurements are [B67-W57-H73 cm] [B26-W22-H29 in]. Her weight is [31 kg] [68 lbs]. The front of her hair has two long bangs going past her shoulders and several loose bangs hanging over her forehead, while the back has a short bob cut. She also wears a black cat-shaped hair clip on both sides of her hair, one of which contained the data on artificially making new Super Devils. 

She usually wears the Kuoh Academy girls'' school uniform, without the shoulder cape. Koneko''s height is 138 cm (4 feet 6 inches), making her one of the shortest female characters of the series.

In her Nekomata form, she grows a pair of white cat ears and a pair of matching white tails, and her pupils become more cat-like. In Volume 24, she gained three tails.

In her "Shirone Mode" that she used for the first time in Volume 16, Koneko can make herself grow older, and her attire consists of a short white kimono and a light blue skirt.', 'https://highschooldxd.fandom.com/wiki/Koneko%20Toujou', 'Koneko es una pequeña chica de unos 15 años de edad con el cabello blanco y los ojos de color avellana. En el frente, su cabello tiene dos flequillos largos que van más allá de sus hombros y varios flequillos sueltos colgando sobre la frente, mientras que la parte trasera tiene el cabello corto. También lleva un broche de cabello en forma de gato negro a ambos lados de la cabeza. Ella viste el uniforme femenino de la academia Kuoh, aunque sin la capa de los hombros. En su forma Nekomata, le crecen un par de blancas orejas de gato y una cola a juego, y sus pupilas se vuelven más felinas.

Al comienzo de la serie, Koneko tenía una personalidad muy fria, rara vez mostrando algún sentimiento o emoción, incluso cuando hablaba. También era la única en el grupo que no se llevaba bien con Issei, a menudo lo insultaba y le reprochaba su debilidad y su naturaleza pervertida, aunque también lo respetaba por nunca darse por vencido.', 'https://highschooldxd.fandom.com/es/wiki/Koneko%20Toujou', false, null),
  ('dxd-kuroka', 'high-school-dxd-opi', 'Kuroka', null, null, null, null, 'Nekomata · hermana mayor de Koneko', null, null, null, false, 'Kuroka is a beautiful young woman with a voluptuous figure, long black hair with split bangs, and hazel-gold eyes with cat-like pupils. Her body measurements are [B98-W57-H86 cm] [B39-W23-H35 in]; height is 161 cm (5 feet 3 inches) and body weight is [49 kg].

Her attire consists of a black kimono, a yellow obi, a set of golden beads, and an ornately detailed headband. The kimono features a red interior and it is open at her shoulders, giving view to her large breasts which rival those of Rias and Akeno in terms of size.

In her Nekomata form, which she is in all the time, she grows a pair of black cat ears and two black tails.

At first, Kuroka was shown to be rather malicious, with her aura described as being more "outright evil" when compared to the "vice" of Azazel''s. In the past, she was said to have murdered her previous master, as she was unable to gain control over her Senjutsu, and was driven mad as a result.', 'https://highschooldxd.fandom.com/wiki/Kuroka', 'Kuroka is a beautiful young woman with a voluptuous figure, long black hair with split bangs, and hazel-gold eyes with cat-like pupils. Her body measurements are [B98-W57-H86 cm] [B39-W23-H35 in]; height is 161 cm (5 feet 3 inches) and body weight is [49 kg].

Her attire consists of a black kimono, a yellow obi, a set of golden beads, and an ornately detailed headband. The kimono features a red interior and it is open at her shoulders, giving view to her large breasts which rival those of Rias and Akeno in terms of size.

In her Nekomata form, which she is in all the time, she grows a pair of black cat ears and two black tails.

At first, Kuroka was shown to be rather malicious, with her aura described as being more "outright evil" when compared to the "vice" of Azazel''s. In the past, she was said to have murdered her previous master, as she was unable to gain control over her Senjutsu, and was driven mad as a result.', 'https://highschooldxd.fandom.com/wiki/Kuroka', 'Kuroka es una joven con una figura voluptuosa, tiene el pelo largo negro y ojos color avellana con pupilas felinas. Su vestimenta consiste en un kimono negro, faja amarilla, un juego de cuentas de oro, y una venda adornada detalladamente. El interior del kimono es rojo y está abierto en sus hombros, dejando a la vista sus grandes pechos que rivaliza con los de Rias y Akeno en términos de tamaño. En su forma de Nekomata, le aparecen un par de orejas de gato negro y dos colas negras.

Kuroka parece muy juguetona, despreocupada, y disfruta tomar el pelo a la gente. Ella es también vulgar, usando su belleza y sensualidad como un arma en su arsenal de burlas. Kuroka ama mucho a su pequeña hermana Koneko, aunque ella parece tener problemas para demostrarlo aveces, prefiriendo burlarse de ella. Ella ha expresado un interés en tener niños fuertes, y le ha hecho proposiciones tanto a Vali como a Issei, ya que ambos tienen Dragones Celestiales dentro de ellos.', 'https://highschooldxd.fandom.com/es/wiki/Kuroka', false, null),
  ('dxd-ophis', 'high-school-dxd-opi', 'Ophis', null, null, null, null, 'Dios Dragón del Infinito', null, null, null, false, 'Ophis'' current appearance is that of a cute young girl with long black hair down to her hips and black eyes (gray in the anime). Her ears differ from a normal human''s as they have pointed tips, although her long black hair makes this feature difficult to notice. Her dark grey eyes have reptilian slitted pupils. Azazel stated that Ophis had the appearance of an old man in the past before changing it. Her body measurements are [B66-W53-H70]; height is [137 cm] and body weight is [31 kg].

Her attire consists of a black Gothic Lolita fashion.

However, Ophis is a true shapeshifter, able to freely manipulate her body shape and size to assume any form that she chooses, regardless of her age, race, or gender. There''s been no hint thus far of her true Dragon form, only her current human disguise and it''s predecessor.

Ophis is an extremely "low-key" individual, with a distinctly subdued demeanor and muted emotions.', 'https://highschooldxd.fandom.com/wiki/Ophis', 'Ophis'' current appearance is that of a cute young girl with long black hair down to her hips and black eyes (gray in the anime). Her ears differ from a normal human''s as they have pointed tips, although her long black hair makes this feature difficult to notice. Her dark grey eyes have reptilian slitted pupils. Azazel stated that Ophis had the appearance of an old man in the past before changing it. Her body measurements are [B66-W53-H70]; height is [137 cm] and body weight is [31 kg].

Her attire consists of a black Gothic Lolita fashion.

However, Ophis is a true shapeshifter, able to freely manipulate her body shape and size to assume any form that she chooses, regardless of her age, race, or gender. There''s been no hint thus far of her true Dragon form, only her current human disguise and it''s predecessor.

Ophis is an extremely "low-key" individual, with a distinctly subdued demeanor and muted emotions.', 'https://highschooldxd.fandom.com/wiki/Ophis', 'El aspecto actual de Ophis es el de una joven menuda y adorable, con el pelo negro y largo hasta las caderas y los ojos negros (grises en el anime). Sus orejas se diferencian de las de un humano normal por su punta afilada, aunque su larga melena hace difícil apreciarlo. Sus ojos, de un gris oscuro, tienen pupilas rasgadas de reptil. Azazel afirmó que Ophis tenía en el pasado la apariencia de un anciano antes de cambiarla. Su indumentaria consiste en un atuendo negro de estilo lolita gótico.

Sin embargo, Ophis es una auténtica cambiaformas, capaz de manipular libremente la forma y el tamaño de su cuerpo para adoptar el aspecto que desee, sin importar edad, raza o género. Hasta ahora no se ha visto ni un indicio de su verdadera forma de dragón: solo su disfraz humano actual y el anterior.

Ophis es un ser extremadamente discreto, de actitud contenida y emociones apagadas.', 'https://highschooldxd.fandom.com/wiki/Ophis', true, null),
  ('dxd-ravel', 'high-school-dxd-opi', 'Ravel Phenex', null, null, null, null, 'Alfil del clan Phenex', null, null, null, false, 'Ravel is a beautiful young girl with dark blue eyes. She has long blonde hair tied into twintails with large, drill-like curls and blue ribbons keeping them in place. The front of her hair has several bangs hanging over her forehead, with a V-shaped fringe hanging over the bridge of her nose. Ravel''s body measurements are [B85-W59-H84 cm] (B33-W23-H33 in); height is 153 cm (5 feet 0 inches) and body weight is [47 kg].

Her initial outfit consisted of a light purple dress with dark purple accents and a blue bow at the front. At the back, three feather-like extensions mimicking a bird''s tail protrude from the dress, which, when combined with her wings of fire, give her a bird-like appearance.', 'https://highschooldxd.fandom.com/wiki/Ravel%20Phenex', 'Ravel is a beautiful young girl with dark blue eyes. She has long blonde hair tied into twintails with large, drill-like curls and blue ribbons keeping them in place. The front of her hair has several bangs hanging over her forehead, with a V-shaped fringe hanging over the bridge of her nose. Ravel''s body measurements are [B85-W59-H84 cm] (B33-W23-H33 in); height is 153 cm (5 feet 0 inches) and body weight is [47 kg].

Her initial outfit consisted of a light purple dress with dark purple accents and a blue bow at the front. At the back, three feather-like extensions mimicking a bird''s tail protrude from the dress, which, when combined with her wings of fire, give her a bird-like appearance.', 'https://highschooldxd.fandom.com/wiki/Ravel%20Phenex', 'Ravel es una chica joven con el pelo largo y rubio y ojos azules oscuros. Su pelo está atado en dos coletas doble de grandes rizos, con cintas azules para mantenerlos en su lugar. Su equipo inicial consistió en un vestido de color morado claro con acentos de color púrpura oscuro y un arco azul en la parte delantera. En la parte trasera, tres extensiones de pluma que imitan la cola de un ave Fenix sobresalen del vestido, que, cuando se combina con sus alas de fuego, le dan una apariencia al Ave Fenix. Al transferirse a la Academia Kuoh, ella viste el uniforme de la academia Kuoh, con la adición de un suéter negro sobre su camisa de vestir. En el anime, Ravel lleva un vestido largo, de color rosa con adornos blancos y un arco magenta en la parte delantera.', 'https://highschooldxd.fandom.com/es/wiki/Ravel%20Phoenix', false, null),
  ('dxd-rias', 'high-school-dxd-opi', 'Rias Gremory', null, null, null, null, 'Rey del grupo Gremory · heredera del clan', null, null, null, false, 'thumb|left|130px
Rias is a beautiful young woman with a voluptuous body, white skin, blue eyes (blue-green in the anime, season 1-3) inherited from her father, Zeoticus, and a buxom figure. Her body measurements are [B99-W58-H90 cm] [B39-W23-H35 in]. Her body weight is [58 kg] [128 lbs]. 

Her most distinctive feature is her long, beautiful crimson hair, which she also inherited from her father, that reaches down to her thighs with a single hair strand (known in Japan as ahoge) sticking out from the top. Her hair also has loose bangs covering her forehead and side bangs framing her face. Rias'' height is 172 cm.', 'https://highschooldxd.fandom.com/wiki/Rias%20Gremory', 'Rias is a beautiful young woman with a voluptuous body, white skin, blue eyes (blue-green in the anime, season 1-3) inherited from her father, Zeoticus, and a buxom figure. Her body measurements are [B99-W58-H90 cm] [B39-W23-H35 in]. Her body weight is [58 kg] [128 lbs]. 

Her most distinctive feature is her long, beautiful crimson hair, which she also inherited from her father, that reaches down to her thighs with a single hair strand (known in Japan as ahoge) sticking out from the top. Her hair also has loose bangs covering her forehead and side bangs framing her face. Rias'' height is 172 cm.', 'https://highschooldxd.fandom.com/wiki/Rias%20Gremory', 'Rias es una hermosa mujer con una figura muy hermosa, de piel clara con ojos azul celeste casi verdosos y un característico cabello color carmesí que le llega hasta los muslos, con una sola hebra de caballo (que en Japón se conoce como Ahoge (アホ毛), o el pelo idiota) que sobresale de la parte superior de su cabeza. También tiene largo el flequillo que a parte de tapar parte de su frente enmarca su cara al estar más largo por los laterales de esta. Aunque esta ha llevado varios tipos de ropa la que más usa es el uniforme para chicas de la academia, estando este compuesto de una camisa blanca de manga larga abotonada (aunque de manga corta para primavera/verano) con una cinta negra en el cuello de la camisa, también lleva una chaqueta sobre la camisa que le tapa los hombros y llega hasta tan solo algo más arriba de la cintura dejando así la camisa blanca sobre el pecho al descubierto. Por último tiene falda magenta con acentos blancos y zapatos de vestir marrones con calcetines altos.', 'https://highschooldxd.fandom.com/es/wiki/Rias%20Gremory', false, null),
  ('dxd-rossweisse', 'high-school-dxd-opi', 'Rossweisse', null, null, null, null, 'Torre del grupo Gremory · antigua valquiria', null, null, null, false, 'Rossweisse is a beautiful young woman with long, straight silver hair and aqua-colored eyes who appears to be in her late teens. Her body measurements are [B96-W61-H89 cm] [B38-W24-H35 in]; height is 173 cm (5 feet 8 inches) and body weight is [59 kg].

Her battle attire is normally of a set of Valkyrie armor, which consists of a white breastplate with gold and pale blue accents and matching, fingerless gauntlets, boots, hip guards, and wing-shaped hair clips. She also wears a black leotard underneath her breastplate, black thigh-high stockings, and a pale blue cloth wrapped underneath her hip guards, all of which are clad with pink lacing along with her hair clips.

For her teaching position at Kuoh Academy, she wears a simple business suit and skirt.', 'https://highschooldxd.fandom.com/wiki/Rossweisse', 'Rossweisse is a beautiful young woman with long, straight silver hair and aqua-colored eyes who appears to be in her late teens. Her body measurements are [B96-W61-H89 cm] [B38-W24-H35 in]; height is 173 cm (5 feet 8 inches) and body weight is [59 kg].

Her battle attire is normally of a set of Valkyrie armor, which consists of a white breastplate with gold and pale blue accents and matching, fingerless gauntlets, boots, hip guards, and wing-shaped hair clips. She also wears a black leotard underneath her breastplate, black thigh-high stockings, and a pale blue cloth wrapped underneath her hip guards, all of which are clad with pink lacing along with her hair clips.

For her teaching position at Kuoh Academy, she wears a simple business suit and skirt.', 'https://highschooldxd.fandom.com/wiki/Rossweisse', 'Rossweisse es una joven con un largo cabello blanco plateado y ojos azules. Su traje normalmente es el set de armadura de Valquiria, que consiste en un pectoral blanco con detalles en dorado y azul claro y manoplas sin dedos a juego, botas, protectores de cadera y clips para el cabello en forma de alas. Ella también lleva un maillot negro debajo de su pectoral, medias negras hasta el muslo y una envoltura de tela azul pálido debajo de los protectores de la cadera, todo lo cual está revestido con cordones rosas.

Para su puesto de profesora en la Academia Kuoh, ella lleva un traje formal con falda.

Rossweisse es una persona muy seria. Ella tiene una tendencia a comprar cosas en las ventas cuando son baratas, lo que hace que Issei la llame "Valquiria de Tienda de 100-Yen". Ella es extremadamente amargada a causa de no tener un novio y se enoja cuando se burlan de eso.', 'https://highschooldxd.fandom.com/es/wiki/Rossweisse', false, null),
  ('dxd-sairaorg', 'high-school-dxd-opi', 'Sairaorg Bael', null, null, null, null, 'Rey del grupo Bael', null, null, null, false, 'Sairaorg is a handsome young man with black hair and violet eyes. He is very tall and has a muscular build due to the extreme training he has done. Issei notes that his face resembles that of his cousins Rias and Sirzechs. His height is [194 cm] and body weight is [135 kg].

Sairaorg has a noble and calm personality and greatly respects his opponents. He also likes to fight strong people, to the point that Rias Gremory, his own cousin, called him a battle maniac. He is shown to be a kind-hearted and compassionate person and has a very straightforward personality. He even shows unconditional kindness to his estranged half brother. Due to suffering discrimination from his traditionalist family, Sairaorg has become extremely open minded. Unlike his father and most of the Bael clan, he does not look down on other Devils based on blood purity and status, as reflected in his chosen peerage.', 'https://highschooldxd.fandom.com/wiki/Sairaorg%20Bael', 'Sairaorg is a handsome young man with black hair and violet eyes. He is very tall and has a muscular build due to the extreme training he has done. Issei notes that his face resembles that of his cousins Rias and Sirzechs. His height is [194 cm] and body weight is [135 kg].

Sairaorg has a noble and calm personality and greatly respects his opponents. He also likes to fight strong people, to the point that Rias Gremory, his own cousin, called him a battle maniac. He is shown to be a kind-hearted and compassionate person and has a very straightforward personality. He even shows unconditional kindness to his estranged half brother. Due to suffering discrimination from his traditionalist family, Sairaorg has become extremely open minded. Unlike his father and most of the Bael clan, he does not look down on other Devils based on blood purity and status, as reflected in his chosen peerage.', 'https://highschooldxd.fandom.com/wiki/Sairaorg%20Bael', 'Sairaorg es un hermoso joven de pelo negro y ojos violetas. Él es muy alto y tiene un cuerpo muscular debido al entrenamiento extremo que ha realizado trae un keikogi color negro y unos zapatos clásicos y un cinturón gris que usa para cerrar su chaqueta ya que usa la ropa debido a que es maestro en artes marciales

Sairaorg tiene una personalidad noble y respeta a sus oponentes. Le gusta pelear con personas fuertes, sobre todo con Issei. Ha demostrado ser una persona buena y muy honesta.', 'https://highschooldxd.fandom.com/es/wiki/Sairaorg%20Bael', false, null),
  ('dxd-serafall', 'high-school-dxd-opi', 'Serafall Leviathan', null, null, null, null, 'Una de los cuatro Maous · hermana de Sona', null, null, null, false, 'Serafall is a beautiful girl, looking in her late teens with black hair tied into twin tails and blue eyes (Pink in seasons 2-3). She also has a child-like body (albeit with large breasts). Her body measurements are B85-W56-H80 cm; her height is 160 cm, and her body weight is 48 kg.

Due to her hobby and interest in magical girls, she occasionally dresses in magical girl''s clothing (from Magical Girl Milky Spiral Seven, the same outfit Mil-tan wears), magic wand and all, prompting Issei to call her the nickname "Satan Girl" ( , Maō Shōjo).', 'https://highschooldxd.fandom.com/wiki/Serafall%20Leviathan', 'Serafall is a beautiful girl, looking in her late teens with black hair tied into twin tails and blue eyes (Pink in seasons 2-3). She also has a child-like body (albeit with large breasts). Her body measurements are B85-W56-H80 cm; her height is 160 cm, and her body weight is 48 kg.

Due to her hobby and interest in magical girls, she occasionally dresses in magical girl''s clothing (from Magical Girl Milky Spiral Seven, the same outfit Mil-tan wears), magic wand and all, prompting Issei to call her the nickname "Satan Girl" ( , Maō Shōjo).', 'https://highschooldxd.fandom.com/wiki/Serafall%20Leviathan', 'Serafall es una mujer hermosa con el pelo largo y negro atado en dos colas a cada lado usando dos listones de color fucsia y sus ojos son de tono purpura. Ella tiene un cuerpo como el de una niña (aunque con grandes pechos), generalmente se viste con ropa de chica mágica (de Magical Girl Láctea Espiral Siete, el mismo traje que Mil-tan viste), llevando de accesorio una varita mágica con forma de estrella, lo que provoca que Issei le de el apodo "Niña Satanás".

A diferencia de su hermana menor Sona, Serafall tiene una personalidad un tanto infantil, que se evidencia cuando llama a su hermana "Sona-chan" o "So-tan" y Sirzechs "Sirzechs-chan". Agregando a su personalidad infantil es el hecho que la mayor parte de su frases terminan con una estrella.', 'https://highschooldxd.fandom.com/es/wiki/Serafall%20Leviat%C3%A1n', false, null),
  ('dxd-sirzechs', 'high-school-dxd-opi', 'Sirzechs Lucifer', null, null, null, null, 'Maou Lucifer · hermano de Rias', null, null, null, false, 'Sirzechs is a handsome man who seems to be in his early 20''s. He has shoulder length crimson hair and blue eyes (blue-green in the anime season 1-3) inherited from his father, Zeoticus, similar to Rias. In fact, Issei has described him as the male version of Rias.

In his true form, Sirzechs takes the form of the Destruction in the shape of a human with crimson aura.

As a Gremory, Sirzechs is shown to be very kind and caring towards others, preferring to have things sorted out through talking instead of fighting. He also has a very laid-back personality, preferring to do things at his own pace and causing his wife to punish him for it. Humorously, when he''s up to his usual antics, the mere mention of his wife''s name is enough to make him apologize immediately. However, Sirzechs does have a serious side, which he has only revealed twice: during his fight against Creuserey Asmodeus and his confrontation with Hades.', 'https://highschooldxd.fandom.com/wiki/Sirzechs%20Lucifer', 'Sirzechs is a handsome man who seems to be in his early 20''s. He has shoulder length crimson hair and blue eyes (blue-green in the anime season 1-3) inherited from his father, Zeoticus, similar to Rias. In fact, Issei has described him as the male version of Rias.

In his true form, Sirzechs takes the form of the Destruction in the shape of a human with crimson aura.

As a Gremory, Sirzechs is shown to be very kind and caring towards others, preferring to have things sorted out through talking instead of fighting. He also has a very laid-back personality, preferring to do things at his own pace and causing his wife to punish him for it. Humorously, when he''s up to his usual antics, the mere mention of his wife''s name is enough to make him apologize immediately. However, Sirzechs does have a serious side, which he has only revealed twice: during his fight against Creuserey Asmodeus and his confrontation with Hades.', 'https://highschooldxd.fandom.com/wiki/Sirzechs%20Lucifer', 'Es de aspecto bien parecido, tiene el cabello largo color Rojo carmesí, lleva puesta una túnica violeta y gris con bordes y decoraciones dorados, y por debajo un traje blanco y gris con bordes y cinturón violetas.

Es una persona muy tranquila, educada e Inteligente aunque también le gusta tomar acciones divertidas. Aunque es muy celoso ya que cuando Millicas prefirió a Oppai Dragon en vez del Satan Rojo y vio que se llevaba bien con Issei, retó a una batalla a Issei para ver quien era mejor, por suerte no se enteró lo de Issei y Grayfia en el Onsen, de lo contrario, habría matado a Issei. También es un siscon dejando siempre a Rías en situaciones vergonzosas. Tiende a apresurar mucho varías cosas, como el dar por echo demasiado deprisa que Issei estaba por Rías y hacer que se comprometan antes de tiempo.', 'https://highschooldxd.fandom.com/es/wiki/Sirzechs%20Lucifer', false, null),
  ('dxd-sona', 'high-school-dxd-opi', 'Sona Sitri', null, null, null, null, 'Rey del grupo Sitri · presidenta del consejo estudiantil', null, null, null, false, 'Sona is a bespectacled young woman with a slim figure, black hair styled in a short bob cut, and violet eyes. Her body measurements are [B77-W57-H83 cm] [B30-W22-H33 in]; her height is 166 cm (5 feet 5 inches) and her body weight is [51 kg].

She is usually seen dressed in the Kuoh Academy girls'' school uniform.

Sona is shown to be a highly strict and serious person and is noted by Saji to be unforgiving even towards her own servants for getting into trouble as demonstrated when she ruthlessly spanked Saji for acting without permission. Whether it is a matter of the Student Council or the Sitri Clan, she does not take anything lightly.', 'https://highschooldxd.fandom.com/wiki/Sona%20Sitri', 'Sona is a bespectacled young woman with a slim figure, black hair styled in a short bob cut, and violet eyes. Her body measurements are [B77-W57-H83 cm] [B30-W22-H33 in]; her height is 166 cm (5 feet 5 inches) and her body weight is [51 kg].

She is usually seen dressed in the Kuoh Academy girls'' school uniform.

Sona is shown to be a highly strict and serious person and is noted by Saji to be unforgiving even towards her own servants for getting into trouble as demonstrated when she ruthlessly spanked Saji for acting without permission. Whether it is a matter of the Student Council or the Sitri Clan, she does not take anything lightly.', 'https://highschooldxd.fandom.com/wiki/Sona%20Sitri', 'Sona es una joven, aparentemente de la misma edad de Rias, de cabello negro y corto, y de ojos Violetas. Ella lleva un par de gafas de color rojo y el uniforma escolar distintivo de las chicas de la Academia Kuoh.

Es de carácter Tranquila y Fuerte a la igual de ser Estricta y muy Inteligente. Le gusta el orden como le ha caracterizado con sus sirvientes.

Sin embargo, le gusta estar en un ambiente tranquilo y le gusta el compañerismo (cuando se asocia con Rias Gremory para enfrentarse a los peligros que acechan a la academia). También es muy competitiva con Rias. 

Su sueño es poder crear una escuela donde se enseñe a todos los demonios sin importar su Clase o procedencia sobre los Rating Games. Por este motivo acude a clases en el mundo humano para analizar su estructura y tomarla como ejemplo.', 'https://highschooldxd.fandom.com/es/wiki/Sona%20Sitri', false, null),
  ('dxd-tsubaki', 'high-school-dxd-opi', 'Tsubaki Shinra', null, null, null, null, 'Reina del grupo Sitri', null, null, null, false, 'Tsubaki is a young bespectacled woman with long straight black hair that extends all the way down to her knees, with split bangs and heterochromic eyes, with a violet left eye and a light brown right eye (both light brown in the anime).

In addition to wearing the Kuoh Academy girls'' school uniform, she also wears blue, semi-rimmed glasses with square lenses.

Like Sona, Tsubaki has a serious personality and is rarely seen smiling. She also cares deeply for her teammates and is very loyal to Sona. However, ever since her fight with Yuuto Kiba, she began falling in love with him, which causes her to be very shy and flustered when around him to the point where she loses her usual calm demeanor. She is noted to like younger boys who would make her serious, making Yuuto a match in a sense. She is shown to be quite sensitive with regards to her feelings for Kiba and his friendship with Issei, as seen when she begged Ravel to stop reading out the manga based on Issei and Kiba.', 'https://highschooldxd.fandom.com/wiki/Tsubaki%20Shinra', 'Tsubaki is a young bespectacled woman with long straight black hair that extends all the way down to her knees, with split bangs and heterochromic eyes, with a violet left eye and a light brown right eye (both light brown in the anime).

In addition to wearing the Kuoh Academy girls'' school uniform, she also wears blue, semi-rimmed glasses with square lenses.

Like Sona, Tsubaki has a serious personality and is rarely seen smiling. She also cares deeply for her teammates and is very loyal to Sona. However, ever since her fight with Yuuto Kiba, she began falling in love with him, which causes her to be very shy and flustered when around him to the point where she loses her usual calm demeanor. She is noted to like younger boys who would make her serious, making Yuuto a match in a sense. She is shown to be quite sensitive with regards to her feelings for Kiba and his friendship with Issei, as seen when she begged Ravel to stop reading out the manga based on Issei and Kiba.', 'https://highschooldxd.fandom.com/wiki/Tsubaki%20Shinra', 'Tsubaki es una mujer de 1,70 cm. de altura con el pelo negro hasta más de la mitad de la espalda. Tiene un flequillo abierto heterocrómico y ojos castaño claro. Utiliza el uniforme de la Academia Kuoh, aun que también lleva gafas azules (semi-montura con cristales cuadrados).

Al igual que su maestro, Tsubaki tiene una personalidad seria y rara vez se la ve sonriendo. También se preocupa profundamente por sus compañeros de equipo.', 'https://highschooldxd.fandom.com/es/wiki/Tsubaki%20Shinra', false, null),
  ('dxd-vali', 'high-school-dxd-opi', 'Vali Lucifer', null, null, null, null, 'Emperador Dragón Blanco · portador del Divine Dividing', null, null, null, false, 'Vali is a handsome young man with light silver hair (dark silver in seasons 2-3) and hazel eyes (light blue in seasons 2-3). He is often seen wearing a dark green V-neck shirt with a high-collared black leather jacket over it. 

He also wears burgundy jeans with a silver chain drooping down over them and black leather chaps with three bands encircling his right calf, and black shoes with black buckles. 

As with other Devils, Vali has black bat-like wings on his back. 

However, unlike other Devils, he possesses a total of eight. Vali also bears a great resemblance to his grandfather, Rizevim Livan Lucifer. 

Vali''s height is 168 cm (5 feet 6 inches) and body weight is [60 kg].

While initially appearing to be a cold, arrogant, overconfident, and ruthless person, Vali has a calm, noble, and caring side to him, as he cares deeply for his comrades.', 'https://highschooldxd.fandom.com/wiki/Vali%20Lucifer', 'Vali is a handsome young man with light silver hair (dark silver in seasons 2-3) and hazel eyes (light blue in seasons 2-3). He is often seen wearing a dark green V-neck shirt with a high-collared black leather jacket over it. 

He also wears burgundy jeans with a silver chain drooping down over them and black leather chaps with three bands encircling his right calf, and black shoes with black buckles. 

As with other Devils, Vali has black bat-like wings on his back. 

However, unlike other Devils, he possesses a total of eight. Vali also bears a great resemblance to his grandfather, Rizevim Livan Lucifer. 

Vali''s height is 168 cm (5 feet 6 inches) and body weight is [60 kg].

While initially appearing to be a cold, arrogant, overconfident, and ruthless person, Vali has a calm, noble, and caring side to him, as he cares deeply for his comrades.', 'https://highschooldxd.fandom.com/wiki/Vali%20Lucifer', 'Vali es un joven apuesto de cabello plateado claro (plateado oscuro en las temporadas 2-3) y ojos color avellana (azul claro en las temporadas 2-3). A menudo se lo ve usando una camisa verde oscuro con cuello en V con una chaqueta de cuero negra de cuello alto sobre ella. El tambien usa jeans de color burdeos con una cadena plateada que cae sobre ellos y chaparreras de cuero negro con tres bandas que rodean su pantorrilla derecha, y zapatos casuales de color negro con hebillas negras. Al igual que otros demonios, Vali tiene alas negras de murciélago en su espalda. Sin embargo, a diferencia de otros demonios, el posee un total de ocho alas. Vali tiene un gran parecido con su abuelo Rizevim Livan Lucifer. La altura de Vali es de 168 cm (5 pies y 6 pulgadas) y su peso corporal es de 60 kg.

A pesar de que presenta una apariencia fría, arrogante, confiada y despiadada, Vali tiene un lado tranquilo y noble, preocupándose tanto de el mismo como de sus camaradas.', 'https://highschooldxd.fandom.com/es/wiki/Vali%20Lucifer', false, null),
  ('dxd-xenovia', 'high-school-dxd-opi', 'Xenovia Quarta', null, null, null, null, 'Caballero del grupo Gremory · portadora de Durandal', null, null, null, false, 'Xenovia is a beautiful young woman with chin-length, blue hair with a dyed green fringe on the right side and brown eyes (dark yellow in the anime, season 2-3). She is also well-endowed with big breasts. Her body measurements are [B87-W58-H88 cm] [B34-W23-H35 in], and her body weight is [56 kg] [123 lbs]. Xenovia''s height 166 cm (5 feet 5 inches).

Her battle attire is her Church battle suit, which consists of a black, skin-tight, short sleeve leotard with pauldrons, matching fingerless gloves that extend to her biceps, and thigh-high boots, all of which are adorned with straps. This attire is worn under a white hooded cloak with gold and blue accents.', 'https://highschooldxd.fandom.com/wiki/Xenovia', 'Xenovia is a beautiful young woman with chin-length, blue hair with a dyed green fringe on the right side and brown eyes (dark yellow in the anime, season 2-3). She is also well-endowed with big breasts. Her body measurements are [B87-W58-H88 cm] [B34-W23-H35 in], and her body weight is [56 kg] [123 lbs]. Xenovia''s height 166 cm (5 feet 5 inches).

Her battle attire is her Church battle suit, which consists of a black, skin-tight, short sleeve leotard with pauldrons, matching fingerless gloves that extend to her biceps, and thigh-high boots, all of which are adorned with straps. This attire is worn under a white hooded cloak with gold and blue accents.', 'https://highschooldxd.fandom.com/wiki/Xenovia', 'Xenovia es una joven de alrededor de la edad de Issei con el cabello corto de color azul claro con un mechón verde a altura de la frente y ojos color café. Su traje principal es el traje de batalla de la Iglesia, que consiste en un leotardo ceñido de manga corta con hombreras, largos guantes sin dedos que se extienden hasta sus bíceps y botas hasta los muslos, todo adornado con cintas. Este equipo se usa debajo de un manto blanco con capucha con detalles en oro y azul. Ella también llevaba un crucifijo alrededor del cuello, que fue retirado más tarde, cuando se convirtió en un demonio. Al ser transferida a la Academia Kuoh e ingresar al Club de Investigación de lo Oculto, ella empieza a usar el uniforme escolar femenino de la Academia Kuoh.

Cuando se introdujo por primera vez a Xenovia, fue retratada con una actitud seria y tranquila, poniendo primero a su misión y habla sólo cuando es necesario, y prefiere no meterse en problemas que no le conciernen.', 'https://highschooldxd.fandom.com/es/wiki/Xenovia%20Quarta', false, null),
  ('dxd-yubelluna', 'high-school-dxd-opi', 'Yubelluna', null, null, null, null, 'Reina del grupo de Riser Phenex', null, null, null, false, 'Yubelluna is a voluptuous woman with long, wavy purple hair that falls all the way down her back and matching eyes. At the front, the right side of her hair falls over her breast and covers her right eye, while the left side falls near the top of her skirt.

Her attire is a dress consisting of a navy blue tunic top with gold accents and a pale blue skirt with open sides, red high-heeled shoes, and overmatched thigh-high stockings with garter belts. The top reveals much of her cleavage and is held with a gold choker with blue and red jewels. Over this, she wears a white overcoat with black and gold accents and matching pauldrons. For accessories, she wears a black headband with a red-orange jewel over her forehead to keep her long hair in place and wields a staff-like scepter in battle.', 'https://highschooldxd.fandom.com/wiki/Yubelluna', 'Yubelluna is a voluptuous woman with long, wavy purple hair that falls all the way down her back and matching eyes. At the front, the right side of her hair falls over her breast and covers her right eye, while the left side falls near the top of her skirt.

Her attire is a dress consisting of a navy blue tunic top with gold accents and a pale blue skirt with open sides, red high-heeled shoes, and overmatched thigh-high stockings with garter belts. The top reveals much of her cleavage and is held with a gold choker with blue and red jewels. Over this, she wears a white overcoat with black and gold accents and matching pauldrons. For accessories, she wears a black headband with a red-orange jewel over her forehead to keep her long hair in place and wields a staff-like scepter in battle.', 'https://highschooldxd.fandom.com/wiki/Yubelluna', 'Yubelluna es una mujer con grandes y notables pechos, con el pelo largo púrpura, ondulado que cae todo el camino por la espalda y los ojos a juego. En la parte delantera, el lado derecho de su cabello cae sobre el pecho y cubre su ojo derecho, mientras que el lado izquierdo cae cerca de la parte superior de la falda. Su traje es un vestido consiste en una tapa azul, una túnica azul marino con detalles en oro y una falda de color azul claro con lados abiertos; incluyendo además zapatos negros. La parte superior muestra gran parte de su escote, y presenta un collar de oro con piedras preciosas de color azul y rojo. Sobre esto, ella lleva un abrigo blanco con detalles en negro y oro y hombreras a juego. Para los accesorios, lleva una diadema negra con una joya de color rojo anaranjado sobre la frente para mantener el pelo largo en el lugar, y ejerce un bastón como cetro en las batallas.', 'https://highschooldxd.fandom.com/es/wiki/Yubelluna', false, null),
  ('dxd-kiba', 'high-school-dxd-opi', 'Yuuto Kiba', null, null, null, null, 'Caballero del grupo Gremory', null, null, null, false, 'thumb|left|160px
Yuuto is a handsome young man with short blond hair, blue eyes (bluish-gray eyes in the anime), and a mole underneath his left eye.

He wears the Kuoh Academy boys'' school uniform, which consists of a black blazer with white accents over a white, long-sleeved dress shirt with a black ribbon on the collar, matching black pants, and brown dress shoes.

Yuuto is, overall, an upbeat person and cares deeply for his comrades. He''s also a very polite and friendly individual, even considering Issei''s initial dislike towards him. As a Knight, he has pride, chivalry, dignity, and honor befitting one, and is shown to enjoy fighting fellow swordsmen like Karlamine.

Initially, he had a deep hatred towards the Holy Swords or their wielders.', 'https://highschooldxd.fandom.com/wiki/Yuuto%20Kiba', 'Yuuto is a handsome young man with short blond hair, blue eyes (bluish-gray eyes in the anime), and a mole underneath his left eye.

He wears the Kuoh Academy boys'' school uniform, which consists of a black blazer with white accents over a white, long-sleeved dress shirt with a black ribbon on the collar, matching black pants, and brown dress shoes.

Yuuto is, overall, an upbeat person and cares deeply for his comrades. He''s also a very polite and friendly individual, even considering Issei''s initial dislike towards him. As a Knight, he has pride, chivalry, dignity, and honor befitting one, and is shown to enjoy fighting fellow swordsmen like Karlamine.

Initially, he had a deep hatred towards the Holy Swords or their wielders.', 'https://highschooldxd.fandom.com/wiki/Yuuto%20Kiba', 'Yūto es un joven con el cabello corto rubio y ojos grises. Al igual que Issei y el resto de los chicos de la Academia Kuoh, lleva el uniforme escolar masculino, que consiste en una chaqueta de color negro con detalles en blanco sobre una camisa manga larga blanca de vestir con un lazo negro en el cuello, pantalones negros y zapatos de vestir cafés.

Yūto es generalmente una persona optimista, respetuoso y se preocupa profundamente por sus compañeros. Él también es una persona muy amable cuando se trata de su forma de ser y su personalidad, incluso teniendo en cuenta la aversión inicial de Issei hacia él.

ÉL le tenía un profundo odio hacia las espadas sagradas hasta el Volumen 3, cuando los miembros del Club de Investigación Oculta y las almas de sus amigos, que eran víctimas del Proyecto espada sagrada, le ayudaron a superarlo.', 'https://highschooldxd.fandom.com/es/wiki/Yuuto%20Kiba', false, null)
on conflict (id) do update
  set game_id = excluded.game_id,
      name = excluded.name,
      image_url = excluded.image_url,
      rarity = excluded.rarity,
      element = excluded.element,
      level_cap = excluded.level_cap,
      description = excluded.description,
      role = excluded.role,
      path = excluded.path,
      signature = excluded.signature,
      is_upcoming = excluded.is_upcoming,
      biography = excluded.biography,
      biography_source = excluded.biography_source,
      biography_en = excluded.biography_en,
      biography_source_en = excluded.biography_source_en,
      biography_es = excluded.biography_es,
      biography_source_es = excluded.biography_source_es,
      biography_es_translated = excluded.biography_es_translated,
      ascension = excluded.ascension;

-- Comprobacion
select count(*) as personajes from public.characters where game_id = 'high-school-dxd-opi';
