-- Ejecutar en Supabase -> SQL Editor -> New query -> Run.
-- Requiere 01_esquema.sql.
--
-- Tier lists oficiales (valoraciones de Prydwen, de 0 = mejor a 5): 380
-- valoraciones. Genshin y Zenless tienen un modo General; Honkai, Memory of
-- Chaos, Pure Fiction y Apocalyptic Shadow. Requiere los personajes (02 a 04).
--
-- Los datos son una copia de la base de datos tal y como estaba el 2026-09-15.
-- Inserta lo que falte y actualiza lo que ya exista, sin borrar nada: los
-- favoritos, tier lists y guias de los usuarios que apuntan a estas filas se
-- conservan. Ojo: si has cambiado algo desde la app despues de esa fecha,
-- ejecutarlo lo devuelve a como estaba en la copia.

insert into public.tier_lists_oficial (
  game_id, mode, character_id, rating, source
)
values
  ('genshin-impact', 'General', 'gi-chevreuse', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-citlali', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-columbina', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-iansan', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-ineffa', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-lauma', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-linnea', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-mavuika', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-mona', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-nefer', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-nicole', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-odette', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-sandrone', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-sucrose', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-yae-miko', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-zibai', 0, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-alyosha', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-bennett', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-cyno', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-durin', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-escoffier', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-fischl', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-flins', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-illuga', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-prune', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-qiqi', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-skirk', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-varka', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-wriothesley', 0.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-aino', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-albedo', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-arlecchino', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-faruzan', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-furina', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-kinich', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-lohen', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-mualani', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-nahida', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-ororon', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-varesa', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-xilonen', 1, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-beidou', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-chiori', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-clorinde', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-diona', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-emilie', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-gaming', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-gorou', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-hu-tao', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-jahoda', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-kazuha', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-klee', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-lyney', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-navia', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-neuvillette', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-nilou', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-shenhe', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-venti', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-xiangling', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-xingqiu', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-yelan', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-zhongli', 1.5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-arataki-itto', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-ayaka', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-charlotte', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-chasca', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-ifa', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-jean', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-kachina', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-kokomi', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-kujou-sara', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-kuki-shinobu', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-lan-yan', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-noelle', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-raiden', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-razor', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-rosaria', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-wanderer', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-xianyun', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-xiao', 2, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-alhaitham', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-baizhu', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-barbara', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-candace', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-chongyun', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-collei', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-dahlia', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-dehya', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-diluc', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-ganyu', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-kaeya', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-kirara', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-layla', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-lynette', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-ningguang', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-sethos', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-thoma', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-yanfei', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-yaoyao', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-yoimiya', 3, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-amber', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-ayato', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-dori', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-eula', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-freminet', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-heizou', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-kaveh', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-keqing', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-lisa', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-mika', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-sayu', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-sigewinne', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-tartaglia', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-tighnari', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-yun-jin', 4, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-aloy', 5, 'prydwen.gg'),
  ('genshin-impact', 'General', 'gi-xinyan', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-archer', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-castorice', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-cyrene', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-firefly', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-huohuo', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-hyacine', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-permanser-terrae', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-rin-tohsaka', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-acheron', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-black-swan', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-fugue', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-gilgamesh', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-hysilens', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-kafka', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-lingsha', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-ruan-mei', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-saber', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-sparkle', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-trazacaminos-hielo', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-trazacaminos-imaginario', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-tribbie', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-anaxa', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-aventurine', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-boothill', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-cerydra', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-cipher', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-fu-xuan', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-gallagher', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-phainon', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-rappa', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-robin', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-silver-wolf', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-sunday', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-welt', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-asta', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-bronya', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-feixiao', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-jade', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-luocha', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-mydei', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-seele', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-the-herta', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-aglaea', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-herta', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-jiaoqiu', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-tingyun', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-argenti', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-bailu', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-himeko', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-jing-yuan', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-lynx', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-topaz', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-blade', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-gepard', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-imbibitor-lunae', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-jingliu', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-moze', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-pela', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-serval', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-yunli', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-arlan', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-clara', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-dan-heng', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-dr-ratio', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-guinaifen', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-hanya', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-hook', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-luka', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-march-7th', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-misha', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-natasha', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-qingque', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-sampo', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-sushang', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-trazacaminos-fisico', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-trazacaminos-fuego', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-xueyi', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-yanqing', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-yukong', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-archer', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-castorice', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-cyrene', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-firefly', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-huohuo', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-hyacine', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-rin-tohsaka', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-acheron', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-black-swan', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-fugue', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-gilgamesh', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-hysilens', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-kafka', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-permanser-terrae', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-ruan-mei', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-saber', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-sparkle', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-trazacaminos-hielo', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-trazacaminos-imaginario', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-tribbie', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-welt', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-anaxa', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-cerydra', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-cipher', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-fu-xuan', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-lingsha', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-phainon', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-silver-wolf', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-sunday', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-aglaea', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-aventurine', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-feixiao', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-gallagher', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-mydei', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-robin', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-the-herta', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-boothill', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-bronya', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-jade', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-luocha', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-rappa', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-seele', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-asta', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-bailu', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-blade', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-herta', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-jiaoqiu', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-jingliu', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-lynx', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-tingyun', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-topaz', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-yunli', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-argenti', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-clara', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-gepard', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-himeko', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-imbibitor-lunae', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-jing-yuan', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-moze', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-pela', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-serval', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-arlan', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-dan-heng', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-dr-ratio', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-guinaifen', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-hanya', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-hook', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-luka', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-march-7th', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-misha', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-natasha', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-qingque', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-sampo', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-sushang', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-trazacaminos-fisico', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-trazacaminos-fuego', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-xueyi', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-yanqing', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-yukong', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-castorice', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-cyrene', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-huohuo', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-hyacine', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-tribbie', 0, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-acheron', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-archer', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-black-swan', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-fu-xuan', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-gilgamesh', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-hysilens', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-kafka', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-permanser-terrae', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-rin-tohsaka', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-saber', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-sparkle', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-trazacaminos-hielo', 0.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-aventurine', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-cipher', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-herta', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-jade', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-lingsha', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-luocha', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-mydei', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-seele', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-sunday', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-the-herta', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-welt', 1, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-anaxa', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-asta', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-cerydra', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-feixiao', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-firefly', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-fugue', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-gallagher', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-himeko', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-robin', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-ruan-mei', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-trazacaminos-imaginario', 1.5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-aglaea', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-argenti', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-bronya', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-phainon', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-rappa', 2, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-bailu', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-jiaoqiu', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-lynx', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-silver-wolf', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-tingyun', 3, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-blade', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-clara', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-gepard', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-jing-yuan', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-jingliu', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-pela', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-serval', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-yunli', 4, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-arlan', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-boothill', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-dan-heng', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-dr-ratio', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-guinaifen', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-hanya', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-hook', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-imbibitor-lunae', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-luka', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-march-7th', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-misha', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-moze', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-natasha', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-qingque', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-sampo', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-sushang', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-topaz', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-trazacaminos-fisico', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-trazacaminos-fuego', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-xueyi', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-yanqing', 5, 'prydwen.gg'),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-yukong', 5, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-burnice', 0.5, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-miyabi', 0.5, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-nicole', 0.5, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-rina', 0.5, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-grace', 1, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-harumasa', 1, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-jane-doe', 1, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-lighter', 1, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-lycaon', 1, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-nekomata', 1, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-piper', 1, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-soldado-11', 1, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-yanagi', 1, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-ellen', 1.5, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-qingyi', 1.5, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-soukaku', 1.5, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-zhu-yuan', 1.5, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-billy', 2, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-caesar', 2, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-corin', 2, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-koleda', 2, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-lucy', 2, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-anby', 3, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-anton', 3, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-ben', 3, 'prydwen.gg'),
  ('zenless-zone-zero', 'General', 'zzz-seth', 3, 'prydwen.gg')
on conflict (game_id, mode, character_id) do update
  set rating = excluded.rating,
      source = excluded.source;

-- Comprobacion
select game_id, mode, count(*) as valoraciones from public.tier_lists_oficial group by game_id, mode order by game_id, mode;
