-- Ejecutar en Supabase -> SQL Editor -> New query -> Run.
-- Requiere 01_esquema.sql (la tabla relic_sets).
--
-- Reliquias y ornamentos planares de Honkai: Star Rail: los 60 conjuntos del juego
-- (32 de reliquias y 28 de ornamentos).
--
-- Fuentes:
--   StarRailRes (github.com/Mar-7th/StarRailRes) -> nombre y efectos en espanol
--     e ingles, e icono.
--   Datos del propio juego (TurnBasedGameData) -> la Caverna de la corrosion
--     donde se consigue cada conjunto de reliquias y la version en que salio.
--     Los ornamentos salen todos de la Extraccion de ornamentos.
--
-- Inserta lo que falte y actualiza lo que ya exista, sin borrar nada.
--
-- Generado el 2026-09-15.

insert into public.relic_sets (
  id, game_id, name, name_en, type, image_url, two_piece, four_piece, how_to_get, version
)
values
  ('hsr-relic-301', 'honkai-star-rail', 'Estación sellaespacios', 'Space Sealing Station', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/301.png', 'El ATQ del portador aumenta en un 12%. Cuando su VEL es igual o superior a 120, el ATQ aumenta en un 12% adicional.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.0'),
  ('hsr-relic-302', 'honkai-star-rail', 'Flota de los eternos', 'Fleet of the Ageless', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/302.png', 'Los PV máx. del portador aumentan en un 12%. Cuando su VEL es igual o superior a 120, el ATQ de todos los aliados aumenta en un 8%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.0'),
  ('hsr-relic-303', 'honkai-star-rail', 'Entidad comercial pangaláctica', 'Pan-Cosmic Commercial Enterprise', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/303.png', 'El acierto de efecto del portador aumenta en un 10% y su ATQ aumenta en una cantidad equivalente al 25% del acierto de efecto actual, hasta un máximo de un 25%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.0'),
  ('hsr-relic-304', 'honkai-star-rail', 'La Belobog de los Arquitectos', 'Belobog of the Architects', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/304.png', 'La DEF del portador aumenta en un 15%. Cuando su acierto de efecto es igual o superior al 50%, la DEF aumenta en un 15% adicional.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.0'),
  ('hsr-relic-305', 'honkai-star-rail', 'Diferenciador celestial', 'Celestial Differentiator', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/305.png', 'El Daño CRIT del portador aumenta en un 16%. Cuando su Daño CRIT es igual o superior al 120%, tras entrar en combate su Prob. CRIT aumenta en un 60% hasta que termine su primer ataque.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.0'),
  ('hsr-relic-306', 'honkai-star-rail', 'Salsotto inerte', 'Inert Salsotto', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/306.png', 'La Prob. CRIT del portador aumenta en un 8%. Cuando su Prob. CRIT es igual o superior al 50%, el daño que infligen su habilidad definitiva y sus ataques adicionales aumenta en un 15%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.0'),
  ('hsr-relic-307', 'honkai-star-rail', 'Talia, paraíso de los forajidos', 'Talia: Kingdom of Banditry', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/307.png', 'El efecto de Ruptura del portador aumenta en un 16%. Cuando su VEL es igual o superior a 145, el efecto especial de Ruptura aumenta en un 20% adicional.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.0'),
  ('hsr-relic-308', 'honkai-star-rail', 'Vonwacq el vivaz', 'Sprightly Vonwacq', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/308.png', 'La recuperación de energía del portador aumenta en un 5%. Cuando su VEL es igual o superior a 120, su acción se adelanta un 40% al entrar en combate.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.0'),
  ('hsr-relic-309', 'honkai-star-rail', 'Arena rutilante', 'Rutilant Arena', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/309.png', 'La Prob. CRIT del portador aumenta en un 8%. Cuando su Prob. CRIT es igual o superior al 70%, el daño que infligen su ATQ básico y su habilidad básica aumenta en un 20%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.2'),
  ('hsr-relic-310', 'honkai-star-rail', 'Quilla rota', 'Broken Keel', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/310.png', 'La RES a efecto del portador aumenta en un 10%. Cuando su RES a efecto es igual o superior al 30%, el Daño CRIT de todos los aliados aumenta en un 10%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.2'),
  ('hsr-relic-311', 'honkai-star-rail', 'Glamoth, frente del firmamento', 'Firmament Frontline: Glamoth', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/311.png', 'El ATQ del portador aumenta en un 12%. Cuando su VEL es igual o superior a 135/160, el daño que inflige aumenta en un 12%/18%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.5'),
  ('hsr-relic-312', 'honkai-star-rail', 'Colonipenal, la tierra de los sueños', 'Penacony, Land of the Dreams', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/312.png', 'La recuperación de energía del portador aumenta en un 5%. Aumenta en un 10% el daño que infligen los demás aliados que sean del mismo tipo que el portador.', null, 'Extracción de ornamentos (Universo Diferenciado)', '1.5'),
  ('hsr-relic-313', 'honkai-star-rail', 'Sigonia, desolación sin dueño', 'Sigonia, the Unclaimed Desolation', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/313.png', 'Aumenta la Prob. CRIT del portador en un 4%. Al eliminar a un enemigo, el Daño CRIT del portador aumenta en un 4%. Se puede acumular hasta 10 veces.', null, 'Extracción de ornamentos (Universo Diferenciado)', '2.1'),
  ('hsr-relic-314', 'honkai-star-rail', 'Izumo gensei y reino divino de Takama', 'Izumo Gensei and Takama Divine Realm', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/314.png', 'Aumenta el ATQ del portador en un 12%. Al entrar en combate, si hay al menos un aliado de la misma Vía que el portador, la Prob. CRIT del portador aumenta en un 12%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '2.1'),
  ('hsr-relic-315', 'honkai-star-rail', 'Duran, dinastía de lobos raudos', 'Duran, Dynasty of Running Wolves', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/315.png', 'Cuando un aliado lanza un ataque adicional, el portador obtiene una acumulación de Mérito, hasta un máximo de 5 acumulaciones. Por cada acumulación, el daño que infligen los ataques adicionales del portador aumenta en un 5%. Cuando se alcanza el máximo de 5 acumulaciones, el Daño CRIT del portador aumenta en un 25%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '2.3'),
  ('hsr-relic-316', 'honkai-star-rail', 'Fragua de la linterna Kalpagni', 'Forge of the Kalpagni Lantern', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/316.png', 'La VEL del portador aumenta en un 6%. Cuando el portador golpea a un enemigo con Debilidad de Fuego, el efecto de Ruptura aumenta en un 40% durante 1 turno.', null, 'Extracción de ornamentos (Universo Diferenciado)', '2.3'),
  ('hsr-relic-317', 'honkai-star-rail', 'Lushaka, sumergido bajo el mar', 'Lushaka, the Sunken Seas', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/317.png', 'La recuperación de energía del portador aumenta en un 5%. Si el portador no es el primer personaje de la formación, aumenta en un 12% el ATQ del primer personaje de la formación.', null, 'Extracción de ornamentos (Universo Diferenciado)', '2.5'),
  ('hsr-relic-318', 'honkai-star-rail', 'Parque de Platanolandia', 'The Wondrous BananAmusement Park', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/318.png', 'El Daño CRIT del portador aumenta en un 16%. Cuando hay una unidad invocada por el portador, el Daño CRIT aumenta en un 32% adicional.', null, 'Extracción de ornamentos (Universo Diferenciado)', '2.5'),
  ('hsr-relic-319', 'honkai-star-rail', 'Osario sereno', 'Bone Collection''s Serene Demesne', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/319.png', 'Los PV máx. del portador aumentan en un 12%. Cuando sus PV máx. son iguales o superiores a 5000, el Daño CRIT del portador y su mnemoduende aumenta en un 28%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '3.1'),
  ('hsr-relic-320', 'honkai-star-rail', 'Árbol gigante en meditación profunda', 'Giant Tree of Rapt Brooding', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/320.png', 'La VEL del portador aumenta en un 6%. Cuando su VEL es igual o superior a 135/180, la curación realizada del portador y su mnemoduende aumenta en un 12%/20%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '3.1'),
  ('hsr-relic-321', 'honkai-star-rail', 'Paraíso de las hadas tejesueños', 'Arcadia of Woven Dreams', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/321.png', 'Cuando en el equipo desplegado en el campo de batalla hay más o menos de 4 aliados, por cada aliado de más/menos que haya, el daño que infligen el portador y su mnemoduende aumenta en un 9%/12%. Se puede acumular hasta 4/3 veces.', null, 'Extracción de ornamentos (Universo Diferenciado)', '3.4'),
  ('hsr-relic-322', 'honkai-star-rail', 'Litoral embriagado', 'Revelry by the Sea', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/322.png', 'El ATQ del portador aumenta en un 12%. Cuando el ATQ del portador es igual o superior a 2400/3600, el Daño con el tiempo que inflige aumenta en un 12%/24% adicional.', null, 'Extracción de ornamentos (Universo Diferenciado)', '3.4'),
  ('hsr-relic-323', 'honkai-star-rail', 'Amphoreus, la tierra eterna', 'Amphoreus, The Eternal Land', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/323.png', 'La Prob. CRIT del portador aumenta en un 8%. Cuando el mnemoduende del portador está en la batalla, la VEL de todos los aliados aumenta en un 8%. Este efecto no se puede acumular.', null, 'Extracción de ornamentos (Universo Diferenciado)', '3.7'),
  ('hsr-relic-324', 'honkai-star-rail', 'Tengoku@sala de chat', 'Tengoku@Livestream', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/324.png', 'El Daño CRIT del portador aumenta en un 16%. Si el portador consume 3 o más pts. de habilidad básica en el mismo turno, su Daño CRIT aumenta en un 32% adicional durante 3 turnos.', null, 'Extracción de ornamentos (Universo Diferenciado)', '3.7'),
  ('hsr-relic-325', 'honkai-star-rail', 'Etapa cero de Punklorde', 'Punklorde Stage Zero', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/325.png', 'La Exultación del portador aumenta en un 8%. Cuando la Exultación alcanza 40%/80% por primera vez en una batalla, el Daño CRIT del portador aumenta en un 20%/32%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '4.1'),
  ('hsr-relic-326', 'honkai-star-rail', 'Ciudad de las mil estrellas', 'City of Converging Stars', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/326.png', 'Cuando el portador lanza un ataque adicional, el ATQ aumenta en un 24% durante 2 turnos. Cuando se elimina a un enemigo, el Daño CRIT de todos los aliados aumenta en un 12% durante la batalla actual. Este efecto no se puede acumular.', null, 'Extracción de ornamentos (Universo Diferenciado)', '4.1'),
  ('hsr-relic-327', 'honkai-star-rail', 'Punto de partida de la estrella caída', 'Fallen Star Anchorage', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/327.png', 'La Prob. CRIT del portador aumenta en un 8%. Al entrar en combate, si tanto el portador como otro compañero de equipo son personajes de Camarada trazacaminos, el Daño CRIT del portador aumenta en un 32%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '4.4'),
  ('hsr-relic-328', 'honkai-star-rail', 'Instituto de Ciencias de la Vida Cósmica', 'Cosmic Life Sciences Institute', 'ornamento', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/328.png', 'Al entrar en combate, si la energía máxima del portador es igual o superior a 200 pts., el daño infligido por el portador aumenta en un 0.2% por cada punto que supere este valor, hasta un máximo del 32%.', null, 'Extracción de ornamentos (Universo Diferenciado)', '4.4'),
  ('hsr-relic-101', 'honkai-star-rail', 'Transeúnte de la nube pasajera', 'Passerby of Wandering Cloud', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/101.png', 'Curación realizada +10%.', 'Al entrar en combate, el equipo recupera inmediatamente 1 pt. de habilidad básica.', 'Caverna de la corrosión: Senda de la deriva', '1.0'),
  ('hsr-relic-102', 'honkai-star-rail', 'Pistolera de la espiga silvestre', 'Musketeer of Wild Wheat', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/102.png', 'ATQ +12%.', 'La VEL del portador aumenta en un 6% y el daño de sus ATQ básicos aumenta en un 10%.', 'Caverna de la corrosión: Senda de la deriva', '1.0'),
  ('hsr-relic-103', 'honkai-star-rail', 'Paladina de la Iglesia de la Corte Inmaculada', 'Knight of Purity Palace', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/103.png', 'DEF +15%.', 'El efecto de escudo otorgado por el portador aumenta en un 20%.', 'Caverna de la corrosión: Senda del himno sagrado', '1.0'),
  ('hsr-relic-104', 'honkai-star-rail', 'Cazador del bosque glacial', 'Hunter of Glacial Forest', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/104.png', 'Daño de Hielo +10%.', 'Cuando el portador usa la habilidad definitiva, el Daño CRIT aumenta en un 25% durante 2 turnos.', 'Caverna de la corrosión: Senda del viento gélido', '1.0'),
  ('hsr-relic-105', 'honkai-star-rail', 'Campeona de boxeo callejero', 'Champion of Streetwise Boxing', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/105.png', 'Daño Físico +10%.', 'Cuando el portador ataca o recibe un ataque, su ATQ aumenta en un 5% durante la batalla actual. Puede acumularse hasta 5 veces.', 'Caverna de la corrosión: Senda de los puños rápidos', '1.0'),
  ('hsr-relic-106', 'honkai-star-rail', 'Guardia de la nieve borrascosa', 'Guard of Wuthering Snow', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/106.png', 'Daño recibido -8%.', 'Al comienzo del turno, si el portador tiene un porcentaje de PV igual o inferior al 50%, regenera una cantidad de PV equivalente al 8% de sus PV máx. y recupera 5 pts. de energía.', 'Caverna de la corrosión: Senda de la providencia', '1.0'),
  ('hsr-relic-107', 'honkai-star-rail', 'Forjador de lava', 'Firesmith of Lava-Forging', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/107.png', 'Daño de Fuego +10%.', 'El daño que inflige la habilidad básica del portador aumenta en un 12%. Además, tras usar la habilidad definitiva, el Daño de Fuego que inflija en el siguiente ataque aumenta en un 12%.', 'Caverna de la corrosión: Senda de la conflagración', '1.0'),
  ('hsr-relic-108', 'honkai-star-rail', 'Genio de las estrellas relucientes', 'Genius of Brilliant Stars', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/108.png', 'Daño Cuántico +10%.', 'Cuando el portador inflige daño a un objetivo enemigo, ignora el 10% de su DEF. Si el objetivo tiene Debilidad Cuántica, ignora un 10% adicional de su DEF.', 'Caverna de la corrosión: Senda de la providencia', '1.0'),
  ('hsr-relic-109', 'honkai-star-rail', 'Banda del trueno crepitante', 'Band of Sizzling Thunder', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/109.png', 'Daño de Rayo +10%.', 'Cuando el portador utiliza la habilidad básica, su ATQ aumenta en un 20% durante 1 turno.', 'Caverna de la corrosión: Senda del himno sagrado', '1.0'),
  ('hsr-relic-110', 'honkai-star-rail', 'Águila del crepúsculo', 'Eagle of Twilight Line', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/110.png', 'Daño de Viento +10%.', 'Cuando el portador utiliza la habilidad definitiva, su acción se adelanta un 25%.', 'Caverna de la corrosión: Senda del viento gélido', '1.0'),
  ('hsr-relic-111', 'honkai-star-rail', 'Ladrón del rastro meteórico', 'Thief of Shooting Meteor', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/111.png', 'Efecto de Ruptura +16%.', 'El efecto de Ruptura del portador aumenta en un 16%. Cuando rompe la Debilidad del enemigo, recupera 3 pts. de energía.', 'Caverna de la corrosión: Senda de los puños rápidos', '1.0'),
  ('hsr-relic-112', 'honkai-star-rail', 'Habitante del yermo de los bandidos', 'Wastelander of Banditry Desert', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/112.png', 'Daño Imaginario +10%.', 'Al infligir daño a enemigos afectados por estados negativos, la Prob. CRIT del portador aumenta en un 10%. Si el objetivo está afectado por Prisión, el Daño CRIT aumenta en un 20%.', 'Caverna de la corrosión: Senda de la conflagración', '1.0'),
  ('hsr-relic-113', 'honkai-star-rail', 'Discípula longeva', 'Longevous Disciple', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/113.png', 'PV máx. +12%.', 'Cuando el portador recibe un ataque o un aliado (incluyendo el portador) consume PV del portador, la Prob. CRIT aumenta en un 8% durante 2 turnos. Este efecto se puede acumular hasta 2 veces.', 'Caverna de la corrosión: Senda de los elixires', '1.2'),
  ('hsr-relic-114', 'honkai-star-rail', 'Mensajero del espacio hackeado', 'Messenger Traversing Hackerspace', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/114.png', 'VEL +6%.', 'Cuando el portador usa su habilidad definitiva sobre un aliado, la VEL de todos los aliados aumenta en un 12% durante 1 turno. Este efecto no se puede acumular.', 'Caverna de la corrosión: Senda de los elixires', '1.2'),
  ('hsr-relic-115', 'honkai-star-rail', 'Gran duque incinerador', 'The Ashblazing Grand Duke', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/115.png', 'Daño de los ataques adicionales +20%.', 'Cuando el portador lanza un ataque adicional, el ATQ del portador aumenta en un 6% por cada vez que haya infligido daño con el ataque adicional. Se puede acumular hasta 8 veces y dura 3 turnos. Este efecto se disipa la siguiente vez que el portador lance un ataque adicional.', 'Caverna de la corrosión: Senda de la oscuridad', '1.5'),
  ('hsr-relic-116', 'honkai-star-rail', 'Prisionero aislado', 'Prisoner in Deep Confinement', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/116.png', 'ATQ +12%.', 'Por cada estado de Daño con el tiempo que tenga el objetivo, el portador ignora un 6% de su DEF cuando le inflige daño, hasta un máximo de 3 estados de Daño con el tiempo.', 'Caverna de la corrosión: Senda de la oscuridad', '1.5'),
  ('hsr-relic-117', 'honkai-star-rail', 'Buceadora pionera del agua muerta', 'Pioneer Diver of Dead Waters', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/117.png', 'El daño infligido a los enemigos afectados por estados negativos aumenta en un 12%.', 'La Prob. CRIT aumenta en un 4%. El Daño CRIT que el portador inflige a los enemigos que tengan al menos 2/3 estados negativos aumenta en un 8%/12%. Cuando el portador aplica un estado negativo a un enemigo, los efectos mencionados aumentan en un 100% durante 1 turno.', 'Caverna de la corrosión: Senda de los sueños', '2.0'),
  ('hsr-relic-118', 'honkai-star-rail', 'Relojero de maquinaciones oníricas', 'Watchmaker, Master of Dream Machinations', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/118.png', 'Efecto de Ruptura +16%.', 'Cuando el portador usa su habilidad definitiva sobre un aliado, el efecto de Ruptura de todos los aliados aumenta en un 30% durante 2 turnos. Este efecto no se puede acumular.', 'Caverna de la corrosión: Senda de los sueños', '2.0'),
  ('hsr-relic-119', 'honkai-star-rail', 'Caballería de hierro plaguicida', 'Iron Cavalry Against the Scourge', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/119.png', 'Efecto de Ruptura +16%.', 'Cuando el efecto de Ruptura del portador es igual o superior al 150%, al causar Daño de Ruptura al objetivo enemigo, ignora un 10% de su DEF. Cuando el efecto de Ruptura del portador es igual o superior al 250%, el Daño de Ultrarruptura que inflige al enemigo ignora adicionalmente un 15% de su DEF.', 'Caverna de la corrosión: Senda del caballero', '2.3'),
  ('hsr-relic-120', 'honkai-star-rail', 'Intrépida cabalgavientos', 'The Wind-Soaring Valorous', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/120.png', 'ATQ +12%.', 'La Prob. CRIT del portador aumenta en un 6%. Cuando el portador lanza un ataque adicional, el daño que inflige la habilidad definitiva aumenta en un 36% durante 1 turno.', 'Caverna de la corrosión: Senda del caballero', '2.3'),
  ('hsr-relic-121', 'honkai-star-rail', 'Sacerdote del calvario revivido', 'Sacerdos'' Relived Ordeal', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/121.png', 'VEL +6%.', 'Al lanzar la habilidad básica o la habilidad definitiva a un aliado, el Daño CRIT del objetivo de la habilidad aumenta en un 18% durante 2 turnos. Este efecto se puede acumular hasta 2 veces.', 'Caverna de la corrosión: Senda de la incertidumbre', '2.6'),
  ('hsr-relic-122', 'honkai-star-rail', 'Eruditos perdidos en el mar del conocimiento', 'Scholar Lost in Erudition', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/122.png', 'Prob. CRIT +8%.', 'El daño que infligen la habilidad básica y la habilidad definitiva aumenta en un 20%. Tras lanzar la habilidad definitiva, el daño que inflige la siguiente habilidad básica aumenta en un 25% adicional.', 'Caverna de la corrosión: Senda de la incertidumbre', '2.6'),
  ('hsr-relic-123', 'honkai-star-rail', 'Héroe de la epopeya triunfal', 'Hero of Triumphant Song', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/123.png', 'ATQ +12%.', 'Cuando el mnemoduende del portador está en el campo de batalla, la VEL del portador aumenta en un 6%. Cuando el mnemoduende del portador ataca, el Daño CRIT del portador y el mnemoduende aumenta en un 30% durante 2 turnos.', 'Caverna de la corrosión: Senda de la canción', '3.0'),
  ('hsr-relic-124', 'honkai-star-rail', 'Poetisa del colapso elegíaco', 'Poet of Mourning Collapse', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/124.png', 'Daño Cuántico +10%.', 'La VEL del portador se reduce en un 8%. Antes de entrar en combate, si la VEL del portador es inferior a 110/95, su Prob. CRIT aumenta en un 20%/32%. Este efecto también aplica al mnemoduende del portador.', 'Caverna de la corrosión: Senda de la canción', '3.0'),
  ('hsr-relic-125', 'honkai-star-rail', 'Guerrera celestial del sol y el trueno', 'Warrior Goddess of Sun and Thunder', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/125.png', 'VEL +6%.', 'El portador obtiene Lluvia benéfica después de que él o su mnemoduende curen a un aliado que no sea el portador ni su mnemoduende. Puede activarse 1 vez por turno y dura 2 turnos. Cuando el portador tiene Lluvia benéfica, su VEL aumenta en un 6% y el Daño CRIT de todos los aliados aumenta en un 15%. Este efecto no se puede acumular.', 'Caverna de la corrosión: Senda del estruendo', '3.3'),
  ('hsr-relic-126', 'honkai-star-rail', 'Capitán del mar maldito', 'Wavestrider Captain', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/126.png', 'Daño CRIT +16%.', 'Cuando el portador se convierte en el objetivo de la habilidad de otro aliado, obtiene 1 acumulación de Ayuda (hasta 2 como máximo). Si el portador tiene 2 acumulaciones de Ayuda al lanzar la habilidad definitiva, las consume todas y su ATQ aumenta en un 48% durante 1 turno.', 'Caverna de la corrosión: Senda del estruendo', '3.3'),
  ('hsr-relic-127', 'honkai-star-rail', 'Salvado{F#ra}{M#r} que reforja el mundo', 'World-Remaking Deliverer', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/127.png', 'Prob. CRIT +8%.', 'Después de que el portador lance el ATQ básico o la habilidad básica cuando su mnemoduende está en el campo de batalla, los PV máx. del portador y su mnemoduende aumentan en un 24% y el daño que infligen todos los aliados aumenta en un 15%. El efecto dura hasta que el portador lance su siguiente ATQ básico o habilidad básica.', 'Caverna de la corrosión: Senda de la salvación oculta', '3.6'),
  ('hsr-relic-128', 'honkai-star-rail', 'Eremita aislado en las estrellas', 'Self-Enshrouded Recluse', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/128.png', 'Efecto de escudo otorgado +10%.', 'El efecto de escudo otorgado por el portador aumenta en un 12%. Cuando un aliado tiene un escudo otorgado por el portador, su Daño CRIT aumenta en un 15%.', 'Caverna de la corrosión: Senda de la salvación oculta', '3.6'),
  ('hsr-relic-129', 'honkai-star-rail', 'Chica mágica de hazañas gloriosas', 'Ever-Glorious Magical Girl', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/129.png', 'Daño CRIT +16%.', 'Al infligir daño de Exultación, el portador y su mnemoduende ignoran un 10% de la DEF del objetivo. Por cada 5 pts. de Chiste acumulados por los aliados, ignoran un 1% adicional de la DEF del objetivo al infligir Daño de Exultación. Se puede acumular hasta 10 veces.', 'Caverna de la corrosión: Senda de la adivinación', '4.0'),
  ('hsr-relic-130', 'honkai-star-rail', 'Adivino de alcance remoto', 'Diviner of Distant Reach', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/130.png', 'VEL +6%.', 'Antes de entrar en combate, si la VEL del portador es igual o superior a 120/160, la Prob. CRIT del portador aumenta en un 10%/18%. La primera vez que el portador lance una habilidad de Exultación en cada combate, la Exultación de todos los aliados aumenta en un 10%. Este efecto no se puede acumular.', 'Caverna de la corrosión: Senda de la adivinación', '4.0'),
  ('hsr-relic-131', 'honkai-star-rail', 'Piloto estelar como Yoveo', 'As Navigator Isee Sees It', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/131.png', 'ATQ +12%.', 'Cuando el portador entra en combate/lanza la habilidad básica, el daño que infligen su habilidad básica y su habilidad definitiva aumenta en un 18%. Se puede acumular hasta 3 veces. Al comenzar el turno del portador/después de lanzar la habilidad definitiva, se disipa 1 acumulación de este efecto.', 'Caverna de la corrosión: Senda de la mirada ardiente', '4.3'),
  ('hsr-relic-132', 'honkai-star-rail', 'Gran forja del interrogante divino', 'Divine-Querying Master Smith', 'reliquia', 'https://raw.githubusercontent.com/Mar-7th/StarRailRes/master/icon/relic/132.png', 'PV máx. +12%.', 'El Daño CRIT que el portador inflige a los enemigos con reducción de DEF aumenta en un 28%. Cuando el portador aplica reducción de DEF a un enemigo, todos los aliados obtienen Ignición durante 2 turnos. Este efecto no se puede acumular. El daño que infligen los aliados con Ignición aumenta en un 15%. Este efecto se puede volver a activar después de que el portador lance un ataque.', 'Caverna de la corrosión: Senda de la mirada ardiente', '4.3')
on conflict (id) do update
  set game_id = excluded.game_id,
      name = excluded.name,
      name_en = excluded.name_en,
      type = excluded.type,
      image_url = excluded.image_url,
      two_piece = excluded.two_piece,
      four_piece = excluded.four_piece,
      how_to_get = excluded.how_to_get,
      version = excluded.version,
      updated_at = now();

-- Comprobacion
select type, count(*) as conjuntos, count(image_url) as con_icono
from public.relic_sets
where game_id = 'honkai-star-rail'
group by type;
