-- Ejecutar en Supabase -> SQL Editor -> New query -> Run.
-- Requiere 01_esquema.sql (la tabla meta_teams) y 05_personajes_aniimo.sql.
--
-- Los 12 equipos meta de Aniimo, uno o dos por elemento, con los cuatro
-- huecos etiquetados por rol (DPS, Ruptura, Apoyo, Curacion y Regeneracion),
-- las alternativas de cada hueco y por que funciona cada equipo.
--
-- Fuente: la guia de equipos de Game8 (game8.co/games/Aniimo/archives/622739),
-- consultada el 2026-09-24. El texto en espanol es una traduccion de esa guia.
--
-- Miembros que aun no tienen ficha en la wiki oficial y por tanto no enlazan:
-- Somniwing.
--
-- Inserta lo que falte y actualiza lo que ya exista, sin borrar nada.

insert into public.meta_teams (
  id, game_id, name_es, name_en, element, style, slots, why_es, why_en, source, sort_order
)
values
  ('aniimo-equipo-ranged-dark-team', 'aniimo', 'Oscuridad a distancia', 'Ranged Dark Team', 'Oscuridad', 'A distancia', '[{"rol":"DPS","opciones":[{"nombre":"Stellarys","id":"aniimo-006"}]},{"rol":"Ruptura","opciones":[{"nombre":"Rookey","id":"aniimo-063"}]},{"rol":"Apoyo","opciones":[{"nombre":"Fragrancier","id":"aniimo-039"}]},{"rol":"Regeneración","opciones":[{"nombre":"Hexxin","id":"aniimo-021"}]}]'::jsonb, 'Rookey se encarga de la ruptura, mientras Fragrancier baja la resistencia a Oscuridad de los enemigos y de paso cura al equipo. Hexxin aplica la maldición, que da EP al equipo cada vez que alguien pega un ataque básico de Oscuridad. Stellarys pone el daño con sus habilidades y ataques básicos, y como su clon copia todo lo que hace, aprovecha el doble las mejoras de Fragrancier y Hexxin.', 'Rookey will deal break damage to enemies, while Fragrancier lowers dark resistance for the enemies and provides healing for the party. Hexxin, on the other hand, applies a Curse debuff that grants EP to the party when using a Dark basic attack. Stellarys will deal dark damage through its skills and basic attacks. Since Stellarys'' clone copies its basic attacks and skills, it can take advantage of the buffs that Fragrancier and Hexxin provide.', 'game8.co', 0),
  ('aniimo-equipo-melee-dark-team', 'aniimo', 'Oscuridad cuerpo a cuerpo', 'Melee Dark Team', 'Oscuridad', 'Cuerpo a cuerpo', '[{"rol":"DPS","opciones":[{"nombre":"Pawney","id":"aniimo-062"},{"nombre":"Ignitis","id":"aniimo-041"}]},{"rol":"Ruptura","opciones":[{"nombre":"Rookey","id":"aniimo-063"}]},{"rol":"Apoyo","opciones":[{"nombre":"Fragrancier","id":"aniimo-039"}]},{"rol":"Regeneración","opciones":[{"nombre":"Hexxin","id":"aniimo-021"}]}]'::jsonb, 'Si prefieres un DPS a melé, Pawney e Ignitis son la mejor opción: pegan básicos a menudo, que es justo lo que activa las mejoras de Fragrancier y Hexxin, y además tienen habilidades que hacen mucho daño. Pawney brilla contra enemigos ya rotos e Ignitis se encarga de rematar a los que están a poca vida.', 'If you prefer a melee DPS for our dark team, then Pawney and Ignitis are your best bets. These two aniimo use their basic attacks often enough to take advantage of Fragrancier and Hexxin''s buffs, while also having access to powerful skills that can deal serious damage to enemies. Pawney excels in dealing damage to Broken enemies, while Ignitis focuses on finishing off low-HP enemies.', 'game8.co', 1),
  ('aniimo-equipo-best-light-team', 'aniimo', 'Equipo de Sagrado', 'Best Light Team', 'Sagrado', null, '[{"rol":"DPS","opciones":[{"nombre":"Lunara","id":"aniimo-99996"},{"nombre":"Helion","id":"aniimo-99998"}]},{"rol":"Ruptura","opciones":[{"nombre":"Rookey","id":"aniimo-063"}]},{"rol":"Curación","opciones":[{"nombre":"Prismana Glacy","id":"aniimo-015"},{"nombre":"Turbo","id":"aniimo-018"}]},{"rol":"Regeneración","opciones":[{"nombre":"Somniwing","id":null}]}]'::jsonb, 'Lunara y Helion son las mejores criaturas de Sagrado: tienen habilidades de varios roles, así que sirven tanto si al equipo le falta EP como si le falta mejora, penalización o ruptura. Si los usas de DPS, acompáñalos con criaturas que valgan para todo: Rookey rompe sin importar el elemento, Glacy Prismana da una mejora de daño a todo el equipo con Disparo de Destello y Somniwing devuelve EP. Si aún no tienes a Glacy Prismana, Turbo hace el apaño: cura menos, pero da escudos. Nimbi también aporta mejoras de daño y de ruptura para todo el equipo.', 'Lunara and Helion are the best Light Aniimo. They have access to various skills in each role, which makes them a versatile Aniimo to bring if your team lacks EP, buffs, debuffs, or break. If you want to use them as a DPS, general-use Aniimos are the best choice. Rookey can inflict break damage regardless of element, Prismana Glacy grants a universal damage buff to the party with Glimmer Shot, and Somniwing provides EP recovery. If you do not have access to Prismana Glacy yet, you can use Turbo instead. Turbo provides less healing in exchange for shields. Nimbi Burst provides universal damage and break buffs.', 'game8.co', 2),
  ('aniimo-equipo-best-fire-team', 'aniimo', 'Equipo de Fuego', 'Best Fire Team', 'Fuego', null, '[{"rol":"DPS","opciones":[{"nombre":"Infergon","id":"aniimo-067"}]},{"rol":"Ruptura","opciones":[{"nombre":"Magmarex","id":"aniimo-072"},{"nombre":"Inferlupa","id":"aniimo-004"}]},{"rol":"Curación","opciones":[{"nombre":"Prismana Glacy","id":"aniimo-015"}]},{"rol":"Regeneración","opciones":[{"nombre":"Flamerion","id":"aniimo-027"}]}]'::jsonb, 'Magmarex va aplicando la penalización de Fuego con su pasiva y con sus habilidades. Flamerion entra cuando ya hay diez o más acumulaciones para devolver EP al equipo y seguir apilando. Infergon aprovecha todo ese EP y esas acumulaciones para consumirlas de golpe con su habilidad y soltar varios pelotazos de Fuego seguidos. Como alternativa puedes poner a Inferlupa en el hueco de ruptura: cuesta más mantener la penalización, pero rompe mucho mejor.', 'Magmarex applies Fire Debuff to enemies with both its passive and fire skills. Flamerion comes into the fight after inflicting 10 or more Fire Debuffs to restore EP for the party and inflict more stacks of it. Infergon takes advantage of all the EP gained and the Fire Debuff to consume it with its skill to deal multiple high Fire damage quickly to enemies. Alternatively, you can also use Inferlupa as an alternative Break aniimo. While Fire Debuff management will become more difficult, Inferlupa''s ability to improve the Break efficiency of attacks can make up for it.', 'game8.co', 3),
  ('aniimo-equipo-best-ice-team', 'aniimo', 'Equipo de Hielo', 'Best Ice Team', 'Hielo', null, '[{"rol":"DPS","opciones":[{"nombre":"Glynsera","id":"aniimo-044"}]},{"rol":"Ruptura","opciones":[{"nombre":"Geoclaw","id":"aniimo-025"}]},{"rol":"Curación","opciones":[{"nombre":"Prismana Glacy","id":"aniimo-015"}]},{"rol":"Regeneración","opciones":[{"nombre":"Somniwing","id":null}]}]'::jsonb, 'Glynsera y Geoclaw son las que mejor aplican la penalización de Hielo, que sube su propio daño y mejora sus habilidades. Geoclaw pone la mayoría de las acumulaciones y además destroza la barra de ruptura. Glynsera se las come para soltar un golpe de Hielo enorme con más probabilidad de crítico. Glacy Prismana cura y sube el daño del equipo con Disparo de Destello, y Somniwing está para que todos recuperen EP y puedan lanzar habilidades más a menudo.', 'Both Glynsera and Geoclaw have the best access to Ice Debuff to improve the damage and enhance the effects of their Ice skills. Geoclaw applies most of the Ice Debuffs while heavily reducing the break gauge of the enemy. Glynsera consumes the Ice Debuffs to deal high Ice damage to the enemy with increased critical chance. Prismana Glacy has access to a healing skill and Glimmer Shot to enhance the damage of the party. Somniwing''s role in this party is to grant EP recovery buffs to help the team cast skills more often.', 'game8.co', 4),
  ('aniimo-equipo-best-wind-team', 'aniimo', 'Equipo de Viento', 'Best Wind Team', 'Viento', null, '[{"rol":"DPS","opciones":[{"nombre":"Cornet","id":"aniimo-009"}]},{"rol":"Ruptura","opciones":[{"nombre":"Tubster","id":"aniimo-010"}]},{"rol":"Apoyo","opciones":[{"nombre":"Tromber","id":"aniimo-008"}]},{"rol":"Apoyo","opciones":[{"nombre":"Chirpi","id":"aniimo-007"},{"nombre":"Eklue","id":"aniimo-032"}]}]'::jsonb, 'Viento es un caso raro: el equipo te lo da la propia familia de criaturas. La idea es juntar las tres mejoras de movimiento de Chirpi, Tromber y Tubster para desbloquear una mejora potente que cura, sube el daño crítico y baja el gasto de aguante. Cornet la aprovecha para volar y soltar una ráfaga de golpes de Viento. Si has hecho contrato con Tromber, cambia a Chirpi por Eklue: así el equipo gana más mejoras de daño de Viento y además baja la resistencia a Viento del enemigo.', 'Wind is in a special place where the team is already predetermined by the same family of aniimo. The goal is to gain all three movement-series buffs from Chirpi, Tromber, and Tubster to obtain a powerful buff that grants healing, critical damage, and stamina cost reduction. This buff will be used by Cornet to fly and deal high multi-hit Wind damage to the enemy. If you formed a contract with Tromber, swapping out Chirpi for Eklue is the best option. It allows the team to gain more wind damage buffs as well as inflict reduced wind resistance on the enemy to further increase the damage output of the team.', 'game8.co', 5),
  ('aniimo-equipo-best-water-team', 'aniimo', 'Equipo de Agua', 'Best Water Team', 'Agua', null, '[{"rol":"DPS","opciones":[{"nombre":"Sherro","id":"aniimo-055"}]},{"rol":"Ruptura","opciones":[{"nombre":"Panpanta","id":"aniimo-052"}]},{"rol":"Curación","opciones":[{"nombre":"Prismana Glacy","id":"aniimo-015"}]},{"rol":"Regeneración","opciones":[{"nombre":"Erlath","id":"aniimo-081"}]}]'::jsonb, 'Panpanta y Erlath crean charcos de agua que Sherro usa para potenciar sus habilidades, así que con Sherro conviene pelear siempre cerca de un charco. Panpanta se centra en romper, y Erlath devuelve EP al equipo cada vez que alguien lanza una habilidad de Agua. Glacy Prismana pone la curación y la mejora de daño con Disparo de Destello.', 'Panpanta and Erlath create water puddles for Sherro to use and enhance its skills to deal more Water damage to the enemies. Always stay near a water puddle when using Sherro''s skills. Panpanta focuses on breaking enemies, and Erlath provides EP recovery for the party for every water skill each Aniimo casts. Prismana Glacy provides healing and a universal damage buff with its Glimmer Shot.', 'game8.co', 6),
  ('aniimo-equipo-melee-dps-lightning-team', 'aniimo', 'Eléctrico cuerpo a cuerpo', 'Melee DPS Lightning Team', 'Eléctrico', 'Cuerpo a cuerpo', '[{"rol":"DPS","opciones":[{"nombre":"Fulmintis","id":"aniimo-10003"}]},{"rol":"Ruptura","opciones":[{"nombre":"Blazen","id":"aniimo-046"}]},{"rol":"Apoyo","opciones":[{"nombre":"Luminelle","id":"aniimo-079"}]},{"rol":"Regeneración","opciones":[{"nombre":"Besauce","id":"aniimo-082"}]}]'::jsonb, 'Fulmintis necesita el EP casi lleno y al enemigo quieto para soltar toda su ráfaga eléctrica con Tormenta de Filos. La preparación empieza con Blazen, que inmoviliza al enemigo rompiéndolo a base de Destello Eléctrico e Impacto Electrizado. Justo antes de que entre Fulmintis, Luminelle sube el daño eléctrico del equipo con Sobrecarga y Autodestrucción. Besauce te devuelve casi todo el EP con Géiser Cargado y baja la resistencia a Eléctrico con su Danza Frenética.', 'Fulmintis requires almost full EP and a stationary enemy to deal high multi-hit lightning damage when using Lightning Blade Storm. The setup starts with Blazen immobilizing the enemy by breaking them with the Lightning Flash + Electrified Impact spam combo. Before Fulmintis deals damage when the enemy breaks, Luminelle can grant the party lightning damage with Arc Surge and Self-Destruction. Besauce restores your EP almost back to full when using Charged Geyser and can reduce the lightning resistance of the enemies with Electric Dance Frenzy.', 'game8.co', 7),
  ('aniimo-equipo-ranged-dps-lightning-team', 'aniimo', 'Eléctrico a distancia', 'Ranged DPS Lightning Team', 'Eléctrico', 'A distancia', '[{"rol":"DPS","opciones":[{"nombre":"Fenmane","id":"aniimo-060"}]},{"rol":"Ruptura","opciones":[{"nombre":"Blazen","id":"aniimo-046"}]},{"rol":"Apoyo","opciones":[{"nombre":"Luminelle","id":"aniimo-079"}]},{"rol":"Regeneración","opciones":[{"nombre":"Besauce","id":"aniimo-082"}]}]'::jsonb, 'Si prefieres pelear a distancia, cambia a Fulmintis por Fenmane. Blazen sigue bajando rápido la barra de ruptura con Destello Eléctrico e Impacto Electrizado, y en cuanto el enemigo se rompe entra Fenmane con las mejoras de Luminelle y Besauce ya puestas, usando Marca de Trueno y Campo de Trueno para ir aplicando la penalización y soltar el daño gordo después.', 'If you prefer a ranged playstyle, you can use Fenmane instead. Blazen can quickly reduce the break gauge of an enemy after using Lightning Flash and Electrified Impact. Once the enemy breaks, Fenmane comes into play with the buffs provided by Luminelle and Besauce. Fenmane uses Thunder Imprint and Thunder Field to periodically apply a lightning debuff and deal high lightning damage later on.', 'game8.co', 8),
  ('aniimo-equipo-melee-dps-grass-team', 'aniimo', 'Hierba cuerpo a cuerpo', 'Melee DPS Grass Team', 'Hierba', 'Cuerpo a cuerpo', '[{"rol":"DPS","opciones":[{"nombre":"Thornblade","id":"aniimo-034"}]},{"rol":"Ruptura","opciones":[{"nombre":"Pomawk","id":"aniimo-037"}]},{"rol":"Apoyo","opciones":[{"nombre":"Melloblum","id":"aniimo-035"}]},{"rol":"Regeneración","opciones":[{"nombre":"Somniwing","id":null}]}]'::jsonb, 'Thornblade es el daño principal: sus habilidades y ataques de Hierba pegan varias veces, y además tiene paradas y contraataques muy buenos. Pomawk mete un montón de daño de ruptura si aciertas con el momento. Melloblum sube sus críticos y su daño, y Somniwing mantiene la recuperación de EP del equipo.', 'Thornblade is the team''s main damage dealer, thanks to its multi-hit grass skills and attacks, as well as having access to powerful parries and counters. Pomawk can quickly inflict high break damage to enemies with its skills if perfectly timed. Melloblum empowers Thornblade''s critical hits and damage output, while Somniwing provides an EP recovery increase for the party.', 'game8.co', 9),
  ('aniimo-equipo-ranged-dps-grass-team', 'aniimo', 'Hierba a distancia', 'Ranged DPS Grass Team', 'Hierba', 'A distancia', '[{"rol":"DPS","opciones":[{"nombre":"Irisal","id":"aniimo-012"}]},{"rol":"Ruptura","opciones":[{"nombre":"Tuckin","id":"aniimo-022"}]},{"rol":"Apoyo","opciones":[{"nombre":"Leafy","id":"aniimo-016"}]},{"rol":"Regeneración","opciones":[{"nombre":"Somniwing","id":null}]}]'::jsonb, 'Irisal hace mucho daño desde lejos con Rayo Concentrado y Tormenta Floral, pero necesita EP constante y césped bajo los pies. Tuckin es una criatura dura que además rompe mucho. Leafy está solo para potenciar a Irisal y generarle ese césped cuando lanza habilidades. Somniwing sube el EP máximo del equipo y lo recupera rápido.', 'Irisal can deal a lot of damage from ranged with Focused Beam and Floral Storm but requires consistent EP recovery and Turf generation. Tuckin is a durable aniimo with high break damage. Leafy is a key team member whose sole purpose is to empower Irisal and generate Turf beneath it when it casts skills. Somniwing increases the team''s max EP and also provides strong EP recovery.', 'game8.co', 10),
  ('aniimo-equipo-best-earth-team', 'aniimo', 'Equipo de Roca', 'Best Earth Team', 'Roca', null, '[{"rol":"DPS","opciones":[{"nombre":"Grizbo","id":"aniimo-069"}]},{"rol":"Ruptura","opciones":[{"nombre":"Minespine","id":"aniimo-074"}]},{"rol":"Apoyo","opciones":[{"nombre":"Bailite","id":"aniimo-076"}]},{"rol":"Regeneración","opciones":[{"nombre":"Somniwing","id":null}]}]'::jsonb, 'Grizbo necesita tiempo para acumular su Furia Desatada y dejar Marcas de Garra en el objetivo. Antes de cambiar a él, asegúrate de que Minespine, Bailite y Somniwing ya han soltado sus habilidades: mejoras, recuperación de EP, curación y ruptura. Con Grizbo, acumula furia, apila Marcas de Garra y consúmelas con el Golpe Crítico para un pelotazo de Roca.', 'Grizbo requires ample time to build up its Raging Rampage and apply Claw Marks to the target. Before switching to Grizbo, make sure that Minespine, Bailite, and Somniwing have used their skills to enhance the party with buffs, EP recovery, healing, and breaks. When using Grizbo, aim to build up rage, stack Claw Marks, then consume it with Critical Hit to deal significantly high Earth damage.', 'game8.co', 11)
on conflict (id) do update
  set name_es = excluded.name_es,
      name_en = excluded.name_en,
      element = excluded.element,
      style = excluded.style,
      slots = excluded.slots,
      why_es = excluded.why_es,
      why_en = excluded.why_en,
      source = excluded.source,
      sort_order = excluded.sort_order,
      updated_at = now();

-- Comprobacion
select element, count(*) as equipos
from public.meta_teams
where game_id = 'aniimo'
group by element
order by element;
