-- Ejecutar en Supabase -> SQL Editor -> New query -> Run.
-- Requiere 01_esquema.sql (la tabla traits) y 05_personajes_aniimo.sql.
--
-- Los 49 rasgos (pasivas) de Aniimo, con las criaturas que lleva cada uno.
--
-- El nombre y la descripcion en espanol salen de la wiki oficial, que es la
-- unica fuente con los numeros. El nombre y el texto en ingles salen de las
-- fichas de MetaBot (metabot.gg/en/aniimo/traits), emparejadas por las
-- criaturas que llevan el rasgo, no por el texto.
--
-- El tipo y las etiquetas se sacan de la propia descripcion: solo se pone una
-- etiqueta si el texto del rasgo la menciona.
--
-- Generado el 2026-09-24.
--
-- Inserta lo que falte y actualiza lo que ya exista, sin borrar nada.

insert into public.traits (
  id, game_id, name_es, name_en, description_es, description_en, icon_url,
  effect_type, tags, creature_ids
)
values
  ('tuning', 'aniimo', 'Afinación', 'Tuning', 'Cada habilidad usada otorga 1 acumulación de [Volumen] y se puede acumular hasta 6 veces. Con 6 acumulaciones de [Volumen], aumenta un 20 % la tasa de crítico durante 15 s.', 'Each skill cast grants 1 stack of [Volume], up to 6 stacks. At 6 stacks of [Volume], increases Crit Rate by [?]% for 15s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1047503_Feature_147102_Icon.png', 'critico', '["acumulacion","critico"]'::jsonb, '["aniimo-036","aniimo-037"]'::jsonb),
  ('earth-affinity', 'aniimo', 'Afinidad terrestre', 'Earth Affinity', 'Mientras estás en el estado [Excavación], puedes usar habilidades e infliges un 20 % de QUIEBRE adicional.', 'While in [Tunneling] state, can cast skills and deal [?]% extra BREAK damage.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1028400_Feature_12812_Icon.png', 'ruptura', '["acumulacion","ruptura"]'::jsonb, '["aniimo-070","aniimo-073","aniimo-074"]'::jsonb),
  ('disco-aniimo', 'aniimo', 'Aniimo disco', 'Disco Aniimo', 'Mientras estés sobre césped, el aumento de daño se incrementa un 30 %. Después de entrar en combate, cada golpe con una habilidad otorga 1 [Poder de danza]. Golpear a varios objetivos no otorga [Poder de danza] adicional. Con 24 de [Poder de danza], la siguiente habilidad no cuesta PE.', 'While on Turf, Damage Amp increases by [?]%. After entering battle, each skill hit grants 1 [Dance Power]. Hitting multiple targets does not grant extra [Dance Power]. At 24, the next skill costs no EP.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1021106_Feature_121102_Icon.png', 'recursos', '["recursos"]'::jsonb, '["aniimo-011","aniimo-012"]'::jsonb),
  ('phantom-opening', 'aniimo', 'Apertura fantasma', 'Phantom Opening', 'Cuando un compañero de equipo inflige daño de ataque básico, obtiene 1 acumulación de [Marca de rosa], hasta un máximo de 10 acumulaciones. Cada acumulación de [Marca de rosa] reduce 3 el costo de PE de melloblum.', 'When a party member deals basic attack damage, gains 1 stack of [Rose Mark], up to 10 stacks. Each stack of [Rose Mark] reduces Melloblum’s EP cost by [?].', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1032402_Feature_132402_Icon.png', 'equipo', '["equipo","recursos","acumulacion","penalizacion"]'::jsonb, '["aniimo-035"]'::jsonb),
  ('appeal', 'aniimo', 'Atracción', 'Appeal', 'Al entrar en combate, si el equipo tiene un miembro de la familia Susuta del sexo opuesto, aumenta la eficiencia de BREAK propia en 30% durante 15 s. Tiempo de reutilización: 20 s.', 'When entering battle, if the party has an opposite-sex Susuta family member, increases own BREAK efficiency by [?]% for 15s. Cooldown: 20s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1017200_Feature_11771_Icon.png', 'familia', '["equipo","familia","cambio","ruptura"]'::jsonb, '["aniimo-049","aniimo-050","aniimo-052"]'::jsonb),
  ('prank', 'aniimo', 'Broma', 'Prank', 'Cada 18 s, la siguiente habilidad aplica [Maldición] a los enemigos alcanzados durante 10 s. Los ataques básicos oscuros restauran 0.4 de EP al golpear a enemigos con [Maldición].', 'Every 18s, the next skill applies [Curse] to enemies hit for 10s. Dark basic attacks restore 50% of EP REGEN FORCE EP when hitting enemies with [Curse].', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1020300_Feature_12074_Icon.png', 'recursos', '["recursos"]'::jsonb, '["aniimo-021"]'::jsonb),
  ('bubble', 'aniimo', 'Burbuja', 'Bubble', 'Cada 12 s, entra en un estado de [Baño]. La siguiente habilidad usada crea un charco.', 'Every 12s, enters Bathing. The next skill cast creates a puddle.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1048100_Feature_148301_Icon.png', 'otro', '[]'::jsonb, '["aniimo-080","aniimo-081"]'::jsonb),
  ('rasgo-companero-de-fuego-confiable', 'aniimo', 'Compañero de fuego confiable', 'Compañero de fuego confiable', 'Mientras esté en la alineación, aumenta el Daño de Atributo Fuego del equipo en 15%. Cuando la Energía supera 40, el efecto aumenta a 20%.', null, 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/6999300_Feature_6999301_Icon.png', 'equipo', '["equipo","recursos","elemento"]'::jsonb, '["aniimo-11001"]'::jsonb),
  ('victory-concerto', 'aniimo', 'Concierto victorioso', 'Victory Concerto', 'Mientras tengas un escudo, eficiencia de QUIEBRE +40 %.Toca Concierto al activar QUIEBRE, lo que reduce un 30 % el costo de vigor de todo el equipo.Cuando tengas 3 ventajas de la serie Movimiento, aumenta un 30 % todos los efectos de Movimiento.', 'While shielded, BREAK efficiency +[?]%.
When triggering BREAK, plays [Concerto], reducing the whole team’s stamina cost by [?]%.
When you have 3 Movement-series buffs, increases all Movement effects by [?]%.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1018700_Feature_118701_Icon.png', 'equipo', '["equipo","sostenimiento","ruptura"]'::jsonb, '["aniimo-010"]'::jsonb),
  ('counting-sheep', 'aniimo', 'Contando ovejas', 'Counting Sheep', 'Cada 10 s, la siguiente habilidad aplica 1 acumulación de [Somnolencia] al objetivo. Al llegar a 3 acumulaciones, el objetivo entra en [Pesadilla] durante 20 s. Los objetivos en [Pesadilla] tienen su Resistencia a la Oscuridad reducida en 27% y no pueden moverse ni lanzar habilidades durante 3 s. Recibir daño elimina el efecto de control.', 'Every [?]s, the next skill applies 1 stack of [Drowsiness] to the target. At 3 stacks, the target enters [Nightmare] for 20s. Targets in [Nightmare] have their Dark Resistance reduced by -35 and cannot move or cast skills for 3s. Taking damage removes the control effect.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1026300_Feature_126301_Icon.png', 'penalizacion', '["acumulacion","penalizacion"]'::jsonb, '["aniimo-019"]'::jsonb),
  ('counter-strike', 'aniimo', 'Contragolpe', 'Counter Strike', 'Tras recibir un ataque, aumenta un 25 % la eficiencia de QUIEBRE durante 10 s.', 'After being attacked, increases BREAK efficiency by [?]% for 10s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1002401_Feature_10281_Icon.png', 'ruptura', '["ruptura"]'::jsonb, '["aniimo-064","aniimo-065","aniimo-066"]'::jsonb),
  ('tidal-heart-119203', 'aniimo', 'Corazón de la marea', 'Tidal Heart (Sheldon)', 'Mientras estés en terreno acuático o tras absorber agua, aumenta un 20 % el daño de agua durante 10 s.', 'While in water terrain or after absorbing water, increases Water damage by [?]% for 10s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1019401_Feature_119403_Icon.png', 'elemento', '["elemento"]'::jsonb, '["aniimo-053","aniimo-054","aniimo-055"]'::jsonb),
  ('flutter-heal', 'aniimo', 'Curación alada', 'Flutter Heal', 'Al entrar en batalla como el Aniimo activo, aumenta un 20 % la curación. Si está fuera del campo de batalla, aparece como un fantasma. Cuando otros Aniimo usan habilidades o definitivas, restaura PS equivalentes a 0.5 % de los PS máximos.', 'When entering battle as the active Aniimo, increases healing by [?]%. If off field, appears as a phantom. When other Aniimo cast skills or Ultimates, restores HP equal to [?]% of max HP.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1023102_Feature_12371_Icon.png', 'sostenimiento', '["sostenimiento"]'::jsonb, '["aniimo-028","aniimo-029"]'::jsonb),
  ('sword-dance', 'aniimo', 'Danza de espadas', 'Sword Dance', 'Cada habilidad usada otorga 1 acumulación de [Danza de espadas], hasta 4 acumulaciones, con una duración de 15 s. Cada ataque básico consume 1 acumulación de [Danza de espadas] para infligir un 180 % de daño adicional.', 'Each skill used grants 1 stack of [Sword Dance], up to 4 stacks, lasting 15s. Each basic attack costs 1 stack of [Sword Dance] to deal 180% extra damage.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1032402_Feature_132402_Icon.png', 'acumulacion', '["acumulacion"]'::jsonb, '["aniimo-033","aniimo-034"]'::jsonb),
  ('electro-stash', 'aniimo', 'Electrorreserva', 'Electro Stash', 'Restaura 4 PE cuando una habilidad asesta un golpe crítico.', 'Restores [?] EP when a skill lands a critical hit.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1003305_Feature_103302_Icon.png', 'recursos', '["recursos","critico"]'::jsonb, '["aniimo-10003"]'::jsonb),
  ('stealth', 'aniimo', 'En modo sigilo', 'Stealth', 'Las habilidades acumulan Impulso al infligir daño y se puede acumular hasta 6 veces. La ganancia de Impulso se duplica al excavar. Con las acumulaciones al máximo, la eficiencia de QUIEBRE aumenta un 30 % durante 20 s.', 'Builds Momentum when dealing damage, up to 6 stacks. Momentum gain is doubled while tunneling. At max stacks, BREAK efficiency increases by [?]% for 20s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1016101_Feature_116101_Icon.png', 'ruptura', '["acumulacion","ruptura","movilidad"]'::jsonb, '["aniimo-023","aniimo-024"]'::jsonb),
  ('radiant-charm', 'aniimo', 'Encanto radiante', 'Radiant Charm', 'Aumenta en 16% el daño de agua para todos los Aniimo del sexo opuesto en el equipo.', 'Increases Water damage by20 for all opposite-sex Aniimo in the party.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1017300_Feature_11731_Icon.png', 'equipo', '["equipo","elemento"]'::jsonb, '["aniimo-051"]'::jsonb),
  ('power-sustain', 'aniimo', 'Energía sostenida', 'Power Sustain', 'Después de asestar 6 golpes críticos, adopta el estado [Sobrecargado] y obtiene de inmediato un escudo de valor equivalente al 5 % de los PS. Todas las habilidades cuestan 12 PE menos, pero no puedes obtener PD. Dura 6 s.', 'After skills land 6 critical hits, becomes [Overcharged], immediately gaining a shield equal to [?]% HP. All skills cost 12 less EP, but UP cannot be gained. Lasts 6s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1022100_Feature_12222_Icon.png', 'sostenimiento', '["recursos","acumulacion","sostenimiento","critico"]'::jsonb, '["aniimo-045","aniimo-046"]'::jsonb),
  ('full-energy', 'aniimo', 'Energía total', 'Full Energy', 'Después de usar 8 ataques básicos en batalla, inferlupa entra en estado de Energía total, lo que mejora su siguiente habilidad. El daño infligido por esa habilidad se considera daño de ataque básico.', 'After using 8 basic attacks in battle, Inferlupa enters Full Energy, enhancing its next skill. Damage dealt by that skill is treated as basic attack damage.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1005503_Feature_105502_Icon.png', 'recursos', '["recursos","acumulacion"]'::jsonb, '["aniimo-004"]'::jsonb),
  ('shrouded-in-mist', 'aniimo', 'Envuelto en niebla', 'Shrouded in Mist', 'Tras usar 4 ataques básicos, entra en el estado [Envuelto en la Niebla]. Al lanzar una habilidad, consume este estado para potenciar sus efectos.', 'Gains 1 stack after being off the field for [?]s or casting a basic attack. At [?] stacks, enters [Shrouded in Mist] state. Casting a skill consumes this state to enhance the skill’s effects.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1026201_Feature_12603_Icon.png', 'acumulacion', '["acumulacion"]'::jsonb, '["aniimo-017","aniimo-018"]'::jsonb),
  ('potent-erosion', 'aniimo', 'Erosión potente', 'Potent Erosion', 'Cuando una habilidad o la Definitiva golpea a un objetivo, reduce la RES a Tierra del objetivo en 2%. Se acumula hasta 5 veces y dura 20 s.', 'When a skill or an Ultimate hits a target, reduces the target’s Earth Resistance by -3 for 20s. Stacks up to 10 times.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1043100_Feature_143301_Icon.png', 'otro', '[]'::jsonb, '["aniimo-075","aniimo-076"]'::jsonb),
  ('frostbite-sunder', 'aniimo', 'Escarcha rompeguarda', 'Frostbite Sunder', 'Los ataques básicos aplican [Despotenciador de hielo]. Inflige un 35 % de QUIEBRE adicional a los objetivos con más de 5 acumulaciones de [Despotenciador de hielo].', 'Basic attacks apply [Ice Debuff]. Deals [?]% extra BREAK to targets with more than 5 stacks of [Ice Debuff].', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1016300_Feature_116306_Icon.png', 'ruptura', '["acumulacion","ruptura"]'::jsonb, '["aniimo-025"]'::jsonb),
  ('water-spirit', 'aniimo', 'Espíritu de agua', 'Water Spirit', 'Mientras estés en terreno acuático, reduce en 16% el costo de PE de todas las habilidades.', 'While in water terrain, reduces the EP cost of all skills by 20% of EP REGEN FORCE.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1004102_Feature_10402_Icon.png', 'recursos', '["recursos"]'::jsonb, '["aniimo-013","aniimo-014","aniimo-015"]'::jsonb),
  ('battle-fervor', 'aniimo', 'Fervor de batalla', 'Battle Fervor', 'Derrotar a un objetivo otorga 1 acumulación de Sed de batalla, lo que aumenta el daño en 25% durante 20 s. Se acumula hasta 2 veces.', 'Defeating a target grants 1 stack of Battlelust, increasing damage by [?]% for 20s. Stacks up to 2 times.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1003200_Feature_10372_Icon.png', 'acumulacion', '["acumulacion"]'::jsonb, '["aniimo-040","aniimo-041"]'::jsonb),
  ('dangerous-fragrance', 'aniimo', 'Fragancia peligrosa', 'Dangerous Fragrance', 'Cuando una habilidad inflige daño a un objetivo, reduce en 12% la resistencia del objetivo a la oscuridad durante 20 s.', 'When deals damage to a target, reduces the target’s Dark Resistance by -15 for 20s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1035100_Feature_13522_Icon.png', 'penalizacion', '["penalizacion"]'::jsonb, '["aniimo-038","aniimo-039"]'::jsonb),
  ('raging-fire-151201', 'aniimo', 'Fuego Rabioso', 'Raging Fire (Squashel)', 'Después de usar una habilidad, el siguiente ataque básico usado en un plazo de 10 s lanzará directamente el golpe final del ataque básico, y su poder aumenta de 4 a 25.', 'After using a skill, the next basic attack used within 10s will directly release the final hit of the basic attack, and its Might is increased from 4 to 25.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1005304_Feature_10503_Icon.png', 'otro', '[]'::jsonb, '["aniimo-047","aniimo-048"]'::jsonb),
  ('raging-rampage', 'aniimo', 'Furia desatada', 'Raging Rampage', 'Acumula [Furia] durante la batalla. Los ataques básicos otorgan 2 puntos, cada 10 de EP gastados en habilidades otorgan 10, y recibir daño otorga 2. Al llegar a 100 puntos, entra en el estado [Enfurecido].[Enfurecido] aumenta la Vel. de ATQ y el daño de sus propias habilidades en 30%, aumenta la tasa de recuperación de EP en 25%, e impide ganar [Furia]. Dura 20 s.', 'Builds [Rage] during battle. Basic attacks grant 2 points, every 10 EP spent on skills grants 10, and taking damage grants 2. At 100 points, enters the [Enraged] state.
[Enraged] increases own skill damage by 30%, increases the EP recovery rate by [?]%, and prevents [Rage] gain. Lasts 20s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1050100_Feature_150102_Icon.png', 'recursos', '["recursos","acumulacion"]'::jsonb, '["aniimo-068","aniimo-069"]'::jsonb),
  ('rasgo-gracia-solar', 'aniimo', 'Gracia solar', 'Gracia solar', 'Al no atacar con una ventaja elemental, el daño final aumenta un 30 %. Cada 4 ataques básicos otorga [Halo solar], lo que mejora la siguiente habilidad.', null, 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1044300_Feature_144102_Icon.png', 'elemento', '["elemento"]'::jsonb, '["aniimo-99998"]'::jsonb),
  ('grand-sorcerer', 'aniimo', 'Gran hechicería', 'Grand Sorcerer', 'Durante 5 s después de usar una habilidad, los golpes de los ataques básicos infligen daño adicional que equivale a 6 de poder.', 'For 5s after using a skill, basic attack hits deal additional damage equal to 6 Might.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1001200_Feature_10175_Icon.png', 'otro', '[]'::jsonb, '["aniimo-005","aniimo-006"]'::jsonb),
  ('scorching-flames', 'aniimo', 'Llamas abrasadoras', 'Scorching Flames', 'Aumenta el daño infligido a objetivos débiles a tu elemento en 25%.', 'Increases damage dealt to elementally countered targets by [?]%.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1005304_Feature_10503_Icon.png', 'elemento', '["elemento"]'::jsonb, '["aniimo-001","aniimo-002","aniimo-003"]'::jsonb),
  ('blazing-flames', 'aniimo', 'Llamas ardientes', 'Blazing Flames', 'Siempre tiene 20 acumulaciones de [Despotenciador de fuego]. [Anillo de fuego tramposo] aplica 4 acumulaciones de [Despotenciador de fuego], mientras que [Orbe de fuego] aplica 3 acumulaciones de [Despotenciador de fuego].', 'Always has 20 stacks of [Fire Debuff]. [Trick Fire Ring] applies 4 stacks of [Fire Debuff], while [Fire Orb] applies 3 stacks of [Fire Debuff].', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1033302_Feature_133303_Icon.png', 'acumulacion', '["acumulacion"]'::jsonb, '["aniimo-026","aniimo-027"]'::jsonb),
  ('prank-master', 'aniimo', 'Maestría de las bromas', 'Prank Master', 'Aumenta un  % el daño de QUIEBRE por cada 21000 PS máximos. Al entrar en combate, invoca a 1 hummin como apoyo. Se invoca a un hummin adicional cada 10 s, hasta un máximo de 3.', 'Increases BREAK damage by % for every [?]1,000 max HP. Upon entering battle, summons 1 Hummin to assist. An additional Hummin is summoned every [?]s, up to a maximum of 3.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1020701_Feature_120701_Icon.png', 'cambio', '["cambio","ruptura"]'::jsonb, '["aniimo-022"]'::jsonb),
  ('band-member', 'aniimo', 'Miembro de la banda', 'Band Member', 'Al cambiar de Aniimo en combate, restaura 20 PE al siguiente miembro de la familia chirpi que entre. Se activa como máximo una vez cada 20 s.', 'When switching Aniimo in battle, restores 25% of ATK EP to the next Chirpi family member switched in. Triggers once every 20s at most.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1018401_Feature_11873_Icon.png', 'familia', '["familia","cambio","recursos","acumulacion"]'::jsonb, '["aniimo-007","aniimo-008"]'::jsonb),
  ('spotlight-moment', 'aniimo', 'Momento de brillar', 'Spotlight Moment', 'La primera habilidad que use este Aniimo 5 s después de entrar en combate no consume PE. Recuperación: 15 s.', 'The first skill this Aniimo uses within 5s of entering battle does not consume EP. Cooldown: [?]s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1047400_Feature_147402_Icon.png', 'recursos', '["recursos"]'::jsonb, '["aniimo-10002"]'::jsonb),
  ('overloaded-engine-145301', 'aniimo', 'Motor sobrecargado', 'Overloaded Engine (Waleetle)', 'Moverse y usar habilidades genera [Energía de sobrecarga]. Cuando la carga está completa, la siguiente habilidad inflige un 40 % de daño adicional y lleva de inmediato a [Giro de tormenta de arena] a la máxima velocidad.', 'Moving and using skills builds [Overload Energy]. When fully charged, the next skill deals [?]% extra damage and immediately brings [Sandstorm Spin] to maximum speed.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1045300_Feature_145301_Icon.png', 'recursos', '["recursos"]'::jsonb, '["aniimo-056","aniimo-057"]'::jsonb),
  ('pursuit', 'aniimo', 'Persecución', 'Pursuit', 'Inflige 30% de daño adicional a los objetivos afectados por efectos de control o Ruptura.', 'When dealing damage to targets in Controlled or Break State, increases an additional [?]% Damage Amp.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1002602_Feature_10232_Icon.png', 'ruptura', '["ruptura"]'::jsonb, '["aniimo-062"]'::jsonb),
  ('pyro-charge', 'aniimo', 'Pirocarga', 'Pyro Charge', 'Tras gastar un total de EP, obtiene [Carga Pyro]. Cada 502 s, aplica 1 acumulación de Perjuicio de Fuego a los objetivos cercanos durante 10 s.', 'After spending a total of [?] EP, gains [Pyro Charge]. Every 2s, applies 1 stack of [Fire Debuff] to nearby targets for 10s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1028301_Feature_128301_Icon.png', 'recursos', '["recursos","acumulacion"]'::jsonb, '["aniimo-071","aniimo-072"]'::jsonb),
  ('power-of-nature', 'aniimo', 'Poder de la naturaleza', 'Power of Nature', 'Mientras no estés en el campo, crea un parche de hierba bajo un compañero de equipo después de que use 3 habilidades.', 'While off field, creates a patch of Turf under a teammate after they cast 3 skills.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1004500_Feature_10473_Icon.png', 'equipo', '["equipo"]'::jsonb, '["aniimo-016"]'::jsonb),
  ('power-of-fire', 'aniimo', 'Poder del fuego', 'Power of Fire', 'Inflige 30% de daño adicional a los objetivos con más de 5 acumulaciones de perjuicio de Fuego.', 'Deals [?]% extra damage to targets with more than 5 stacks of Fire Debuff.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1002503_Feature_10252_Icon.png', 'acumulacion', '["acumulacion"]'::jsonb, '["aniimo-067"]'::jsonb),
  ('lunar-power', 'aniimo', 'Poder lunar', 'Lunar Power', 'Al no atacar con una ventaja elemental, el daño final aumenta un 30 %.Usar una habilidad o definitiva otorga 4 acumulaciones de Marca de luna de plata. Cada golpe de ataque básico consume 1 acumulación e inflige un 100 % de daño adicional, mientras restaura un 0.5 % de PS.', 'When not attacking with an advantageous element, final damage increases by 30%.
Casting a skill or Ultimate grants 4 stacks of [Silver Moon Mark]. Each basic attack hit consumes 1 stack, deals [?]% extra damage, and restores [?]% HP.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1037100_Feature_13711_Icon.png', 'penalizacion', '["acumulacion","penalizacion","elemento"]'::jsonb, '["aniimo-99996"]'::jsonb),
  ('rock-empowerment', 'aniimo', 'Potenciación de piedra', 'Rock Empowerment', 'Los [Montones de Rocas] creados por Bouldus pueden ser destruidos por Waleetle con [Deriva de Bola de Piedra], liberando ondas de choque y aplicando [Desintegración] al objetivo.[Desintegración]: Cada acumulación reduce la Resistencia a Tierra en 6% y la Velocidad de Movimiento en 5% durante 20 s. Se acumula hasta 6 veces.', '[Rock Piles] created by Bouldus can be destroyed by Waleetle’s [Stone Ball Drift], releasing shock waves and applying [Disintegration] to the target.
[Disintegration]: Each stack reduces Earth Resistance by 7.5 and Movement Speed by [?]% for 20s, up to 6 stacks.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1045401_Feature_145402_Icon.png', 'penalizacion', '["acumulacion","penalizacion","movilidad"]'::jsonb, '["aniimo-058"]'::jsonb),
  ('energized', 'aniimo', 'Rebosante de energía', 'Energized', 'Por cada 1,000 de HP máximos, aumenta el daño de RUPTURA en un 2%.', 'For every 1,000 max HP, increases BREAK damage by 2.5%.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1020101_Feature_120101_Icon.png', 'ruptura', '["recursos","ruptura"]'::jsonb, '["aniimo-020"]'::jsonb),
  ('guardbreak-resonance', 'aniimo', 'Resonancia rompeguardia', 'Guardbreak Resonance', 'Aumenta un 0 el QUIEBRE.', 'Increases BREAK by 100% of DEF.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1002102_Feature_102101_Icon.png', 'ruptura', '["ruptura"]'::jsonb, '["aniimo-061","aniimo-063"]'::jsonb),
  ('arc-surge', 'aniimo', 'Sobrecarga de arco', 'Arc Surge', 'Los compañeros de equipo que reciban la mejora de habilidad de este Aniimo también obtienen 12% de daño de Rayo durante 20 s.', 'Teammates who receive this Aniimo’s skill buff also gain a 15 Lightning boost for [?]s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1014302_Feature_11431_Icon.png', 'equipo', '["equipo"]'::jsonb, '["aniimo-077","aniimo-078","aniimo-079"]'::jsonb),
  ('power-surge', 'aniimo', 'Sobrecarga de poder', 'Power Surge', 'Restaura 4 PE al usar una habilidad con menos de 20 PE.', 'When casting a skill with less than 20 EP, restores 5 EP.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1012200_Feature_11272_Icon.png', 'recursos', '["recursos"]'::jsonb, '["aniimo-082"]'::jsonb),
  ('air-superiority', 'aniimo', 'Superioridad aérea', 'Air Superiority', 'Aumenta un 20 % la tasa de crítico mientras vuelas.', 'Increases Crit Rate by [?]% while flying.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1018502_Feature_11874_Icon.png', 'critico', '["critico"]'::jsonb, '["aniimo-009"]'::jsonb),
  ('judgment-storm', 'aniimo', 'Tormenta de juicio', 'Judgment Storm', 'Cuando una habilidad aplica un despotenciador a un objetivo, el daño de viento de todo el equipo aumenta un 16% % durante 20 s.', 'When applies a debuff to a target, Wind damage for the whole team increases by 20 for [?]s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1044300_Feature_144102_Icon.png', 'equipo', '["equipo","elemento"]'::jsonb, '["aniimo-031","aniimo-032"]'::jsonb),
  ('biting-wind', 'aniimo', 'Viento cortante', 'Biting Wind', 'Al infligir daño a objetivos con más de 5 acumulaciones de [Despotenciador de hielo], la tasa de crítico de ese daño aumenta un 15 %.', 'When dealing damage to targets with more than 5 stacks of [Ice Debuff], increases Crit Rate of that damage by [?]%.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1013102_Feature_11372_Icon.png', 'critico', '["acumulacion","critico"]'::jsonb, '["aniimo-042","aniimo-043","aniimo-044"]'::jsonb),
  ('thunderbond', 'aniimo', 'Vínculo de trueno', 'Thunderbond', 'Cuando el ataque de este Aniimo golpea a un objetivo, obtiene 1 acumulación de [Vínculo de trueno]. Con 30 acumulaciones, entra en la [Postura de alatrueno] al usar su siguiente habilidad o definitiva. Dura 10 s.', 'When this Aniimo’s attack hits a target, it gains 1 stack of [Thunderbond]. At 30 stacks, it enters the [Thunderwing Stance] when using its next skill or Ultimate. Lasts 10s.', 'https://worldx-website-cdn.aniimo.com/official-website/worldx/wiki_stage/init/1029100_Feature_12932_Icon.png', 'acumulacion', '["acumulacion"]'::jsonb, '["aniimo-059","aniimo-060"]'::jsonb)
on conflict (id) do update
  set name_es = excluded.name_es,
      name_en = excluded.name_en,
      description_es = excluded.description_es,
      description_en = excluded.description_en,
      icon_url = excluded.icon_url,
      effect_type = excluded.effect_type,
      tags = excluded.tags,
      creature_ids = excluded.creature_ids,
      updated_at = now();

-- Comprobacion
select effect_type, count(*) as rasgos
from public.traits
where game_id = 'aniimo'
group by effect_type
order by effect_type;
