-- Ejecutar en Supabase → SQL Editor → New query → Run.
-- Requiere characters.sql ya ejecutado.
--
-- Reemplaza el catalogo de Genshin, Honkai y Zenless por las listas completas.
-- High School DxD no se toca.
--
-- Columnas nuevas:
--   role      = tipo de personaje / rol principal
--   path      = Via en Honkai, Especialidad en Zenless
--   signature = cono de luz o motor-W recomendado
--   biography = pendiente de rellenar con la historia oficial

alter table public.characters add column if not exists role text;
alter table public.characters add column if not exists path text;
alter table public.characters add column if not exists signature text;
alter table public.characters add column if not exists biography text;

-- Ojo: borra tambien los favoritos guardados de estos juegos (cascada).
delete from public.characters
where game_id in ('genshin-impact', 'honkai-star-rail', 'zenless-zone-zero');

-- ---------------------------------------------------------------------------
-- Genshin Impact
-- ---------------------------------------------------------------------------
insert into public.characters (id, game_id, name, rarity, element, level_cap, role) values
  ('gi-aino', 'genshin-impact', 'Aino', '4', 'Hydro', 90, 'Sub-DPS / Support'),
  ('gi-albedo', 'genshin-impact', 'Albedo', '5', 'Geo', 90, 'Sub-DPS / Buffer'),
  ('gi-alhaitham', 'genshin-impact', 'Alhacén (Alhaitham)', '5', 'Dendro', 90, 'DPS'),
  ('gi-aloy', 'genshin-impact', 'Aloy', '5', 'Cryo', 90, 'Sub-DPS / DPS'),
  ('gi-alyosha', 'genshin-impact', 'Alyosha', '5', 'Electro', 90, 'Sub-DPS / DPS'),
  ('gi-amber', 'genshin-impact', 'Amber', '4', 'Pyro', 90, 'Sub-DPS / Support'),
  ('gi-arataki-itto', 'genshin-impact', 'Arataki Itto', '5', 'Geo', 90, 'DPS'),
  ('gi-arlecchino', 'genshin-impact', 'Arlecchino', '5', 'Pyro', 90, 'DPS'),
  ('gi-baizhu', 'genshin-impact', 'Baizhu', '5', 'Dendro', 90, 'Support (Healer) / Buffer'),
  ('gi-barbara', 'genshin-impact', 'Bárbara', '4', 'Hydro', 90, 'Support (Healer)'),
  ('gi-beidou', 'genshin-impact', 'Beidou', '4', 'Electro', 90, 'Sub-DPS / Tanque'),
  ('gi-bennett', 'genshin-impact', 'Bennett', '4', 'Pyro', 90, 'Buffer / Support (Healer)'),
  ('gi-candace', 'genshin-impact', 'Candace', '4', 'Hydro', 90, 'Buffer / Tanque'),
  ('gi-charlotte', 'genshin-impact', 'Charlotte', '4', 'Cryo', 90, 'Support (Healer)'),
  ('gi-chasca', 'genshin-impact', 'Chasca', '5', 'Anemo', 90, 'DPS / Sub-DPS'),
  ('gi-chevreuse', 'genshin-impact', 'Chevreuse', '4', 'Pyro', 90, 'Buffer / Support (Healer)'),
  ('gi-chiori', 'genshin-impact', 'Chiori', '5', 'Geo', 90, 'Sub-DPS'),
  ('gi-chongyun', 'genshin-impact', 'Chongyun', '4', 'Cryo', 90, 'Sub-DPS / Buffer'),
  ('gi-citlali', 'genshin-impact', 'Citlalí', '5', 'Cryo', 90, 'Tanque / Debuffer'),
  ('gi-clorinde', 'genshin-impact', 'Clorinde', '5', 'Electro', 90, 'DPS'),
  ('gi-collei', 'genshin-impact', 'Collei', '4', 'Dendro', 90, 'Sub-DPS / Support'),
  ('gi-columbina', 'genshin-impact', 'Columbina', '5', 'Hydro', 90, 'Sub-DPS / Support'),
  ('gi-cyno', 'genshin-impact', 'Cyno', '5', 'Electro', 90, 'DPS'),
  ('gi-dehya', 'genshin-impact', 'Dehya', '5', 'Pyro', 90, 'Tanque / Sub-DPS'),
  ('gi-diluc', 'genshin-impact', 'Diluc', '5', 'Pyro', 90, 'DPS'),
  ('gi-diona', 'genshin-impact', 'Diona', '4', 'Cryo', 90, 'Tanque / Support (Healer)'),
  ('gi-dori', 'genshin-impact', 'Dori', '4', 'Electro', 90, 'Support (Healer)'),
  ('gi-emilie', 'genshin-impact', 'Emilie', '5', 'Dendro', 90, 'Sub-DPS / Support'),
  ('gi-eula', 'genshin-impact', 'Eula', '5', 'Cryo', 90, 'DPS (Físico)'),
  ('gi-faruzan', 'genshin-impact', 'Faruzán', '4', 'Anemo', 90, 'Buffer / Debuffer'),
  ('gi-fischl', 'genshin-impact', 'Fischl', '4', 'Electro', 90, 'Sub-DPS'),
  ('gi-flins', 'genshin-impact', 'Flins', '5', 'Electro', 90, 'DPS'),
  ('gi-freminet', 'genshin-impact', 'Fréminet', '4', 'Cryo', 90, 'DPS'),
  ('gi-furina', 'genshin-impact', 'Furina', '5', 'Hydro', 90, 'Buffer / Sub-DPS'),
  ('gi-gaming', 'genshin-impact', 'Gaming', '4', 'Pyro', 90, 'DPS'),
  ('gi-ganyu', 'genshin-impact', 'Ganyu', '5', 'Cryo', 90, 'DPS / Sub-DPS'),
  ('gi-gorou', 'genshin-impact', 'Gorou', '4', 'Geo', 90, 'Buffer'),
  ('gi-hu-tao', 'genshin-impact', 'Hu Tao', '5', 'Pyro', 90, 'DPS'),
  ('gi-iansan', 'genshin-impact', 'Iansán', '4', 'Electro', 90, 'Sub-DPS'),
  ('gi-ineffa', 'genshin-impact', 'Ineffa', '5', 'Electro', 90, 'DPS'),
  ('gi-jean', 'genshin-impact', 'Jean', '5', 'Anemo', 90, 'Support (Healer) / Debuffer'),
  ('gi-kachina', 'genshin-impact', 'Kachina', '4', 'Geo', 90, 'Sub-DPS / Support'),
  ('gi-kazuha', 'genshin-impact', 'Kaedehara Kazuha', '5', 'Anemo', 90, 'Buffer / Debuffer'),
  ('gi-kaeya', 'genshin-impact', 'Kaeya', '4', 'Cryo', 90, 'Sub-DPS'),
  ('gi-ayaka', 'genshin-impact', 'Kamisato Ayaka', '5', 'Cryo', 90, 'DPS'),
  ('gi-ayato', 'genshin-impact', 'Kamisato Ayato', '5', 'Hydro', 90, 'DPS'),
  ('gi-kaveh', 'genshin-impact', 'Kaveh', '4', 'Dendro', 90, 'DPS / Support'),
  ('gi-keqing', 'genshin-impact', 'Keqing', '5', 'Electro', 90, 'DPS'),
  ('gi-kinich', 'genshin-impact', 'Kinich', '5', 'Dendro', 90, 'DPS'),
  ('gi-kirara', 'genshin-impact', 'Kirara', '4', 'Dendro', 90, 'Tanque / Sub-DPS'),
  ('gi-klee', 'genshin-impact', 'Klee', '5', 'Pyro', 90, 'DPS'),
  ('gi-kujou-sara', 'genshin-impact', 'Kujou Sara', '4', 'Electro', 90, 'Buffer / Sub-DPS'),
  ('gi-kuki-shinobu', 'genshin-impact', 'Kuki Shinobu', '4', 'Electro', 90, 'Support (Healer) / Sub-DPS'),
  ('gi-layla', 'genshin-impact', 'Laila (Layla)', '4', 'Cryo', 90, 'Tanque'),
  ('gi-lan-yan', 'genshin-impact', 'Lan Yan', '4', 'Anemo', 90, 'Support / Sub-DPS'),
  ('gi-lisa', 'genshin-impact', 'Lisa', '4', 'Electro', 90, 'Sub-DPS / Debuffer'),
  ('gi-lynette', 'genshin-impact', 'Lynette', '4', 'Anemo', 90, 'Sub-DPS / Support'),
  ('gi-lyney', 'genshin-impact', 'Lyney', '5', 'Pyro', 90, 'DPS'),
  ('gi-mavuika', 'genshin-impact', 'Mavuika (Arconte Pyro)', '5', 'Pyro', 90, 'DPS / Buffer'),
  ('gi-mika', 'genshin-impact', 'Mika', '4', 'Cryo', 90, 'Buffer / Support (Healer)'),
  ('gi-mona', 'genshin-impact', 'Mona', '5', 'Hydro', 90, 'Buffer / Sub-DPS'),
  ('gi-mualani', 'genshin-impact', 'Mualani', '5', 'Hydro', 90, 'DPS'),
  ('gi-nahida', 'genshin-impact', 'Nahida (Arconte Dendro)', '5', 'Dendro', 90, 'Sub-DPS / Buffer'),
  ('gi-navia', 'genshin-impact', 'Navia', '5', 'Geo', 90, 'DPS'),
  ('gi-neuvillette', 'genshin-impact', 'Neuvillette', '5', 'Hydro', 90, 'DPS'),
  ('gi-nilou', 'genshin-impact', 'Nilou', '5', 'Hydro', 90, 'Buffer / Sub-DPS'),
  ('gi-ningguang', 'genshin-impact', 'Ningguang', '4', 'Geo', 90, 'DPS / Sub-DPS'),
  ('gi-noelle', 'genshin-impact', 'Noelle', '4', 'Geo', 90, 'Tanque / Support (Healer) / DPS'),
  ('gi-odette', 'genshin-impact', 'Odette', '5', 'Cryo', 90, 'Sub-DPS / Support'),
  ('gi-ororon', 'genshin-impact', 'Ororon', '4', 'Electro', 90, 'Sub-DPS'),
  ('gi-qiqi', 'genshin-impact', 'Qiqi', '5', 'Cryo', 90, 'Support (Healer)'),
  ('gi-razor', 'genshin-impact', 'Razor', '4', 'Electro', 90, 'DPS (Físico)'),
  ('gi-rosaria', 'genshin-impact', 'Rosaria', '4', 'Cryo', 90, 'Sub-DPS / Buffer'),
  ('gi-sucrose', 'genshin-impact', 'Sacarosa (Sucrose)', '4', 'Anemo', 90, 'Buffer / Debuffer'),
  ('gi-kokomi', 'genshin-impact', 'Sangonomiya Kokomi', '5', 'Hydro', 90, 'Support (Healer) / Sub-DPS'),
  ('gi-sayu', 'genshin-impact', 'Sayu', '4', 'Anemo', 90, 'Support (Healer)'),
  ('gi-sethos', 'genshin-impact', 'Sethos', '4', 'Electro', 90, 'DPS'),
  ('gi-shenhe', 'genshin-impact', 'Shenhe', '5', 'Cryo', 90, 'Buffer / Sub-DPS'),
  ('gi-heizou', 'genshin-impact', 'Shikanoin Heizou', '4', 'Anemo', 90, 'DPS'),
  ('gi-raiden', 'genshin-impact', 'Shogun Raiden (Arconte)', '5', 'Electro', 90, 'DPS / Buffer'),
  ('gi-sigewinne', 'genshin-impact', 'Sigewinne', '5', 'Hydro', 90, 'Support (Healer) / Buffer'),
  ('gi-tartaglia', 'genshin-impact', 'Tartaglia (Childe)', '5', 'Hydro', 90, 'DPS'),
  ('gi-thoma', 'genshin-impact', 'Thoma', '4', 'Pyro', 90, 'Tanque / Sub-DPS'),
  ('gi-tighnari', 'genshin-impact', 'Tignari (Tighnari)', '5', 'Dendro', 90, 'DPS'),
  ('gi-wanderer', 'genshin-impact', 'Trotamundos (Wanderer)', '5', 'Anemo', 90, 'DPS'),
  ('gi-venti', 'genshin-impact', 'Venti (Arconte Anemo)', '5', 'Anemo', 90, 'Support / Debuffer'),
  ('gi-traveler', 'genshin-impact', 'Viajero (Traveler)', '5', 'Multi-elemento', 90, 'Support / Sub-DPS (Varía por elemento)'),
  ('gi-wriothesley', 'genshin-impact', 'Wriothesley', '5', 'Cryo', 90, 'DPS'),
  ('gi-xiangling', 'genshin-impact', 'Xiangling', '4', 'Pyro', 90, 'Sub-DPS'),
  ('gi-xianyun', 'genshin-impact', 'Xianyun (Preservadora)', '5', 'Anemo', 90, 'Support (Healer) / Buffer'),
  ('gi-xiao', 'genshin-impact', 'Xiao', '5', 'Anemo', 90, 'DPS'),
  ('gi-xilonen', 'genshin-impact', 'Xilonen', '5', 'Geo', 90, 'Support / Debuffer'),
  ('gi-xingqiu', 'genshin-impact', 'Xingchiu (Xingqiu)', '4', 'Hydro', 90, 'Sub-DPS / Support'),
  ('gi-xinyan', 'genshin-impact', 'Xinyan', '4', 'Pyro', 90, 'Tanque / DPS'),
  ('gi-yae-miko', 'genshin-impact', 'Yae Miko', '5', 'Electro', 90, 'Sub-DPS'),
  ('gi-yanfei', 'genshin-impact', 'Yanfei', '4', 'Pyro', 90, 'DPS'),
  ('gi-yaoyao', 'genshin-impact', 'Yaoyao', '4', 'Dendro', 90, 'Support (Healer)'),
  ('gi-yelan', 'genshin-impact', 'Yelan', '5', 'Hydro', 90, 'Sub-DPS / Buffer'),
  ('gi-yoimiya', 'genshin-impact', 'Yoimiya', '5', 'Pyro', 90, 'DPS'),
  ('gi-yun-jin', 'genshin-impact', 'Yun Jin', '4', 'Geo', 90, 'Buffer'),
  ('gi-zhongli', 'genshin-impact', 'Zhongli (Arconte Geo)', '5', 'Geo', 90, 'Tanque / Debuffer');

-- ---------------------------------------------------------------------------
-- Honkai: Star Rail
-- ---------------------------------------------------------------------------
insert into public.characters (id, game_id, name, rarity, element, level_cap, role, path, signature) values
  ('hsr-acheron', 'honkai-star-rail', 'Acheron', '5', 'Rayo', 80, 'DPS', 'Nihilidad', 'En la orilla inalcanzable'),
  ('hsr-aglaea', 'honkai-star-rail', 'Aglaea', '5', 'Rayo', 80, 'Sub-DPS / Debuffer (Congelación)', 'Memoria', 'Cono de firma de Aglaea'),
  ('hsr-anaxa', 'honkai-star-rail', 'Anaxa', '5', 'Viento', 80, 'DPS', 'Erudición', 'Cono de firma de Anaxa'),
  ('hsr-archer', 'honkai-star-rail', 'Archer (Collab)', '5', 'Cuántico', 80, 'DPS', 'Cacería', 'Cono de evento/firma'),
  ('hsr-argenti', 'honkai-star-rail', 'Argenti', '5', 'Físico', 80, 'DPS', 'Erudición', 'Un instante frente a la mirada'),
  ('hsr-arlan', 'honkai-star-rail', 'Arlan', '4', 'Rayo', 80, 'DPS', 'Destrucción', 'Voto secreto'),
  ('hsr-asta', 'honkai-star-rail', 'Asta', '4', 'Fuego', 80, 'Buffer', 'Armonía', 'Encuentro planetario / ¡A bailar!'),
  ('hsr-aventurine', 'honkai-star-rail', 'Aventurino (Aventurine)', '5', 'Imaginario', 80, 'Tanque / Sub-DPS', 'Conservación', 'El destino nunca es justo'),
  ('hsr-bailu', 'honkai-star-rail', 'Bailu', '5', 'Rayo', 80, 'Support (Healer)', 'Abundancia', 'El tiempo no espera a nadie'),
  ('hsr-black-swan', 'honkai-star-rail', 'Black Swan', '5', 'Viento', 80, 'Sub-DPS / Debuffer (DoT)', 'Nihilidad', 'Recuerdo reconstruido'),
  ('hsr-blade', 'honkai-star-rail', 'Blade', '5', 'Viento', 80, 'DPS', 'Destrucción', 'El lado inalcanzable'),
  ('hsr-boothill', 'honkai-star-rail', 'Boothill', '5', 'Físico', 80, 'DPS', 'Cacería', 'Navegando hacia una segunda vida'),
  ('hsr-bronya', 'honkai-star-rail', 'Bronya', '5', 'Viento', 80, 'Buffer', 'Armonía', 'La batalla no ha terminado'),
  ('hsr-castorice', 'honkai-star-rail', 'Castorice', '5', 'Cuántico', 80, 'Support / Debuffer', 'Memoria', 'Cono de firma de Castorice'),
  ('hsr-cerydra', 'honkai-star-rail', 'Cerydra', '4', 'Viento', 80, 'Buffer', 'Armonía', 'Cono de firma de Cerydra'),
  ('hsr-cipher', 'honkai-star-rail', 'Cipher', '4', 'Cuántico', 80, 'Debuffer', 'Nihilidad', 'Cono de firma de Cipher'),
  ('hsr-clara', 'honkai-star-rail', 'Clara', '5', 'Físico', 80, 'Tanque / DPS', 'Destrucción', 'Algo irremplazable'),
  ('hsr-cyrene', 'honkai-star-rail', 'Cyrene', '4', 'Hielo', 80, 'Debuffer / Support', 'Memoria', 'Cono de firma de Cyrene'),
  ('hsr-dan-heng', 'honkai-star-rail', 'Dan Heng', '4', 'Viento', 80, 'DPS', 'Cacería', 'El silencio perdura'),
  ('hsr-imbibitor-lunae', 'honkai-star-rail', 'Dan Heng (Imbibitor Lunae)', '5', 'Imaginario', 80, 'DPS', 'Destrucción', 'Más brillante que el sol'),
  ('hsr-permanser-terrae', 'honkai-star-rail', 'Dan Heng (Permanser Terrae)', '5', 'Físico', 80, 'Tanque', 'Conservación', 'Cono de firma de Permanser Terrae'),
  ('hsr-dr-ratio', 'honkai-star-rail', 'Dr. Ratio', '5', 'Imaginario', 80, 'DPS', 'Cacería', 'El bautismo del pensamiento puro'),
  ('hsr-evernight', 'honkai-star-rail', 'Evernight', '5', 'Hielo', 80, 'Debuffer (Control)', 'Memoria', 'Cono de firma de Evernight'),
  ('hsr-feixiao', 'honkai-star-rail', 'Feixiao', '5', 'Viento', 80, 'DPS', 'Cacería', 'Salgo a cazar'),
  ('hsr-firefly', 'honkai-star-rail', 'Firefly (Sam)', '5', 'Fuego', 80, 'DPS (Ruptura)', 'Destrucción', 'Donde los sueños descansan'),
  ('hsr-fu-xuan', 'honkai-star-rail', 'Fu Xuan', '5', 'Cuántico', 80, 'Tanque / Buffer', 'Conservación', 'Ella ya ha cerrado los ojos'),
  ('hsr-fugue', 'honkai-star-rail', 'Fugue (Tingyun 5⭐)', '5', 'Fuego', 80, 'Debuffer / Buffer', 'Nihilidad', 'El largo camino a casa'),
  ('hsr-gallagher', 'honkai-star-rail', 'Gallagher', '4', 'Fuego', 80, 'Support (Healer)', 'Abundancia', 'Quédate (Recomendado)'),
  ('hsr-gepard', 'honkai-star-rail', 'Gepard', '5', 'Hielo', 80, 'Tanque', 'Conservación', 'El momento de la victoria'),
  ('hsr-gilgamesh', 'honkai-star-rail', 'Gilgamesh (Collab)', '5', 'Imaginario', 80, 'DPS', 'Erudición', 'Cono de evento/firma'),
  ('hsr-guinaifen', 'honkai-star-rail', 'Guinaifen', '4', 'Fuego', 80, 'Sub-DPS / Debuffer (DoT)', 'Nihilidad', 'Las miradas del pasado (Recomendado)'),
  ('hsr-hanya', 'honkai-star-rail', 'Hanya', '4', 'Físico', 80, 'Buffer', 'Armonía', 'Bajo el cielo azul'),
  ('hsr-herta', 'honkai-star-rail', 'Herta', '4', 'Hielo', 80, 'Sub-DPS', 'Erudición', 'El nacimiento del yo'),
  ('hsr-himeko', 'honkai-star-rail', 'Himeko', '5', 'Fuego', 80, 'DPS / Sub-DPS', 'Erudición', 'Noche en la Vía Láctea'),
  ('hsr-hook', 'honkai-star-rail', 'Hook', '4', 'Fuego', 80, 'DPS', 'Destrucción', 'Topos al rescate'),
  ('hsr-huohuo', 'honkai-star-rail', 'Huohuo', '5', 'Viento', 80, 'Support (Healer) / Buffer', 'Abundancia', 'Noche de terror'),
  ('hsr-hyacine', 'honkai-star-rail', 'Hyacine', '4', 'Viento', 80, 'Debuffer / Sub-DPS', 'Memoria', 'Cono de firma de Hyacine'),
  ('hsr-hysilens', 'honkai-star-rail', 'Hysilens', '4', 'Físico', 80, 'Debuffer', 'Nihilidad', 'Cono de firma de Hysilens'),
  ('hsr-jade', 'honkai-star-rail', 'Jade', '5', 'Cuántico', 80, 'Sub-DPS', 'Erudición', 'La esperanza es incalculable'),
  ('hsr-jiaoqiu', 'honkai-star-rail', 'Jiaoqiu', '5', 'Fuego', 80, 'Debuffer / Sub-DPS', 'Nihilidad', 'Incontables primaveras'),
  ('hsr-jing-yuan', 'honkai-star-rail', 'Jing Yuan', '5', 'Rayo', 80, 'DPS', 'Erudición', 'Antes del amanecer'),
  ('hsr-jingliu', 'honkai-star-rail', 'Jingliu', '5', 'Hielo', 80, 'DPS', 'Destrucción', 'Yo seré mi propia espada'),
  ('hsr-kafka', 'honkai-star-rail', 'Kafka', '5', 'Rayo', 80, 'DPS (DoT)', 'Nihilidad', 'Solo hay que tener paciencia'),
  ('hsr-lingsha', 'honkai-star-rail', 'Lingsha', '5', 'Fuego', 80, 'Support (Healer) / Sub-DPS', 'Abundancia', 'El aroma perdura'),
  ('hsr-luka', 'honkai-star-rail', 'Luka', '4', 'Físico', 80, 'Sub-DPS / Debuffer', 'Nihilidad', 'Determinación'),
  ('hsr-luocha', 'honkai-star-rail', 'Luocha', '5', 'Imaginario', 80, 'Support (Healer)', 'Abundancia', 'Ecos del ataúd'),
  ('hsr-lynx', 'honkai-star-rail', 'Lynx', '4', 'Cuántico', 80, 'Support (Healer)', 'Abundancia', 'Momento de calidez'),
  ('hsr-march-7th', 'honkai-star-rail', 'March 7th', '4', 'Hielo', 80, 'Tanque / Debuffer', 'Conservación', 'El primer día del resto de mi vida'),
  ('hsr-march-7th-imaginaria', 'honkai-star-rail', 'March 7th (Imaginaria)', '4', 'Imaginario', 80, 'Sub-DPS / DPS', 'Cacería', 'El silencio perdura (Recomendado)'),
  ('hsr-misha', 'honkai-star-rail', 'Misha', '4', 'Hielo', 80, 'DPS', 'Destrucción', 'Promesa imborrable'),
  ('hsr-moze', 'honkai-star-rail', 'Moze', '4', 'Rayo', 80, 'Sub-DPS', 'Cacería', 'Un juego de sombras (Recomendado)'),
  ('hsr-mydei', 'honkai-star-rail', 'Mydei', '5', 'Imaginario', 80, 'DPS', 'Destrucción', 'Cono de firma de Mydei'),
  ('hsr-natasha', 'honkai-star-rail', 'Natasha', '4', 'Físico', 80, 'Support (Healer)', 'Abundancia', 'Sentimiento compartido'),
  ('hsr-pela', 'honkai-star-rail', 'Pela', '4', 'Hielo', 80, 'Debuffer', 'Nihilidad', 'Determinación / Buenas noches'),
  ('hsr-phainon', 'honkai-star-rail', 'Phainon', '5', 'Físico', 80, 'DPS', 'Destrucción', 'Cono de firma de Phainon'),
  ('hsr-qingque', 'honkai-star-rail', 'Qingque', '4', 'Cuántico', 80, 'DPS', 'Erudición', 'Que el mundo clame'),
  ('hsr-rappa', 'honkai-star-rail', 'Rappa', '5', 'Imaginario', 80, 'DPS', 'Erudición', 'Inscripción ninja: Rompemaldiciones'),
  ('hsr-rin-tohsaka', 'honkai-star-rail', 'Rin Tohsaka (Collab)', '5', 'Fuego', 80, 'DPS / Sub-DPS', 'Erudición', 'Cono de evento/firma'),
  ('hsr-robin', 'honkai-star-rail', 'Robin', '5', 'Físico', 80, 'Buffer', 'Armonía', 'Destellos nocturnos'),
  ('hsr-ruan-mei', 'honkai-star-rail', 'Ruan Mei', '5', 'Hielo', 80, 'Buffer (Ruptura)', 'Armonía', 'El reflejo del pasado'),
  ('hsr-saber', 'honkai-star-rail', 'Saber (Collab)', '5', 'Viento', 80, 'DPS', 'Destrucción', 'Cono de evento/firma'),
  ('hsr-sampo', 'honkai-star-rail', 'Sampo', '4', 'Viento', 80, 'Sub-DPS (DoT)', 'Nihilidad', 'Las miradas del pasado'),
  ('hsr-seele', 'honkai-star-rail', 'Seele', '5', 'Cuántico', 80, 'DPS', 'Cacería', 'En la noche'),
  ('hsr-serval', 'honkai-star-rail', 'Serval', '4', 'Rayo', 80, 'Sub-DPS / DPS', 'Erudición', 'Que el mundo clame'),
  ('hsr-silver-wolf', 'honkai-star-rail', 'Silver Wolf', '5', 'Cuántico', 80, 'Debuffer', 'Nihilidad', 'Lluvia incesante'),
  ('hsr-sparkle', 'honkai-star-rail', 'Sparkle (Hanabi)', '5', 'Cuántico', 80, 'Buffer', 'Armonía', 'Aventura terrenal'),
  ('hsr-sunday', 'honkai-star-rail', 'Sunday', '5', 'Imaginario', 80, 'Buffer', 'Armonía', 'Un ascenso terrenal'),
  ('hsr-sushang', 'honkai-star-rail', 'Sushang', '4', 'Físico', 80, 'DPS', 'Cacería', 'Esgrima'),
  ('hsr-the-herta', 'honkai-star-rail', 'The Herta (La Herta)', '5', 'Hielo', 80, 'DPS', 'Erudición', 'Hacia el velo inalcanzable'),
  ('hsr-tingyun', 'honkai-star-rail', 'Tingyun', '4', 'Rayo', 80, 'Buffer', 'Armonía', '¡A bailar! / Tallar la luna'),
  ('hsr-topaz', 'honkai-star-rail', 'Topaz y Numby', '5', 'Fuego', 80, 'Sub-DPS / Buffer', 'Cacería', 'Preocupación y felicidad'),
  ('hsr-trazacaminos-fisico', 'honkai-star-rail', 'Trazacaminos (Físico)', '5', 'Físico', 80, 'DPS', 'Destrucción', 'Sobre la caída de un eón'),
  ('hsr-trazacaminos-fuego', 'honkai-star-rail', 'Trazacaminos (Fuego)', '5', 'Fuego', 80, 'Tanque', 'Conservación', 'Textura de los recuerdos'),
  ('hsr-trazacaminos-imaginario', 'honkai-star-rail', 'Trazacaminos (Imag.)', '5', 'Imaginario', 80, 'Buffer (Ruptura)', 'Armonía', 'El pasado y el futuro'),
  ('hsr-trazacaminos-hielo', 'honkai-star-rail', 'Trazacaminos (Hielo)', '5', 'Hielo', 80, 'Debuffer / Support', 'Memoria', 'Cono de Memoria gratuito'),
  ('hsr-tribbie', 'honkai-star-rail', 'Tribbie', '5', 'Cuántico', 80, 'Buffer', 'Armonía', 'Cono de firma de Tribbie'),
  ('hsr-welt', 'honkai-star-rail', 'Welt', '5', 'Imaginario', 80, 'Debuffer / Sub-DPS', 'Nihilidad', 'En el nombre del mundo'),
  ('hsr-xueyi', 'honkai-star-rail', 'Xueyi', '4', 'Cuántico', 80, 'DPS', 'Destrucción', 'Promesa imborrable / Sobre la caída'),
  ('hsr-yanqing', 'honkai-star-rail', 'Yanqing', '5', 'Hielo', 80, 'DPS', 'Cacería', 'Dormir como un tronco'),
  ('hsr-yukong', 'honkai-star-rail', 'Yukong', '4', 'Imaginario', 80, 'Buffer', 'Armonía', 'El pasado y el futuro'),
  ('hsr-yunli', 'honkai-star-rail', 'Yunli', '5', 'Físico', 80, 'Tanque / DPS', 'Destrucción', 'Danza al atardecer');

-- ---------------------------------------------------------------------------
-- Zenless Zone Zero
-- ---------------------------------------------------------------------------
insert into public.characters (id, game_id, name, rarity, element, level_cap, role, path, signature) values
  ('zzz-anby', 'zenless-zone-zero', 'Anby Demara', 'A', 'Eléctrico', 60, 'Sub-DPS / Debuffer', 'Aturdimiento', 'Batería Demara II'),
  ('zzz-anton', 'zenless-zone-zero', 'Anton Ivanov', 'A', 'Eléctrico', 60, 'DPS', 'Ataque', 'Taladro del eje rojo'),
  ('zzz-ben', 'zenless-zone-zero', 'Ben Bigger', 'A', 'Fuego', 60, 'Tanque / Sub-DPS', 'Defensa', 'Cilindro enorme'),
  ('zzz-billy', 'zenless-zone-zero', 'Billy Kid', 'A', 'Físico', 60, 'DPS', 'Ataque', 'Réplica del motor estelar'),
  ('zzz-burnice', 'zenless-zone-zero', 'Burnice White', 'S', 'Fuego', 60, 'Sub-DPS / Debuffer (DoT)', 'Anomalía', 'Agitador de llamas'),
  ('zzz-caesar', 'zenless-zone-zero', 'Caesar King', 'S', 'Físico', 60, 'Tanque / Buffer', 'Defensa', 'Colmillos de furia'),
  ('zzz-corin', 'zenless-zone-zero', 'Corin Wickes', 'A', 'Físico', 60, 'DPS', 'Ataque', 'Ama de llaves'),
  ('zzz-ellen', 'zenless-zone-zero', 'Ellen Joe', 'S', 'Hielo', 60, 'DPS', 'Ataque', 'Visitante de las profundidades'),
  ('zzz-grace', 'zenless-zone-zero', 'Grace Howard', 'S', 'Eléctrico', 60, 'DPS (DoT) / Debuffer', 'Anomalía', 'Cámara de fusión'),
  ('zzz-harumasa', 'zenless-zone-zero', 'Harumasa', 'S', 'Eléctrico', 60, 'DPS', 'Ataque', 'Motor-W de firma de Harumasa'),
  ('zzz-jane-doe', 'zenless-zone-zero', 'Jane Doe', 'S', 'Físico', 60, 'DPS (DoT)', 'Anomalía', 'Púas afiladas'),
  ('zzz-koleda', 'zenless-zone-zero', 'Koleda Belobog', 'S', 'Fuego', 60, 'Sub-DPS / Debuffer', 'Aturdimiento', 'Horno infernal'),
  ('zzz-lighter', 'zenless-zone-zero', 'Lighter', 'S', 'Fuego', 60, 'Sub-DPS / Debuffer', 'Aturdimiento', 'Corona de laureles'),
  ('zzz-lucy', 'zenless-zone-zero', 'Lucy', 'A', 'Fuego', 60, 'Buffer', 'Apoyo', 'Cañón catapum'),
  ('zzz-lycaon', 'zenless-zone-zero', 'Lycaon (Von Lycaon)', 'S', 'Hielo', 60, 'Sub-DPS / Debuffer', 'Aturdimiento', 'Restricción inquebrantable'),
  ('zzz-miyabi', 'zenless-zone-zero', 'Miyabi', 'S', 'Hielo', 60, 'DPS (DoT)', 'Anomalía', 'Motor-W de firma de Miyabi'),
  ('zzz-nekomata', 'zenless-zone-zero', 'Nekomata', 'S', 'Físico', 60, 'DPS', 'Ataque', 'Cuna de acero'),
  ('zzz-nicole', 'zenless-zone-zero', 'Nicole Demara', 'A', 'Etéreo', 60, 'Debuffer (Defensa)', 'Apoyo', 'La caja fuerte'),
  ('zzz-piper', 'zenless-zone-zero', 'Piper Wheel', 'A', 'Físico', 60, 'Sub-DPS / Debuffer', 'Anomalía', 'Viaje rugiente'),
  ('zzz-qingyi', 'zenless-zone-zero', 'Qingyi', 'S', 'Eléctrico', 60, 'Sub-DPS / Debuffer', 'Aturdimiento', 'Tetera de jade helado'),
  ('zzz-rina', 'zenless-zone-zero', 'Rina (Alexandrina)', 'S', 'Eléctrico', 60, 'Buffer (Perforación)', 'Apoyo', 'Cuna del llanto'),
  ('zzz-seth', 'zenless-zone-zero', 'Seth Lowell', 'A', 'Eléctrico', 60, 'Tanque / Buffer', 'Defensa', 'Pacificador'),
  ('zzz-soldado-11', 'zenless-zone-zero', 'Soldado 11', 'S', 'Fuego', 60, 'DPS', 'Ataque', 'Azufre'),
  ('zzz-soukaku', 'zenless-zone-zero', 'Soukaku', 'A', 'Hielo', 60, 'Buffer', 'Apoyo', 'Demonio tímido'),
  ('zzz-yanagi', 'zenless-zone-zero', 'Yanagi', 'S', 'Eléctrico', 60, 'DPS (DoT)', 'Anomalía', 'Tejetiempos'),
  ('zzz-zhu-yuan', 'zenless-zone-zero', 'Zhu Yuan', 'S', 'Etéreo', 60, 'DPS', 'Ataque', 'Pacificador antidisturbios VI');
