-- Ejecutar en Supabase → SQL Editor → New query → Run.
-- Requiere tier_lists.sql ya ejecutado.
--
-- Anade los tres modos de Honkai: Memory of Chaos, Pure Fiction y Apocalyptic
-- Shadow. Los ratings salen del payload de la propia pagina de Prydwen, donde
-- vienen los tres modos aunque en pantalla solo se pinte el seleccionado.
-- Verificado: el tier 0 de Memory of Chaos coincide exactamente con la rejilla
-- publicada.
--
-- Se puede repetir: reemplaza los tres modos de Honkai.

delete from public.tier_lists_oficial where game_id = 'honkai-star-rail';

insert into public.tier_lists_oficial (game_id, mode, character_id, rating) values
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-acheron', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-acheron', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-acheron', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-aglaea', 1.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-aglaea', 2),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-aglaea', 2),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-anaxa', 1),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-anaxa', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-anaxa', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-archer', 0),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-archer', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-archer', 0),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-argenti', 4),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-argenti', 2),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-argenti', 3),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-arlan', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-arlan', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-arlan', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-asta', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-asta', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-asta', 1.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-aventurine', 1.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-aventurine', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-aventurine', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-bailu', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-bailu', 3),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-bailu', 3),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-black-swan', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-black-swan', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-black-swan', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-blade', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-blade', 4),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-blade', 4),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-boothill', 2),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-boothill', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-boothill', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-bronya', 2),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-bronya', 2),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-bronya', 1.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-castorice', 0),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-castorice', 0),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-castorice', 0),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-cerydra', 1),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-cerydra', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-cerydra', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-cipher', 1),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-cipher', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-cipher', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-clara', 4),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-clara', 4),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-clara', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-cyrene', 0),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-cyrene', 0),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-cyrene', 0),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-dan-heng', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-dan-heng', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-dan-heng', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-imbibitor-lunae', 4),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-imbibitor-lunae', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-imbibitor-lunae', 4),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-permanser-terrae', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-permanser-terrae', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-permanser-terrae', 0),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-dr-ratio', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-dr-ratio', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-dr-ratio', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-feixiao', 1.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-feixiao', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-feixiao', 1.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-firefly', 0),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-firefly', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-firefly', 0),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-fu-xuan', 1),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-fu-xuan', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-fu-xuan', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-gallagher', 1.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-gallagher', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-gallagher', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-gepard', 4),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-gepard', 4),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-gepard', 4),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-gilgamesh', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-gilgamesh', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-gilgamesh', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-guinaifen', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-guinaifen', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-guinaifen', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-hanya', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-hanya', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-hanya', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-herta', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-herta', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-herta', 2),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-himeko', 4),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-himeko', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-himeko', 3),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-hook', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-hook', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-hook', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-huohuo', 0),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-huohuo', 0),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-huohuo', 0),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-hyacine', 0),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-hyacine', 0),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-hyacine', 0),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-hysilens', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-hysilens', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-hysilens', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-jade', 2),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-jade', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-jade', 1.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-jiaoqiu', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-jiaoqiu', 3),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-jiaoqiu', 2),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-jing-yuan', 4),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-jing-yuan', 4),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-jing-yuan', 3),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-jingliu', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-jingliu', 4),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-jingliu', 4),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-kafka', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-kafka', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-kafka', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-lingsha', 1),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-lingsha', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-lingsha', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-luka', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-luka', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-luka', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-luocha', 2),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-luocha', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-luocha', 1.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-lynx', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-lynx', 3),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-lynx', 3),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-march-7th', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-march-7th', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-march-7th', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-misha', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-misha', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-misha', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-moze', 4),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-moze', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-moze', 4),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-mydei', 1.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-mydei', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-mydei', 1.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-natasha', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-natasha', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-natasha', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-pela', 4),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-pela', 4),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-pela', 4),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-phainon', 1),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-phainon', 2),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-phainon', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-qingque', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-qingque', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-qingque', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-rappa', 2),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-rappa', 2),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-rappa', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-rin-tohsaka', 0),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-rin-tohsaka', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-rin-tohsaka', 0),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-robin', 1.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-robin', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-robin', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-ruan-mei', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-ruan-mei', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-ruan-mei', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-saber', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-saber', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-saber', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-sampo', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-sampo', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-sampo', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-seele', 2),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-seele', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-seele', 1.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-serval', 4),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-serval', 4),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-serval', 4),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-silver-wolf', 1),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-silver-wolf', 3),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-silver-wolf', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-sparkle', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-sparkle', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-sparkle', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-sunday', 1),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-sunday', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-sunday', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-sushang', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-sushang', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-sushang', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-the-herta', 1.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-the-herta', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-the-herta', 1.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-tingyun', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-tingyun', 3),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-tingyun', 2),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-fugue', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-fugue', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-fugue', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-topaz', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-topaz', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-topaz', 3),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-trazacaminos-fisico', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-trazacaminos-fisico', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-trazacaminos-fisico', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-trazacaminos-imaginario', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-trazacaminos-imaginario', 1.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-trazacaminos-imaginario', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-trazacaminos-fuego', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-trazacaminos-fuego', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-trazacaminos-fuego', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-trazacaminos-hielo', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-trazacaminos-hielo', 0.5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-trazacaminos-hielo', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-tribbie', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-tribbie', 0),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-tribbie', 0.5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-welt', 0.5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-welt', 1),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-welt', 1),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-xueyi', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-xueyi', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-xueyi', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-yanqing', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-yanqing', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-yanqing', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-yukong', 5),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-yukong', 5),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-yukong', 5),
  ('honkai-star-rail', 'Memory of Chaos', 'hsr-yunli', 3),
  ('honkai-star-rail', 'Pure Fiction', 'hsr-yunli', 4),
  ('honkai-star-rail', 'Apocalyptic Shadow', 'hsr-yunli', 4)
on conflict (game_id, mode, character_id) do nothing;
