-- Ejecutar en Supabase → SQL Editor → New query → Run.
-- Requiere umamusume.sql ya ejecutado.
--
-- Cartas de apoyo disponibles en la version Global. La wiki no publica una
-- lista global, asi que se comprobo ficha por ficha: una carta esta en Global
-- si su pagina indica "Initially released (EN)".
--
-- Se puede repetir: reemplaza las cartas de la version global.

delete from public.umamusume_support_cards where version = 'global';

insert into public.umamusume_support_cards (version, id, name, base_character, icon_url, rarity, bonus) values
  ('global', 'SSR_Silence_Suzuka_(Beyond_This_Shining_Moment)', 'Silence Suzuka (Beyond This Shining Moment)', 'Silence Suzuka', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30002_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Tokai_Teio_(Dream_Big!)', 'Tokai Teio (Dream Big!)', 'Tokai Teio', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30003_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Gold_City_(Run(my)way)', 'Gold City (Run(my)way)', 'Gold City', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30014_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Sakura_Bakushin_O_(Eat_Fast!_Yum_Fast!)', 'Sakura Bakushin O (Eat Fast! Yum Fast!)', 'Sakura Bakushin O', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30015_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Nishino_Flower_(Even_the_Littlest_Bud)', 'Nishino Flower (Even the Littlest Bud)', 'Nishino Flower', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30018_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Biko_Pegasus_(Double_Carrot_Punch!)', 'Biko Pegasus (Double Carrot Punch!)', 'Biko Pegasus', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30020_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Twin_Turbo_(Turbo_Booooost!)', 'Twin Turbo (Turbo Booooost!)', 'Twin Turbo', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30026_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Kitasan_Black_(Fire_at_My_Heels)', 'Kitasan Black (Fire at My Heels)', 'Kitasan Black', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30028_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Kawakami_Princess_(Princess_Bride)', 'Kawakami Princess (Princess Bride)', 'Kawakami Princess', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30039_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Sweep_Tosho_(It%27s_All_Mine!)', 'Sweep Tosho (It&#39;s All Mine!)', 'Sweep Tosho', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30045_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Taiki_Shuttle_(Hands_Up,_Crook!)', 'Taiki Shuttle (Hands Up, Crook!)', 'Taiki Shuttle', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30053_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Zenno_Rob_Roy_(Magical_Heroine)', 'Zenno Rob Roy (Magical Heroine)', 'Zenno Rob Roy', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30065_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Mayano_Top_Gun_(Party_Formation)', 'Mayano Top Gun (Party Formation)', 'Mayano Top Gun', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30072_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Matikanefukukitaru_(Touching_Sleeves_Is_Good_Luck!_%E2%99%AA)', 'Matikanefukukitaru (Touching Sleeves Is Good Luck! ♪)', 'Matikanefukukitaru', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30078_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Narita_Top_Road_(Peachy_Silhouette)', 'Narita Top Road (Peachy Silhouette)', 'Narita Top Road', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30086_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Seeking_the_Pearl_(Cheer_that_Changed_the_World)', 'Seeking the Pearl (Cheer that Changed the World)', 'Seeking the Pearl', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30095_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Agnes_Tachyon_(Q%E2%89%A00)', 'Agnes Tachyon (Q≠0)', 'Agnes Tachyon', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30101_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Maruzensky_(Sentimental_Flare_%E2%99%AA)', 'Maruzensky (Sentimental Flare ♪)', 'Maruzensky', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30107_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Daitaku_Helios_(Sunlit_Angel_%E2%99%AA)', 'Daitaku Helios (Sunlit Angel ♪)', 'Daitaku Helios', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30116_Card.png&width=128', 'SSR', 'Speed'),
  ('global', 'SSR_Gold_Ship_(Breakaway_Battleship)', 'Gold Ship (Breakaway Battleship)', 'Gold Ship', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30004_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Seiun_Sky_(Foolproof_Plan)', 'Seiun Sky (Foolproof Plan)', 'Seiun Sky', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30008_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Tamamo_Cross_(Split_the_Sky,_White_Lightning!)', 'Tamamo Cross (Split the Sky, White Lightning!)', 'Tamamo Cross', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30009_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Super_Creek_(Piece_of_Mind)', 'Super Creek (Piece of Mind)', 'Super Creek', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30016_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Satono_Diamond_(The_Will_to_Overtake)', 'Satono Diamond (The Will to Overtake)', 'Satono Diamond', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30029_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Sakura_Chiyono_O_(Peak_Sakura_Season)', 'Sakura Chiyono O (Peak Sakura Season)', 'Sakura Chiyono O', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30038_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Nakayama_Festa_(43,_8,_1)', 'Nakayama Festa (43, 8, 1)', 'Nakayama Festa', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30043_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Winning_Ticket_(Full-Blown_Tantrum)', 'Winning Ticket (Full-Blown Tantrum)', 'Winning Ticket', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30046_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Narita_Brian_(The_Whistling_Arrow%27s_Taunt)', 'Narita Brian (The Whistling Arrow&#39;s Taunt)', 'Narita Brian', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30069_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Manhattan_Cafe_(My_Solo_Spun_in_Spiraling_Runs)', 'Manhattan Cafe (My Solo Spun in Spiraling Runs)', 'Manhattan Cafe', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30075_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Symboli_Rudolf_(Encha%C3%AEnement)', 'Symboli Rudolf (Enchaînement)', 'Symboli Rudolf', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30090_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Ikuno_Dictus_(Beloved_Orchid_Bouquet)', 'Ikuno Dictus (Beloved Orchid Bouquet)', 'Ikuno Dictus', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30099_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Manhattan_Cafe_(It%27s_on_the_House)', 'Manhattan Cafe (It&#39;s on the House)', 'Manhattan Cafe', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30110_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Mejiro_Palmer_(Moonlit_Devil_%E2%99%AA)', 'Mejiro Palmer (Moonlit Devil ♪)', 'Mejiro Palmer', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30115_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Symboli_Kris_S_(A_Win_Foreshadowed)', 'Symboli Kris S (A Win Foreshadowed)', 'Symboli Kris S', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30118_Card.png&width=128', 'SSR', 'Stamina'),
  ('global', 'SSR_Vodka_(Wild_Rider)', 'Vodka (Wild Rider)', 'Vodka', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30005_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_El_Condor_Pasa_(Champion%27s_Passion)', 'El Condor Pasa (Champion&#39;s Passion)', 'El Condor Pasa', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30007_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Smart_Falcon_(My_Umadol_Way!_%E2%98%86)', 'Smart Falcon (My Umadol Way! ☆)', 'Smart Falcon', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30017_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Oguri_Cap_(Get_Lots_of_Hugs_for_Me)', 'Oguri Cap (Get Lots of Hugs for Me)', 'Oguri Cap', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30024_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Yaeno_Muteki_(Fiery_Discipline)', 'Yaeno Muteki (Fiery Discipline)', 'Yaeno Muteki', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30032_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Rice_Shower_(Happiness_Just_around_the_Bend)', 'Rice Shower (Happiness Just around the Bend)', 'Rice Shower', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30034_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Bamboo_Memory_(Head-on_Fight!)', 'Bamboo Memory (Head-on Fight!)', 'Bamboo Memory', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30042_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_King_Halo_(Tonight,_We_Waltz)', 'King Halo (Tonight, We Waltz)', 'King Halo', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30056_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Tamamo_Cross_(Beware!_Halloween_Night!)', 'Tamamo Cross (Beware! Halloween Night!)', 'Tamamo Cross', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30064_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Daitaku_Helios_(Make!_Some!_NOISE)', 'Daitaku Helios (Make! Some! NOISE)', 'Daitaku Helios', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30071_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Admire_Vega_(Lucky_Star_in_the_Sky)', 'Admire Vega (Lucky Star in the Sky)', 'Admire Vega', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30077_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Agnes_Digital_(A_Fan%27s_Joy)', 'Agnes Digital (A Fan&#39;s Joy)', 'Agnes Digital', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30085_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Daiwa_Scarlet_(Number_1_Outfit)', 'Daiwa Scarlet (Number 1 Outfit)', 'Daiwa Scarlet', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30093_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Haru_Urara_(Sunny_Passion_%E2%99%AA)', 'Haru Urara (Sunny Passion ♪)', 'Haru Urara', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30098_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Air_Groove_(%E7%90%86%E6%83%B3%E3%81%B8%E5%90%91%E3%81%8B%E3%81%86%E9%9D%92%E5%B5%90)', 'Air Groove (理想へ向かう青嵐)', 'Air Groove', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30106_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Daiichi_Ruby_(Ah,_Such_Majesty)', 'Daiichi Ruby (Ah, Such Majesty)', 'Daiichi Ruby', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30114_Card.png&width=128', 'SSR', 'Power'),
  ('global', 'SSR_Special_Week_(The_Brightest_Star_in_Japan!)', 'Special Week (The Brightest Star in Japan!)', 'Special Week', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30001_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Grass_Wonder_(Fairest_Fleur)', 'Grass Wonder (Fairest Fleur)', 'Grass Wonder', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30006_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Ines_Fujin_(Watch_My_Star_Fly!)', 'Ines Fujin (Watch My Star Fly!)', 'Ines Fujin', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30011_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Winning_Ticket_(BNWinner!)', 'Winning Ticket (BNWinner!)', 'Winning Ticket', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30012_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Mejiro_Palmer_(Go_Ahead_and_Laugh)', 'Mejiro Palmer (Go Ahead and Laugh)', 'Mejiro Palmer', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30027_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Hishi_Akebono_(Who_Wants_the_First_Bite%3F)', 'Hishi Akebono (Who Wants the First Bite?)', 'Hishi Akebono', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30040_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Mejiro_Ryan_(Winning_Pitch)', 'Mejiro Ryan (Winning Pitch)', 'Mejiro Ryan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30048_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Ikuno_Dictus_(Warm_Heart,_Soft_Steps)', 'Ikuno Dictus (Warm Heart, Soft Steps)', 'Ikuno Dictus', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30063_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Sakura_Bakushin_O_(Super!_Sonic!_Flower_Power!)', 'Sakura Bakushin O (Super! Sonic! Flower Power!)', 'Sakura Bakushin O', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30083_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Marvelous_Sunday_(A_MORE_MARVELOUS_WORLD!_%E2%98%86)', 'Marvelous Sunday (A MORE MARVELOUS WORLD! ☆)', 'Marvelous Sunday', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30089_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Bamboo_Memory_(Make_These_Feelings_Reach_You!)', 'Bamboo Memory (Make These Feelings Reach You!)', 'Bamboo Memory', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30094_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_El_Condor_Pasa_(Twinkle_in_Your_Eyes_%E2%88%9E)', 'El Condor Pasa (Twinkle in Your Eyes ∞)', 'El Condor Pasa', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30102_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Twin_Turbo_(TT_Ignition!)', 'Twin Turbo (TT Ignition!)', 'Twin Turbo', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30112_Card.png&width=128', 'SSR', 'Guts'),
  ('global', 'SSR_Fine_Motion_(Wave_of_Gratitude)', 'Fine Motion (Wave of Gratitude)', 'Fine Motion', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30010_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Air_Shakur_(7_More_Centimeters)', 'Air Shakur (7 More Centimeters)', 'Air Shakur', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30013_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Yukino_Bijin_(Hometown_Cheers)', 'Yukino Bijin (Hometown Cheers)', 'Yukino Bijin', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30031_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Nice_Nature_(Daring_to_Dream)', 'Nice Nature (Daring to Dream)', 'Nice Nature', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30054_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Seiun_Sky_(Paint_the_Sky_Red)', 'Seiun Sky (Paint the Sky Red)', 'Seiun Sky', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30055_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Curren_Chan_(Cutie_Pie_with_Shining_Eyes)', 'Curren Chan (Cutie Pie with Shining Eyes)', 'Curren Chan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30068_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Narita_Taishin_(Strict_Shopper)', 'Narita Taishin (Strict Shopper)', 'Narita Taishin', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30073_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Nishino_Flower_(Little_Cupcakes,_Big_Emotions)', 'Nishino Flower (Little Cupcakes, Big Emotions)', 'Nishino Flower', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30082_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Sirius_Symboli_(Escorte_%C3%89toile)', 'Sirius Symboli (Escorte Étoile)', 'Sirius Symboli', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30091_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Mr._C.B._(Dear_Mr._C.B.)', 'Mr. C.B. (Dear Mr. C.B.)', 'Mr. C.B.', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30097_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Matikanetannhauser_(Machitan%E2%98%86Adventure)', 'Matikanetannhauser (Machitan☆Adventure)', 'Matikanetannhauser', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30103_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Nakayama_Festa_(Trusting_the_Dice)', 'Nakayama Festa (Trusting the Dice)', 'Nakayama Festa', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30108_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Tokai_Teio_(Teio-Oo-Oo!!!)', 'Tokai Teio (Teio-Oo-Oo!!!)', 'Tokai Teio', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30111_Card.png&width=128', 'SSR', 'Wit'),
  ('global', 'SSR_Tazuna_Hayakawa_(Tracen_Reception)', 'Tazuna Hayakawa (Tracen Reception)', 'Tazuna Hayakawa', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30021_Card.png&width=128', 'SSR', 'Pal'),
  ('global', 'SSR_Kashimoto_Riko_(Planned_Perfection)', 'Kashimoto Riko (Planned Perfection)', 'Kashimoto Riko', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30036_Card.png&width=128', 'SSR', 'Pal'),
  ('global', 'SSR_Light_Hello_(From_the_Ground_Up)', 'Light Hello (From the Ground Up)', 'Light Hello', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30052_Card.png&width=128', 'SSR', 'Pal'),
  ('global', 'SSR_Anshinzawa_Sasami_(%E3%83%96%E3%82%B9%E3%83%83%E3%81%A8%E3%81%84%E3%81%A3%E3%81%A8%E3%81%8F%EF%BC%9F)', 'Anshinzawa Sasami (ブスッといっとく？)', 'Anshinzawa Sasami', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30080_Card.png&width=128', 'SSR', 'Pal'),
  ('global', 'SSR_Heirs_to_the_Throne_(Esteemed_and_Adored)', 'Heirs to the Throne (Esteemed and Adored)', 'Heirs to the Throne', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_30067_Card.png&width=128', 'SSR', 'Group'),
  ('global', 'SR_Narita_Taishin_(Poolside_High_Tides)', 'Narita Taishin (Poolside High Tides)', 'Narita Taishin', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20014_Card.png&width=128', 'SR', 'Speed'),
  ('global', 'SR_King_Halo_(First-Rate_Plan)', 'King Halo (First-Rate Plan)', 'King Halo', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20020_Card.png&width=128', 'SR', 'Speed'),
  ('global', 'SR_Sweep_Tosho_(Lamplit_Training_of_a_Witch-to-Be)', 'Sweep Tosho (Lamplit Training of a Witch-to-Be)', 'Sweep Tosho', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20023_Card.png&width=128', 'SR', 'Speed'),
  ('global', 'SR_El_Condor_Pasa_(Mud-Caked_Compa%C3%B1ero)', 'El Condor Pasa (Mud-Caked Compañero)', 'El Condor Pasa', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20033_Card.png&width=128', 'SR', 'Speed'),
  ('global', 'SR_Vodka_(An_Annoying_Supervisor)', 'Vodka (An Annoying Supervisor)', 'Vodka', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20039_Card.png&width=128', 'SR', 'Speed'),
  ('global', 'SR_Curren_Chan_(Cozy_Cute_Memory_%E2%99%AA)', 'Curren Chan (Cozy Cute Memory ♪)', 'Curren Chan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20044_Card.png&width=128', 'SR', 'Speed'),
  ('global', 'SR_Mayano_Top_Gun_(Cute_%2B_Cute_%3D_%3F)', 'Mayano Top Gun (Cute + Cute = ?)', 'Mayano Top Gun', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20007_Card.png&width=128', 'SR', 'Stamina'),
  ('global', 'SR_Manhattan_Cafe_(My_Solo_Drawn_to_Raindrop_Drums)', 'Manhattan Cafe (My Solo Drawn to Raindrop Drums)', 'Manhattan Cafe', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20008_Card.png&width=128', 'SR', 'Stamina'),
  ('global', 'SR_Zenno_Rob_Roy_(The_Perfect_Book_for_You)', 'Zenno Rob Roy (The Perfect Book for You)', 'Zenno Rob Roy', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20028_Card.png&width=128', 'SR', 'Stamina'),
  ('global', 'SR_Tosen_Jordan_(Turf_as_Nails)', 'Tosen Jordan (Turf as Nails)', 'Tosen Jordan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20035_Card.png&width=128', 'SR', 'Stamina'),
  ('global', 'SR_Mejiro_Ryan_(Hot_Hearts_and_Cool_Drinks)', 'Mejiro Ryan (Hot Hearts and Cool Drinks)', 'Mejiro Ryan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20040_Card.png&width=128', 'SR', 'Stamina'),
  ('global', 'SR_Tokai_Teio_(Step!_Smile!_Wink!)', 'Tokai Teio (Step! Smile! Wink!)', 'Tokai Teio', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20047_Card.png&width=128', 'SR', 'Stamina'),
  ('global', 'SR_Hishi_Amazon_(Reach_the_Top!)', 'Hishi Amazon (Reach the Top!)', 'Hishi Amazon', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20003_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Agnes_Digital_(Digital%27s_Recharge_Station)', 'Agnes Digital (Digital&#39;s Recharge Station)', 'Agnes Digital', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20005_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Biwa_Hayahide_(Trial_Initiation)', 'Biwa Hayahide (Trial Initiation)', 'Biwa Hayahide', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20006_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Mihono_Bourbon_(Pal-Assisted_Training)', 'Mihono Bourbon (Pal-Assisted Training)', 'Mihono Bourbon', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20009_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Mejiro_Ryan_(On_and_Off_the_Court)', 'Mejiro Ryan (On and Off the Court)', 'Mejiro Ryan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20010_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Daitaku_Helios_(Let%27s_Get_This_Party_Lit!)', 'Daitaku Helios (Let&#39;s Get This Party Lit!)', 'Daitaku Helios', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20024_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Nishino_Flower_(Lifting_Your_Spirits)', 'Nishino Flower (Lifting Your Spirits)', 'Nishino Flower', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20027_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Inari_One_(Laughing_through_the_Mud)', 'Inari One (Laughing through the Mud)', 'Inari One', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20032_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Fine_Motion_(Grma,_Ramen_%E2%99%AA)', 'Fine Motion (Grma, Ramen ♪)', 'Fine Motion', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20037_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Sakura_Bakushin_O_(The_Perfect_Morning_Greeting!)', 'Sakura Bakushin O (The Perfect Morning Greeting!)', 'Sakura Bakushin O', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20042_Card.png&width=128', 'SR', 'Power'),
  ('global', 'SR_Air_Groove_(Nothing_Escapes_the_Vice_Prez)', 'Air Groove (Nothing Escapes the Vice Prez)', 'Air Groove', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20004_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Yukino_Bijin_(City_Girl_101)', 'Yukino Bijin (City Girl 101)', 'Yukino Bijin', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20011_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Meisho_Doto_(Fighting_for_Fortune)', 'Meisho Doto (Fighting for Fortune)', 'Meisho Doto', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20017_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Nice_Nature_(It%27s_Just_Water)', 'Nice Nature (It&#39;s Just Water)', 'Nice Nature', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20019_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Tamamo_Cross_(Now_Dat%27s_What_I_Call_Grilled_Squid!)', 'Tamamo Cross (Now Dat&#39;s What I Call Grilled Squid!)', 'Tamamo Cross', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20022_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Seeking_the_Pearl_(The_World%27s_My_Oyster)', 'Seeking the Pearl (The World&#39;s My Oyster)', 'Seeking the Pearl', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20029_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Sirius_Symboli_(The_Brightest_Star_Shines_On)', 'Sirius Symboli (The Brightest Star Shines On)', 'Sirius Symboli', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20038_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Admire_Vega_(Aim_for_the_Brightest)', 'Admire Vega (Aim for the Brightest)', 'Admire Vega', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20041_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Oguri_Cap_(I_Love_You..._Dear_Food)', 'Oguri Cap (I Love You... Dear Food)', 'Oguri Cap', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20048_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_K.S.Miracle_(The_3rd_MIRACLE)', 'K.S.Miracle (The 3rd MIRACLE)', 'K.S.Miracle', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20051_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Tsurumaru_Tsuyoshi_(Go,_Go!_Tsuyoshi!)', 'Tsurumaru Tsuyoshi (Go, Go! Tsuyoshi!)', 'Tsurumaru Tsuyoshi', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20052_Card.png&width=128', 'SR', 'Guts'),
  ('global', 'SR_Fuji_Kiseki_(Well,_Look_Who%27s_Home)', 'Fuji Kiseki (Well, Look Who&#39;s Home)', 'Fuji Kiseki', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20001_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Daiwa_Scarlet_(Nothing_Hard_Work_Can%27t_Solve!)', 'Daiwa Scarlet (Nothing Hard Work Can&#39;t Solve!)', 'Daiwa Scarlet', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20002_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Agnes_Tachyon_(Experimental_Studies_on_Subject_A)', 'Agnes Tachyon (Experimental Studies on Subject A)', 'Agnes Tachyon', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20012_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Marvelous_Sunday_(A_Marvelous_%E2%98%86_Plan)', 'Marvelous Sunday (A Marvelous ☆ Plan)', 'Marvelous Sunday', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20015_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Matikanefukukitaru_(Fate%27s_Forecast)', 'Matikanefukukitaru (Fate&#39;s Forecast)', 'Matikanefukukitaru', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20016_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Mejiro_Dober_(Ignore_the_Stares)', 'Mejiro Dober (Ignore the Stares)', 'Mejiro Dober', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20018_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Ikuno_Dictus_(Never_Skip_Warm-Ups)', 'Ikuno Dictus (Never Skip Warm-Ups)', 'Ikuno Dictus', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20025_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Ines_Fujin_(You_Earned_It!)', 'Ines Fujin (You Earned It!)', 'Ines Fujin', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20030_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Mejiro_Ardan_(My_Heart_Will_Go_On)', 'Mejiro Ardan (My Heart Will Go On)', 'Mejiro Ardan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20034_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Sweep_Tosho_(Reckless_Witch_Training)', 'Sweep Tosho (Reckless Witch Training)', 'Sweep Tosho', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20046_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Gold_City_(Going_for_Gold)', 'Gold City (Going for Gold)', 'Gold City', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20049_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Seiun_Sky_(Bobbing_with_the_Waves)', 'Seiun Sky (Bobbing with the Waves)', 'Seiun Sky', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20050_Card.png&width=128', 'SR', 'Wit'),
  ('global', 'SR_Kiryuin_Aoi_(Trainers%27_Teamwork)', 'Kiryuin Aoi (Trainers&#39; Teamwork)', 'Kiryuin Aoi', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_20021_Card.png&width=128', 'SR', 'Pal'),
  ('global', 'R_Silence_Suzuka_(Tracen_Academy)', 'Silence Suzuka (Tracen Academy)', 'Silence Suzuka', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10002_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Tokai_Teio_(Tracen_Academy)', 'Tokai Teio (Tracen Academy)', 'Tokai Teio', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10003_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Maruzensky_(Tracen_Academy)', 'Maruzensky (Tracen Academy)', 'Maruzensky', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10004_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Taiki_Shuttle_(Tracen_Academy)', 'Taiki Shuttle (Tracen Academy)', 'Taiki Shuttle', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10008_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Gold_City_(Tracen_Academy)', 'Gold City (Tracen Academy)', 'Gold City', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10017_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Sakura_Bakushin_O_(Tracen_Academy)', 'Sakura Bakushin O (Tracen Academy)', 'Sakura Bakushin O', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10018_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Eishin_Flash_(Tracen_Academy)', 'Eishin Flash (Tracen Academy)', 'Eishin Flash', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10038_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Narita_Taishin_(Tracen_Academy)', 'Narita Taishin (Tracen Academy)', 'Narita Taishin', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10040_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Nishino_Flower_(Tracen_Academy)', 'Nishino Flower (Tracen Academy)', 'Nishino Flower', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10041_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Biko_Pegasus_(Tracen_Academy)', 'Biko Pegasus (Tracen Academy)', 'Biko Pegasus', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10042_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_King_Halo_(Tracen_Academy)', 'King Halo (Tracen Academy)', 'King Halo', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10048_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Sweep_Tosho_(Tracen_Academy)', 'Sweep Tosho (Tracen Academy)', 'Sweep Tosho', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10050_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Twin_Turbo_(Tracen_Academy)', 'Twin Turbo (Tracen Academy)', 'Twin Turbo', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10051_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Kitasan_Black_(Tracen_Academy)', 'Kitasan Black (Tracen Academy)', 'Kitasan Black', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10055_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Kawakami_Princess_(Tracen_Academy)', 'Kawakami Princess (Tracen Academy)', 'Kawakami Princess', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10063_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Shinko_Windy_(Tracen_Academy)', 'Shinko Windy (Tracen Academy)', 'Shinko Windy', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10066_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Narita_Brian_(Tracen_Academy)', 'Narita Brian (Tracen Academy)', 'Narita Brian', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10072_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Narita_Top_Road_(Tracen_Academy)', 'Narita Top Road (Tracen Academy)', 'Narita Top Road', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10077_Card.png&width=128', 'R', 'Speed'),
  ('global', 'R_Gold_Ship_(Tracen_Academy)', 'Gold Ship (Tracen Academy)', 'Gold Ship', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10006_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Mejiro_McQueen_(Tracen_Academy)', 'Mejiro McQueen (Tracen Academy)', 'Mejiro McQueen', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10010_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_T.M._Opera_O_(Tracen_Academy)', 'T.M. Opera O (Tracen Academy)', 'T.M. Opera O', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10012_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Seiun_Sky_(Tracen_Academy)', 'Seiun Sky (Tracen Academy)', 'Seiun Sky', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10014_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Rice_Shower_(Tracen_Academy)', 'Rice Shower (Tracen Academy)', 'Rice Shower', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10015_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Super_Creek_(Tracen_Academy)', 'Super Creek (Tracen Academy)', 'Super Creek', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10019_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Tamamo_Cross_(Tracen_Academy)', 'Tamamo Cross (Tracen Academy)', 'Tamamo Cross', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10027_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Mayano_Top_Gun_(Tracen_Academy)', 'Mayano Top Gun (Tracen Academy)', 'Mayano Top Gun', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10030_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Manhattan_Cafe_(Tracen_Academy)', 'Manhattan Cafe (Tracen Academy)', 'Manhattan Cafe', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10031_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Satono_Diamond_(Tracen_Academy)', 'Satono Diamond (Tracen Academy)', 'Satono Diamond', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10056_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Zenno_Rob_Roy_(Tracen_Academy)', 'Zenno Rob Roy (Tracen Academy)', 'Zenno Rob Roy', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10059_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Sakura_Chiyono_O_(Tracen_Academy)', 'Sakura Chiyono O (Tracen Academy)', 'Sakura Chiyono O', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10062_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Nakayama_Festa_(Tracen_Academy)', 'Nakayama Festa (Tracen Academy)', 'Nakayama Festa', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10067_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Tosen_Jordan_(Tracen_Academy)', 'Tosen Jordan (Tracen Academy)', 'Tosen Jordan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10070_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Mejiro_Bright_(Tracen_Academy)', 'Mejiro Bright (Tracen Academy)', 'Mejiro Bright', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10076_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Symboli_Kris_S_(Tracen_Academy)', 'Symboli Kris S (Tracen Academy)', 'Symboli Kris S', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10082_Card.png&width=128', 'R', 'Stamina'),
  ('global', 'R_Oguri_Cap_(Tracen_Academy)', 'Oguri Cap (Tracen Academy)', 'Oguri Cap', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10005_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Vodka_(Tracen_Academy)', 'Vodka (Tracen Academy)', 'Vodka', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10007_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_El_Condor_Pasa_(Tracen_Academy)', 'El Condor Pasa (Tracen Academy)', 'El Condor Pasa', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10011_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Hishi_Amazon_(Tracen_Academy)', 'Hishi Amazon (Tracen Academy)', 'Hishi Amazon', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10024_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Agnes_Digital_(Tracen_Academy)', 'Agnes Digital (Tracen Academy)', 'Agnes Digital', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10026_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Biwa_Hayahide_(Tracen_Academy)', 'Biwa Hayahide (Tracen Academy)', 'Biwa Hayahide', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10029_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Mihono_Bourbon_(Tracen_Academy)', 'Mihono Bourbon (Tracen Academy)', 'Mihono Bourbon', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10032_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Mejiro_Ryan_(Tracen_Academy)', 'Mejiro Ryan (Tracen Academy)', 'Mejiro Ryan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10033_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Smart_Falcon_(Tracen_Academy)', 'Smart Falcon (Tracen Academy)', 'Smart Falcon', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10039_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Daitaku_Helios_(Tracen_Academy)', 'Daitaku Helios (Tracen Academy)', 'Daitaku Helios', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10052_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Yaeno_Muteki_(Tracen_Academy)', 'Yaeno Muteki (Tracen Academy)', 'Yaeno Muteki', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10058_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Bamboo_Memory_(Tracen_Academy)', 'Bamboo Memory (Tracen Academy)', 'Bamboo Memory', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10065_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Inari_One_(Tracen_Academy)', 'Inari One (Tracen Academy)', 'Inari One', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10068_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Admire_Vega_(Tracen_Academy)', 'Admire Vega (Tracen Academy)', 'Admire Vega', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10075_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Daiichi_Ruby_(Tracen_Academy)', 'Daiichi Ruby (Tracen Academy)', 'Daiichi Ruby', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10079_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Tanino_Gimlet_(Tracen_Academy)', 'Tanino Gimlet (Tracen Academy)', 'Tanino Gimlet', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10084_Card.png&width=128', 'R', 'Power'),
  ('global', 'R_Special_Week_(Tracen_Academy)', 'Special Week (Tracen Academy)', 'Special Week', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10001_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Grass_Wonder_(Tracen_Academy)', 'Grass Wonder (Tracen Academy)', 'Grass Wonder', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10009_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Winning_Ticket_(Tracen_Academy)', 'Winning Ticket (Tracen Academy)', 'Winning Ticket', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10016_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Haru_Urara_(Tracen_Academy)', 'Haru Urara (Tracen Academy)', 'Haru Urara', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10020_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Air_Groove_(Tracen_Academy)', 'Air Groove (Tracen Academy)', 'Air Groove', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10025_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Yukino_Bijin_(Tracen_Academy)', 'Yukino Bijin (Tracen Academy)', 'Yukino Bijin', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10034_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Ines_Fujin_(Tracen_Academy)', 'Ines Fujin (Tracen Academy)', 'Ines Fujin', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10035_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Meisho_Doto_(Tracen_Academy)', 'Meisho Doto (Tracen Academy)', 'Meisho Doto', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10045_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Nice_Nature_(Tracen_Academy)', 'Nice Nature (Tracen Academy)', 'Nice Nature', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10047_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Mejiro_Palmer_(Tracen_Academy)', 'Mejiro Palmer (Tracen Academy)', 'Mejiro Palmer', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10054_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Matikanetannhauser_(Tracen_Academy)', 'Matikanetannhauser (Tracen Academy)', 'Matikanetannhauser', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10057_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Seeking_the_Pearl_(Tracen_Academy)', 'Seeking the Pearl (Tracen Academy)', 'Seeking the Pearl', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10061_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Hishi_Akebono_(Tracen_Academy)', 'Hishi Akebono (Tracen Academy)', 'Hishi Akebono', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10064_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Sirius_Symboli_(Tracen_Academy)', 'Sirius Symboli (Tracen Academy)', 'Sirius Symboli', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10071_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_K.S.Miracle_(Tracen_Academy)', 'K.S.Miracle (Tracen Academy)', 'K.S.Miracle', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10080_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Tsurumaru_Tsuyoshi_(Tracen_Academy)', 'Tsurumaru Tsuyoshi (Tracen Academy)', 'Tsurumaru Tsuyoshi', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10081_Card.png&width=128', 'R', 'Guts'),
  ('global', 'R_Symboli_Rudolf_(Tracen_Academy)', 'Symboli Rudolf (Tracen Academy)', 'Symboli Rudolf', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10013_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Daiwa_Scarlet_(Tracen_Academy)', 'Daiwa Scarlet (Tracen Academy)', 'Daiwa Scarlet', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10023_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Fine_Motion_(Tracen_Academy)', 'Fine Motion (Tracen Academy)', 'Fine Motion', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10028_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Agnes_Tachyon_(Tracen_Academy)', 'Agnes Tachyon (Tracen Academy)', 'Agnes Tachyon', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10036_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Air_Shakur_(Tracen_Academy)', 'Air Shakur (Tracen Academy)', 'Air Shakur', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10037_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Marvelous_Sunday_(Tracen_Academy)', 'Marvelous Sunday (Tracen Academy)', 'Marvelous Sunday', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10043_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Matikanefukukitaru_(Tracen_Academy)', 'Matikanefukukitaru (Tracen Academy)', 'Matikanefukukitaru', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10044_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Mejiro_Dober_(Tracen_Academy)', 'Mejiro Dober (Tracen Academy)', 'Mejiro Dober', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10046_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Fuji_Kiseki_(Tracen_Academy)', 'Fuji Kiseki (Tracen Academy)', 'Fuji Kiseki', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10049_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Ikuno_Dictus_(Tracen_Academy)', 'Ikuno Dictus (Tracen Academy)', 'Ikuno Dictus', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10053_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Mejiro_Ardan_(Tracen_Academy)', 'Mejiro Ardan (Tracen Academy)', 'Mejiro Ardan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10069_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Curren_Chan_(Tracen_Academy)', 'Curren Chan (Tracen Academy)', 'Curren Chan', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10073_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Mr._C.B._(Tracen_Academy)', 'Mr. C.B. (Tracen Academy)', 'Mr. C.B.', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10078_Card.png&width=128', 'R', 'Wit'),
  ('global', 'R_Tazuna_Hayakawa_(Tracen_Academy)', 'Tazuna Hayakawa (Tracen Academy)', 'Tazuna Hayakawa', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10021_Card.png&width=128', 'R', 'Pal'),
  ('global', 'R_Kiryuin_Aoi_(Tracen_Academy)', 'Kiryuin Aoi (Tracen Academy)', 'Kiryuin Aoi', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10022_Card.png&width=128', 'R', 'Pal'),
  ('global', 'R_Kashimoto_Riko_(Tracen_Academy)', 'Kashimoto Riko (Tracen Academy)', 'Kashimoto Riko', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10060_Card.png&width=128', 'R', 'Pal'),
  ('global', 'R_Anshinzawa_Sasami_(Acupuncturist)', 'Anshinzawa Sasami (Acupuncturist)', 'Anshinzawa Sasami', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10074_Card.png&width=128', 'R', 'Pal'),
  ('global', 'R_Light_Hello_(Event_Producer)', 'Light Hello (Event Producer)', 'Light Hello', 'https://umamusu.wiki/w/thumb.php?f=Support_Card_10083_Card.png&width=128', 'R', 'Pal');
