-- Ejecutar en Supabase -> SQL Editor -> New query -> Run.
--
-- Pistas de disco (Drive Discs) de Zenless Zone Zero: los 30 conjuntos.
--
-- No son armas, asi que van en su propia tabla: en vez de stats y pasiva tienen
-- un efecto al llevar 2 piezas y otro al llevar 4, y cada una de sus 6 ranuras
-- solo puede tener ciertas stats principales.
--
-- Fuentes:
--   HoYoWiki, la wiki oficial de HoYoverse -> nombre, icono, grados y efectos
--     de 2 y 4 piezas, en espanol oficial.
--   Wiki de Zenless (Fandom) -> la mision de Limpieza rutinaria en la que se
--     farmea cada conjunto. El nombre de la mision se queda en ingles.
--
-- Las stats principales de cada ranura son las mismas en todos los conjuntos
-- (lo confirma la pagina "Drive Disc" de la wiki), asi que van con una tabla
-- comun: HoYoWiki las escribia de cuatro formas y en dos discos le faltaban.
--
-- Generado el 2026-09-11.

create table if not exists public.drive_discs (
  id text primary key,
  game_id text not null,
  name text not null,
  name_en text,
  image_url text,
  -- Grados en los que sale el conjunto: "B,A,S" o solo "S".
  grades text,
  version text,
  two_piece text,
  four_piece text,
  -- Stats principales que pueden salir en cada ranura, de la 1 a la 6.
  main_stats jsonb,
  how_to_get text,
  updated_at timestamptz not null default now()
);

create index if not exists drive_discs_game_idx on public.drive_discs (game_id, name);

alter table public.drive_discs enable row level security;

drop policy if exists "Los discos se pueden consultar" on public.drive_discs;
create policy "Los discos se pueden consultar"
  on public.drive_discs for select
  using (true);

drop policy if exists "Los admins crean discos" on public.drive_discs;
create policy "Los admins crean discos"
  on public.drive_discs for insert
  with check (public.is_admin());

drop policy if exists "Los admins editan discos" on public.drive_discs;
create policy "Los admins editan discos"
  on public.drive_discs for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Los admins borran discos" on public.drive_discs;
create policy "Los admins borran discos"
  on public.drive_discs for delete
  using (public.is_admin());

insert into public.drive_discs (
  id, game_id, name, name_en, image_url, grades, version, two_piece, four_piece,
  main_stats, how_to_get
)
values
  ('zzz-disc-993', 'zenless-zone-zero', 'Aria radiante', 'Shining Aria', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2025/12/30/19629685/6d165e695769274d3a1ffd9ef9890d13_25360245106479120.png', 'B,A,S', '2.5', 'Daño etéreo +10%.', 'Cuando el portador golpea a un enemigo con el ataque normal, su Maestría de Anomalía aumenta en 36 ptos. durante 8 s. La duración se reinicia con cada activación. Al provocar Aturdimiento sobre un enemigo en el campo de batalla, el daño infligido por el portador aumenta en un 25 % durante 18 s. La duración se reinicia con cada activación.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Deceits and Bulwarks» · Se compran a Roland y Elfy'),
  ('zzz-disc-625', 'zenless-zone-zero', 'Armonía umbría', 'Shadow Harmony', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2025/09/05/15884296/df1b8e9153a4ca865d0b3efd0109bd06_2037926335425882207.gif', 'B,A,S', '1.6', 'El daño infligido por la réplica y el ataque rápido aumenta en un 15 %.', 'Al golpear a un enemigo con una réplica o un ataque rápido, si el daño infligido es del mismo atributo que el del portador, obtiene 1 carga de bonificación. Puede activarse un máximo de una vez por cada habilidad. Por cada carga de bonificación, el Ataque y la Probabilidad de Crítico del portador aumentan en un 4 % y un 4 % respectivamente durante 15 s. Pueden acumularse hasta 3 cargas. La duración se reinicia con cada activación.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Gunslinger vs Guardian» · Se compran a Roland y Elfy'),
  ('zzz-disc-992', 'zenless-zone-zero', 'Balada de aguas blancas', 'White Water Ballad', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2025/12/30/19629685/2467e415780b5f1b5c7ca57b91577dc5_7172534532741595451.png', 'B,A,S', '2.5', 'Daño físico +10%.', 'Cuando el portador se encuentra en cualquier velo etéreo, su Probabilidad de Critico aumenta en un 10%. Tras salir de velo etéreo, este efecto se prolonga durante 15 s. Si el portador es un personaje atacante, al activar o extender velo etéreo, la Probabilidad de Critico aumenta en un 10 % y el Ataque aumenta en un 10% durante 30 s. La duración se reinicia con cada activación.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Deceits and Bulwarks» · Se compran a Roland y Elfy'),
  ('zzz-disc-547', 'zenless-zone-zero', 'Balada de la rama y la espada', 'Branch & Blade Song', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2024/12/25/19629685/2ef493e0fe25c73faf761cb991d9920f_1083995100362607031.png', 'S', '1.4', 'Daño Crítico +16 %.', 'Si la Tasa de Anomalía es igual o mayor a 115 ptos., el Daño Crítico del portador aumenta en un 30 %. Cuando cualquier miembro del equipo provoca congelación o ruptura de hielo sobre un enemigo, la Probabilidad de Crítico del portador aumenta en un 12 % durante 15 s.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Monster Duet» · Se compran a Roland y Elfy'),
  ('zzz-disc-130', 'zenless-zone-zero', 'Blues libre', 'Freedom Blues', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/ec6bd15b507c13de9ed3dfe331893b03_7048380845230519712.png', 'B,A,S', '1.0', 'Aumenta la Maestría de Anomalía en 30 ptos.', 'Al golpear al enemigo con una técnica especial EX, reduce su resistencia a la Anomalía de Atributo correspondiente en un 20 % durante 8 s. No se acumula con efectos del mismo tipo.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Sharp Fang and Blunt Axe» · Se compran a Roland y Elfy'),
  ('zzz-disc-1069', 'zenless-zone-zero', 'Conejo en el país de las maravillas', 'Bunny in Wonderland', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2026/03/23/7acf3d7763f83142dae00ec3d72382a6_4137210704565935097.png', 'B,A,S', '2.7', 'PV +10%.', 'Si el portador es un personaje defensivo: cuando el portador ejecuta la técnica especial EX o cualquier personaje del equipo ejecuta un apoyo defensivo o apoyo evasivo, el daño infligido por todos los personajes del equipo aumenta en un 6 %. Pueden acumularse hasta 3 cargas durante 25 s. Las cargas se reducen una a una, y la duración se reinicia al obtener o perder cargas. Los efectos pasivos con el mismo nombre no se pueden acumular.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Dragon Taming Chariot» · Se compran a Roland y Elfy'),
  ('zzz-disc-1070', 'zenless-zone-zero', 'Diario de una prisionera', 'Notes From the Chained', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2026/03/23/ee7ad206fe6089cb283ddce94cf13ae2_1035147875814816092.png', 'B,A,S', '2.7', 'Daño glacial +10%.', 'Cuando el portador activa floridez, su Maestría de Anomalía aumenta en 48 ptos. durante 30 s. La duración se reinicia con cada activación. Al activar el efecto de congelación, el daño de Anomalía de Atributo y el de disfunción infligidos por el portador aumentan en un 16 % durante 30 s. La duración se reinicia con cada activación.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Dragon Taming Chariot» · Se compran a Roland y Elfy'),
  ('zzz-disc-129', 'zenless-zone-zero', 'Disco sacudestrellas', 'Shockstar Disco', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/b3feeb5bf8107a0f9aa81c948fb18d70_44281632904561529.png', 'B,A,S', '1.0', 'Aumenta el Impacto en un 6 %.', 'Aumenta el Aturdimiento infligido al objetivo principal por un ataque normal, un ataque rápido o un contraataque en un 20 %.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Hunter and Hound» · Se compran a Roland y Elfy'),
  ('zzz-disc-789', 'zenless-zone-zero', 'Fábula Yunkui', 'Yunkui Tales', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2025/09/05/15884296/e3c186b09bc8bbcd036df27f37c93ebc_5668772145058055136.gif', 'B,A,S', '2.0', 'PV +10%', 'Al ejecutar la técnica especial EX, la técnica en cadena o la técnica definitiva, la Probabilidad de Crítico aumenta en un 4% durante 15s. Pueden acumularse hasta 3 cargas. La duración se reinicia con cada activación. Al contar con 3 cargas de este efecto, el daño bruto aumenta en un 10%.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Words and Weapons» · Se compran a Roland y Elfy'),
  ('zzz-disc-1109', 'zenless-zone-zero', 'Firmamento llameante', 'The Sky Ablaze', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2026/06/16/83dc33403e36850f6aebab61d6a75a14_816854655715497740.png', 'B,A,S', '3.0', 'Daño etéreo +10%.', 'Si el portador es un agente etéreo, su Daño Crítico aumenta en un 30%. Al ejecutar una técnica especial EX o una técnica definitiva, el Ataque del portador aumenta en un 10% durante 30 s. La duración se reinicia con cada activación.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Pilot and the Rebel Mech» · Se compran a Roland y Elfy'),
  ('zzz-disc-913', 'zenless-zone-zero', 'Floración del alba', 'Dawn''s Bloom', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2025/09/06/15884296/1b2c821ed5493d3eaca50abb0640c8e9_1589613576234012269.gif', 'B,A,S', '2.2', 'El daño infligido por el ataque normal aumenta en un 15 %.', 'El daño del ataque normal aumenta en un 20 %. Si el portador es un personaje atacante, al usar una técnica especial EX o una técnica definitiva, el daño del ataque normal aumenta en un 20 % adicional durante 25 s. La duración se reinicia con cada activación.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Iron Law and Outlaws» · Se compran a Roland y Elfy'),
  ('zzz-disc-1176', 'zenless-zone-zero', 'Hado emplumado', 'Feathered Fate', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2026/08/04/19629685/34355a30be6ffe8ce259097b50fd7267_2191491146607477652.gif', 'B,A,S', '3.1', 'Maestría de Anomalía +30 ptos.', 'Al entrar en el campo de batalla o al pasar a ser el personaje activo, el portador obtiene la siguiente bonificación: la Maestría de Anomalía aumenta en 50 ptos. Si el portador es del atributo lumiflujo, el daño de Anomalía de Atributo infligido aumenta en un 15% durante 15s. Este efecto se mantiene activo incluso cuando el portador no es el personaje activo.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Swiftspine and Splitclaw» · Se compran a Roland y Elfy'),
  ('zzz-disc-392', 'zenless-zone-zero', 'Jazz caótico', 'Chaos Jazz', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/09/24/3331555e4253b676a447e42f29201fd6_5344025446086892407.png', 'B,A,S', '1.2', 'Maestría de Anomalía +30 ptos.', 'El daño ígneo y el daño eléctrico aumentan en un 15 %. Cuando el agente está inactivo, el daño infligido por la técnica especial EX y el ataque de apoyo aumenta en un 20 %. Una vez que el agente se vuelve activo, este efecto se prolonga durante 5 s. Puede activarse una vez cada 7.5 s.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Hunter and Beast» · Se compran a Roland y Elfy'),
  ('zzz-disc-5', 'zenless-zone-zero', 'Jazz oscilante', 'Swing Jazz', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/4f85a6c7c3f2a3bbde23b282b477f8dd_6306531671314941333.png', 'B,A,S', '1.0', 'Aumenta la Recuperación de Energía en un 20 %.', 'Al ejecutar una técnica en cadena o una técnica definitiva, aumenta el daño infligido por todos los miembros del equipo en un 15 % durante 12 s. Este efecto no se acumula con otros efectos del mismo nombre.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Monster and Weirdo» · Se compran a Roland y Elfy'),
  ('zzz-disc-624', 'zenless-zone-zero', 'Melodía de Faetón', 'Phaethon''s Melody', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2025/09/05/15884296/b38ce526744d80bf400e7ff77884edac_3292881930954170244.gif', 'B,A,S', '1.6', 'Tasa de Anomalía +8 %.', 'Cuando cualquier miembro del equipo ejecuta una técnica especial EX, la Maestría de Anomalía del portador aumenta en 45 ptos. durante 8 s. Si el agente que ejecuta la técnica especial EX no es portador, aunmenta el daño etéreo infligido por el portador en un 25 %.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Gunslinger vs Guardian» · Se compran a Roland y Elfy'),
  ('zzz-disc-134', 'zenless-zone-zero', 'Metal caótico', 'Chaotic Metal', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/d24db7eae8c2561bc49a1d72b9259364_3628772142390484587.png', 'B,A,S', '1.0', 'Aumenta el daño etéreo en un 10 %.', 'Aumenta el Daño Crítico del portador en un 20 %. Cuando cualquier miembro del equipo inflige daño adicional por medio del efecto de corrupción, dicha bonificación aumenta en un 5.5 % adicional durante 8 s. Pueden acumularse hasta 6 cargas. La duración se reinicia con cada activación.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Monster and Weirdo» · Se compran a Roland y Elfy'),
  ('zzz-disc-137', 'zenless-zone-zero', 'Metal colmilludo', 'Fanged Metal', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/6d11b8c1e66b1824d7d790d444cde696_1608329811533476236.png', 'B,A,S', '1.0', 'Aumenta el daño físico en un 10 %.', 'Cuando cualquier miembro del equipo provoca embestida al enemigo, aumenta el daño infligido por el portador al objetivo en un 35 % durante 12 s.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Fist and Gun» · Se compran a Roland y Elfy'),
  ('zzz-disc-135', 'zenless-zone-zero', 'Metal eléctrico', 'Thunder Metal', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/75f9b18188620315fa938eb30766a91b_6900706211802222766.png', 'B,A,S', '1.0', 'Aumenta el daño eléctrico en un 10 %.', 'Mientras haya enemigos afectados por electrochoque en combate, aumenta el Ataque del portador en un 28 %.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Hunter and Hound» · Se compran a Roland y Elfy'),
  ('zzz-disc-133', 'zenless-zone-zero', 'Metal infernal', 'Inferno Metal', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/16d66698b1d28c72040c270aac5919ff_3161385404722683377.png', 'B,A,S', '1.0', 'Aumenta el daño ígneo en un 10 %.', 'Al golpear a un enemigo afectado por calcinación, aumenta la Probabilidad de Crítico del portador en un 28 % durante 8 s.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Madman and Follower» · Se compran a Roland y Elfy'),
  ('zzz-disc-136', 'zenless-zone-zero', 'Metal polar', 'Polar Metal', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/1c3c63f61e89acf72f66fa49270b4e16_7690792437263479747.png', 'B,A,S', '1.0', 'Aumenta el daño glacial en un 10 %.', 'Aumenta el daño infligido por el ataque normal y el ataque rápido en un 20 %. Además, cuando un enemigo se ve afectado por los efectos de congelación o ruptura de hielo de cualquier miembro del equipo, el efecto aumenta en un 20 % durante 12 s.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Sharp Fang and Blunt Axe» · Se compran a Roland y Elfy'),
  ('zzz-disc-790', 'zenless-zone-zero', 'Monarca del Pináculo', 'King of the Summit', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2025/09/05/15884296/03e35db16c441db2b763b50adcf9d448_1550828084103241549.gif', 'B,A,S', '2.0', 'El Aturdimiento provocado por los ataques aumenta en un 6%.', 'Cuando el portador es un agente aturdidor y ejecuta la técnica especial EX o la técnica en cadena, el Daño Crítico de todos los personajes del equipo aumenta en un 15%; si la Probabilidad de Crítico del portador es mayor o igual a un 50%, el Daño Crítico aumenta en un 15% adicional, durante 15s. La duración se reinicia con cada activación. Los efectos pasivos con el mismo nombre no se pueden acumular.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Words and Weapons» · Se compran a Roland y Elfy'),
  ('zzz-disc-914', 'zenless-zone-zero', 'Nana a la luz cenicienta', 'Moonlight Lullaby', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2025/09/06/15884296/dfbd4ae42007e0c57e7656beb4ad5756_1624742920670101651.gif', 'B,A,S', '2.2', 'Recuperación de Energía +20 %.', 'Cuando el portador es un personaje auxiliar, al ejecutar la técnica especial EX o la técnica definitiva, el daño infligido por todos los personajes del equipo aumenta en un 18 % durante 25 s. La duración se reinicia con cada activación. Los efectos pasivos con el mismo nombre no se pueden acumular.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Iron Law and Outlaws» · Se compran a Roland y Elfy'),
  ('zzz-disc-131', 'zenless-zone-zero', 'Punk hormonal', 'Hormone Punk', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/0a758d895fa95d4f11f36371c057c1cb_4732503042787764309.png', 'B,A,S', '1.0', 'Aumenta el Ataque en un 10 %.', 'Al entrar en combate o al sustituir a un agente activo, aumenta el Ataque del portador en un 25 % durante 10 s. Puede activarse una vez cada 20 s.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Fist and Gun» · Se compran a Roland y Elfy'),
  ('zzz-disc-391', 'zenless-zone-zero', 'Punk primitivo', 'Proto Punk', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/09/24/9ed2248f48456f1533d602635034b25e_2030621787622153035.png', 'B,A,S', '1.2', 'Escudo +15%.', 'Cuando cualquier miembro del equipo ejecuta un apoyo defensivo o un apoyo evasivo, el daño provocado por todos los miembros del equipo aumenta en un 15 % durante 10 s. Este efecto no se acumula con otros efectos del mismo nombre.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Hunter and Beast» · Se compran a Roland y Elfy'),
  ('zzz-disc-132', 'zenless-zone-zero', 'Rock espiritual', 'Soul Rock', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/b4fd81cd50ea47a2107308e7a11d8a55_5618445283317531443.png', 'B,A,S', '1.0', 'Aumenta la Defensa en un 16 %.', 'Al perder PV por un ataque enemigo, se reduce el daño recibido del portador en un 40 % durante 2.5 s. Puede activarse 1 vez cada 15 s.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Tower and Cannon» · Se compran a Roland y Elfy'),
  ('zzz-disc-1177', 'zenless-zone-zero', 'Rosa espinosa', 'Thorned Rose', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2026/08/04/19629685/443ecb59e755b5c312492d6812984b53_1752981105593183764.gif', 'B,A,S', '3.1', 'Defensa +16%.', 'El daño infligido por el portador aumenta en un 15%. Si la Defensa inicial del portador es igual o superior a 1000/1800 ptos., la Probabilidad de Crítico aumenta en un 8/16%.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Swiftspine and Splitclaw» · Se compran a Roland y Elfy'),
  ('zzz-disc-1108', 'zenless-zone-zero', 'Salón huracanado', 'Wuthering Salon', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2026/06/16/629118bce003a8c9aba77f5f06ca059f_6802818800811286167.png', 'B,A,S', '3.0', 'Daño aéreo +10%.', 'Cuando el portador ejecuta una técnica especial EX, su Maestría de Anomalía aumenta en 25 ptos. durante 40 s. Pueden acumularse hasta 2 cargas. La duración se reinicia con cada activación. Al activar el efecto de erosión, el daño del portador aumenta en un 18 % durante 40 s. La duración se reinicia con cada activación.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Pilot and the Rebel Mech» · Se compran a Roland y Elfy'),
  ('zzz-disc-127', 'zenless-zone-zero', 'Tecno pícido', 'Woodpecker Electro', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/0d4dd047370168a3b992d9884ca926c6_8904461176918742696.png', 'B,A,S', '1.0', 'Aumenta la Probabilidad de Crítico en un 8 %.', 'Al golpear al enemigo con un ataque normal, un contraataque o una técnica especial EX, ejecuta un golpe crítico y otorga al portador 1 carga de bonificación. Cada carga aumenta el Ataque del portador en un 9 % durante 6 s. La duración de cada técnica se cuenta por separado.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Tower and Cannon» · Se compran a Roland y Elfy'),
  ('zzz-disc-128', 'zenless-zone-zero', 'Tecno tetraodóntido', 'Puffer Electro', 'https://act-webstatic.hoyoverse.com/event-static-hoyowiki-admin/2024/07/09/554cb9ae3eea679586cc85ac4cd586c0_9111840743195019243.png', 'B,A,S', '1.0', 'Aumenta la Tasa de Perforación en un 8 %.', 'Aumenta el daño infligido por técnicas definitivas en un 20 %. Al ejecutar una técnica definitiva, aumenta el Ataque del portador en un 15 % durante 12 s.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Madman and Follower» · Se compran a Roland y Elfy'),
  ('zzz-disc-546', 'zenless-zone-zero', 'Voz astral', 'Astral Voice', 'https://act-upload.hoyoverse.com/event-ugc-hoyowiki/2024/12/25/19629685/094475f6f4754f4175941caf8a570f95_331379326623098101.png', 'S', '1.4', 'Ataque +10 %.', 'Cuando cualquier miembro del equipo entra en combate por medio de un apoyo rápido, todos los miembros del equipo obtienen 1 carga de eufonía durante 15 s. Pueden acumularse hasta 3 cargas. La duración se reinicia con cada activación. Por cada carga de eufonía, el daño infligido de los miembros del equipo que entran en combate por medio de un apoyo rápido aumenta en un 8 %. Este efecto solo puede aplicarse una vez por todos los miembros del equipo.', '[{"ranura":1,"stats":"PV"},{"ranura":2,"stats":"ATQ"},{"ranura":3,"stats":"DEF"},{"ranura":4,"stats":"% PV, % ATQ, % DEF, Probabilidad de Crítico, Daño Crítico, Maestría de Anomalía"},{"ranura":5,"stats":"% PV, % ATQ, % DEF, Tasa de Perforación, Bono de daño de cualquier atributo"},{"ranura":6,"stats":"% PV, % ATQ, % DEF, Tasa de Anomalía, Impacto, Recuperación de Energía"}]'::jsonb, 'Limpieza rutinaria «Monster Duet» · Se compran a Roland y Elfy')
on conflict (id) do update
  set name = excluded.name,
      name_en = excluded.name_en,
      image_url = excluded.image_url,
      grades = excluded.grades,
      version = excluded.version,
      two_piece = excluded.two_piece,
      four_piece = excluded.four_piece,
      main_stats = excluded.main_stats,
      how_to_get = coalesce(excluded.how_to_get, public.drive_discs.how_to_get),
      updated_at = now();

-- Comprobacion: 30 discos, todos con icono y efectos.
select count(*) as total,
       count(*) filter (where image_url is null) as sin_icono,
       count(*) filter (where two_piece is null or four_piece is null) as sin_efectos,
       count(*) filter (where how_to_get is null) as sin_origen
from public.drive_discs
where game_id = 'zenless-zone-zero';
